### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by god33** [HandyOrg/HandyControl#1]
例如：
1、错误		未在类型“CompareSlider”中找到可附加的属性“TargetContent”。	 

2、错误		命名空间“clr-namespace:HandyControl.Controls;assembly=HandyControl”中不存 
类似这样的几百个。

**Comment by god33** [comment]
您好，感谢回复。我用的是vs2015，.net是4.6.1，我装个2017试试呢




在 2018-09-03 11:20:14，"纳边" <notifications@github.com> 写道：


你好，请问你的开发环境是vs2017，.net环境是4.6.2吗

**Comment by god33** [comment]
能不能降低点版本呢，现在vs2017还是很少有人用的




在 2018-09-03 11:20:14，"纳边" <notifications@github.com> 写道：


你好，请问你的开发环境是vs2017，.net环境是4.6.2吗

**Comment by NaBian** [comment]
.net最低要求是4.5，vs版本由于受c#的版本所限制，暂时只支持vs2017，但是只要把一些7.0的语法改为6.0就能支持vs2015了。

**Comment by god33** [comment]
7.0的语法好像很多啊，1000多行。难度挺大的





在 2018-09-04 21:34:50，"纳边" <notifications@github.com> 写道：


.net最低要求是4.5，vs版本由于受c#的版本所限制，暂时只支持vs2017，但是只要把一些7.0的语法改为6.0就能支持vs2015了。
