### ISSUE TITLE
 Nuget安装的最新HandyControl中没有DrawerContainer？

### ISSUE THREAD

**Issue by alsbingo** [HandyOrg/HandyControl#1012]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - .net: [e.g. 4.6.2]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by NaBian** [comment]
对，在下个版本。
