### ISSUE TITLE
Button's height doesn't increase when the content font size increases.

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#1015]
I'm setting the font size of button's content in xaml. When the font size of the content is increased above 12, the height of the button must increase proportionately to fit the content inside the button. But that doesn't happen, the height stays 30 irrespective of the font size.

**Comment by NaBian** [comment]
assign the height to auto

**Comment by ms-somanna** [comment]
> assign the height to auto

Shouldn't it be assigned automatically?

**Comment by NaBian** [comment]
fixed-height can keep the ui style consistent, otherwise, some people set the height to 30 and some people set 28 in the same project, it's terrible.

**Comment by ms-somanna** [comment]
> fixed-height can keep the ui style consistent, otherwise, some people set the height to 30 and some people set 28 in the same project, it's terrible.

I see.

**Comment by JasperCalapini** [comment]
Hi, I am also having issues regarding on the height of the buttton.

> assign the height to auto

This works when I run the program _but not 'quite' in the designer view_. 

```
<Grid>
<Button Height="auto" 
        VerticalAlignment="Stretch"
        HorizontalAlignment="Stretch"
        Text="Fill the Grid">
</Grid>
```

In the designer's view, only the `HorizontalAlignment="Stretch"` works. When I look at the properties on the `Button`, It says *Auto (30)*. When I set a constant height like `Height="10"` then set it back `Height="auto"`, The `VerticalAlignment="Stretch"` work. ***BUT when you reopen the project, the _VerticalAlignment_ won't work again, height will again _auto(30)_ on the properties*.**

It works on Runtime but It would be nice if it works on designer view as well.

I am new to this wpf/programming and trying this wonderful package.
