### ISSUE TITLE
SideMenu与ScrollViewer搭配使用时，存在鼠标悬停在SideMenu内容上滚动滑轮，滚动条不起效的问题

### ISSUE THREAD

**Issue by NickNameIsNull** [HandyOrg/HandyControl#103]
鼠标需要悬停在滚动条上，滚动滑轮，才能实现滚动；
由于MarkDown不是很识别代码，有代码被吞的情况，将复现代码上传在附件中：
[CodeReview.txt](https://github.com/HandyOrg/HandyControl/files/3297719/CodeReview.txt)

问题gif：
![滚动问题](https://user-images.githubusercontent.com/16376037/59616448-04c96300-9157-11e9-9360-d682a90c8ae7.gif)

**Comment by NaBian** [comment]
@RemoveLove SideMenu自带滚动条，不需要在外面包一层ScrollViewer
