### ISSUE TITLE
HandyControl.Controls.TextBox 开放 VerifyFunc 属性没有做好防逗比措施

### ISSUE THREAD

**Issue by lindexi** [HandyOrg/HandyControl#109]
我是逗比，只要能写出的逗比代码我就会写出来

我看到 HandyControl.Controls.TextBox 很高兴，因为听说里面可以写校验的方法

我看到了 Func<string, OperationResult<bool>> VerifyFunc 属性，这个属性就是用于写校验代码的，我看到我的小伙伴在界面用了 TextBox 于是我就帮他添加一点有趣的代码

        public void F1()
        {
            TextBox.VerifyFunc = s => new OperationResult<bool>()
            {
                Data = true,
                Message = "林德熙是逗比",
                ResultType = ResultType.Failed
            };
        }

        public void F2()
        {
            TextBox.VerifyFunc = s => new OperationResult<bool>()
            {
                Data = true,
                Message = "林德熙不是逗比",
                ResultType = ResultType.Success
            };
        }

请问在不知道 F1 和 F2 的调用顺序和被多少次调用请问每次校验的时候返回的是什么？其实我也不知道

也许我也会将这个函数用于做回调

            TextBox.VerifyFunc += s =>
            {
                Console.WriteLine("用来文本改变了");
                return null;
            };

这个控件很好用，只是没有做好防逗比

**Comment by NaBian** [comment]
@lindexi 大佬，我看不懂，有点懵圈

**Comment by lindexi** [comment]
@NaBian 开放一个委托作为属性是比较难做到防逗比的

**Comment by NaBian** [comment]
@lindexi 只要写这些代码的人高兴就好，控件库不在乎这些
