### ISSUE TITLE
使用BlurWindow时，鼠标拖动窗口卡顿、延迟

### ISSUE THREAD

**Issue by yobyzal** [HandyOrg/HandyControl#116]
**Describe the bug**
使用 `hc:BlurWindow` 时，鼠标拖动窗口特别卡顿而且伴有延时。

**To Reproduce**
1. 克隆仓库到本地（commit：e514d738fe3bd5a4fa69a307b9eb900c0d52e28c）
2. 编译运行 `HandyControlDemo_Net_GE45`
3. 使用鼠标快速拖动窗口

**Environment (please complete the following information):**
 - .net: [4.5]
 - IDE [vs2019]
 - Version [16.1.4]
 - Windows [企业版，Insider Preview，Build 18922.rs_prerelease.190614-1427]

**Comment by NaBian** [comment]
@yobyzal 这是自1903起的window bug，相同的问题详见这里：[bug](https://github.com/sourcechord/FluentWPF/issues/42#issue-435394099)
