### ISSUE TITLE
NumericUpDown 使用键盘输入数据不触发ValueChanged事件

### ISSUE THREAD

**Issue by lanzhiquan** [HandyOrg/HandyControl#1162]
### Describe the bug

NumericUpDown 使用键盘输入数据不触发ValueChanged事件。3.3版本之前不会有此问题，3.3版出现。

### Steps to reproduce the bug

`           <hc:NumericUpDown Name="NumericUpDown1" Minimum="-999999.0" Maximum="999999.0" Value="666.123" DecimalPlaces="6"></hc:NumericUpDown>`

**Comment by thirking** [comment]
为什么关掉了，这个Issue，我感觉这个问题还存在呀

**Comment by NickNameIsNull** [comment]
查看git记录，应该是在3.13 作者进行输入控件重构时，去掉了_textBox的TextChanged事件；出现了Text输入后，不触发ValueChanged事件；
![image](https://user-images.githubusercontent.com/16376037/177457632-771a3d8a-6f5b-4f8f-b54d-f3ebbba9e45f.png)
