### ISSUE TITLE
希望能加入可以多选的Combox扩展控件

### ISSUE THREAD

**Issue by 5653325** [HandyOrg/HandyControl#117]
最好是可以分组的那种，比如下拉后显示如下这种格式
分组一（文字，不可选中）
可选内容一
可选内容二
可选内容三
分组二（文字，不可选中）
可选内容一
可选内容二
可选内容三
谢谢。

**Comment by noctwolf** [comment]
修改默认模板做了个简单的例子
[模板修改1](https://github.com/noctwolf/Samples/blob/1a9939d768650dc24647bf9d10e27344f7972f37/ComboBox%E5%A4%9A%E9%80%89%E5%88%86%E7%BB%84/MainWindow.xaml#L28-L40)
[模板修改2](https://github.com/noctwolf/Samples/blob/1a9939d768650dc24647bf9d10e27344f7972f37/ComboBox%E5%A4%9A%E9%80%89%E5%88%86%E7%BB%84/MainWindow.xaml#L48-L55)
[添加分组描述](https://github.com/noctwolf/Samples/blob/1a9939d768650dc24647bf9d10e27344f7972f37/ComboBox%E5%A4%9A%E9%80%89%E5%88%86%E7%BB%84/MainWindow.xaml.cs#L32-L33)
![](https://user-images.githubusercontent.com/21022467/60535748-6680f400-9d37-11e9-90d1-e146a69deee3.png)

**Comment by 5653325** [comment]
> 修改默认模板做了个简单的例子
> [模板修改1](https://github.com/noctwolf/Samples/blob/1a9939d768650dc24647bf9d10e27344f7972f37/ComboBox%E5%A4%9A%E9%80%89%E5%88%86%E7%BB%84/MainWindow.xaml#L28-L40)
> [模板修改2](https://github.com/noctwolf/Samples/blob/1a9939d768650dc24647bf9d10e27344f7972f37/ComboBox%E5%A4%9A%E9%80%89%E5%88%86%E7%BB%84/MainWindow.xaml#L48-L55)
> [添加分组描述](https://github.com/noctwolf/Samples/blob/1a9939d768650dc24647bf9d10e27344f7972f37/ComboBox%E5%A4%9A%E9%80%89%E5%88%86%E7%BB%84/MainWindow.xaml.cs#L32-L33)
> ![](https://user-images.githubusercontent.com/21022467/60535748-6680f400-9d37-11e9-90d1-e146a69deee3.png)

最好是CheckBox的多选项。哈哈

**Comment by noctwolf** [comment]
设置ListBox的模板就可以 😸 
```xaml
            <ListBox.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <CheckBox Content="{Binding Title}" 
                                  IsChecked="{Binding IsSelected, 
                            RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type ListBoxItem}}}"/>
                    </Grid>
                </DataTemplate>
            </ListBox.ItemTemplate>
```

**Comment by 5653325** [comment]
谢谢
