### ISSUE TITLE
右键菜单鼠标缓慢移动，第二级菜单会消失

### ISSUE THREAD

**Issue by XifanRD** [HandyOrg/HandyControl#118]
第一、鼠标快速滑动会有概率点击二级菜单

![image](https://user-images.githubusercontent.com/10935995/61039555-8e401e00-a401-11e9-9d69-304f3d2b2944.png)

第二、缓慢移动到滚动条时，二级菜单消失，鼠标点不中
![image](https://user-images.githubusercontent.com/10935995/61039645-be87bc80-a401-11e9-9603-7a9c4458263a.png)

请确认下是否可以修复

**Comment by NaBian** [comment]
@XifanRD 谢谢，问题已通过修改menu样式修复
