### ISSUE TITLE
visual studio will hang if we use netcore3

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#121]
hi, If we use handycontrol in .NETCore3, then after a while (Building and running several times) Visual Studio will hang
I tested netcore3 without using the handycontrol , and Visual studio did not have a problem

[xx.zip](https://github.com/HandyOrg/HandyControl/files/3388732/xx.zip)

**Comment by NaBian** [comment]
@ghost1372 what is the version of your vs

**Comment by ghost1372** [comment]
@Nabian vs 2019  16.2 preview 3

**Comment by NaBian** [comment]
@ghost1372  if you restart the vs, everything will be ok, i have no idea about this issue, it could be vs's problem. 🤔

**Comment by ghost1372** [comment]
@NaBian  Every time I get a restart, the problem gets bigger 😅 anyway, thanks for your consideration, I share with the Visual team

**Comment by metheofanis** [comment]
I have the same problem. Visual Studio 2019 hangs in random intervals.
If I restart then it works again.
Any solution yet?

**Comment by ghost1372** [comment]
@tprodromos  I haven't found a solution yet

**Comment by metheofanis** [comment]
Thank you!

**Comment by NaBian** [comment]
@ghost1372 does this problem still exist on version 16.3.* ?

**Comment by ghost1372** [comment]
@NaBian  Fortunately not at present

**Comment by NaBian** [comment]
great, look at a few more versions.

**Comment by ghost1372** [comment]
ok😉

**Comment by NaBian** [comment]
@ghost1372 can we close this issue?

**Comment by ghost1372** [comment]
@NaBian I think yes
No problem so far
