### ISSUE TITLE
imageblock value does not fall

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#123]
run demo and click on imageblock item
![Untitled](https://user-images.githubusercontent.com/9213496/61517602-e63bdd80-aa1c-11e9-87ee-2c77da70fa1f.png)

**Comment by NaBian** [comment]
according to the steps you said, there was no problem on my computer.

**Comment by ghost1372** [comment]
@NaBian  Please watch the video
I cloned the latest version from the site
[qqq.zip](https://github.com/HandyOrg/HandyControl/files/3413256/qqq.zip)

**Comment by noctwolf** [comment]
看视频发现缩放不是100%，用125%已重现

**Comment by ghost1372** [comment]
@noctwolf  yes, i tested in 100% and worked fine, but in 125% failed.
so, why this happened?

**Comment by ghost1372** [comment]
@noctwolf  tnx for pr
Can you check this issue too?
https://github.com/HandyOrg/HandyControl/issues/4

**Comment by noctwolf** [comment]
> @noctwolf tnx for pr
> Can you check this issue too?
> #4

我尝试了125%，不能重现白色边框
![125](https://user-images.githubusercontent.com/21022467/61577750-6ac25500-ab1e-11e9-8869-ad490b5ca7f2.png)

**Comment by ghost1372** [comment]
@noctwolf  tnx, So maybe the problem is with my monitor
did you try maximized app?
The screenshot you sent is not a full screen application

**Comment by noctwolf** [comment]
哦，我重现了。是最大化时的Padding/Margin导致的。
https://github.com/HandyOrg/HandyControl/blob/e722fa6fd06db92e5c21453eef87b8adc653e7e9/src/Net_GE45/HandyControl_Net_GE45/Themes/Styles/Window.xaml#L119
从8修改为7可以修复你的问题，但是我不确定这个值的依据和兼容性，所以就不pr了

**Comment by ghost1372** [comment]
@noctwolf  tnx Modifying from 8 to 7 fixed problem, @NaBian  do you have any idea?

**Comment by NaBian** [comment]
@ghost1372 I'm working on it.
