### ISSUE TITLE
TabContrl使用代码动态添加TabItem会导致TabControl左右滚动宽度计算错误的问题

### ISSUE THREAD

**Issue by NickNameIsNull** [HandyOrg/HandyControl#129]
由于目前HC的TabControl不支持绑定，所以我在后台代码中去添加TabItem，出现了下面动图所式的情况。
![TabContrlTest](https://user-images.githubusercontent.com/16376037/61587833-f5a95b00-abc3-11e9-859b-fde76b25748e.gif)
这个问题在窗体大小改变后、tabitem关闭后，左右的滚动也会存在异常的情况。
代码在附件.zip中：
[HandControlTest.zip](https://github.com/HandyOrg/HandyControl/files/3414361/HandControlTest.zip)

**Comment by NaBian** [comment]
已解决: 445bef0
