### ISSUE TITLE
Clock BorderTitle_OnMouseWheel

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#131]
MouseWheel on Clock BorderTitle only change se
[zxzxzxzxzx.zip](https://github.com/HandyOrg/HandyControl/files/3422239/zxzxzxzxzx.zip)
c (no effect in minute and clock)

**Comment by NaBian** [comment]
that's how it was designed

**Comment by ghost1372** [comment]
so, this is not bug👌
