### ISSUE TITLE
ComboBoxBaseStyle样式变化导致影响控件默认高度，版本2.1

### ISSUE THREAD

**Issue by noctwolf** [HandyOrg/HandyControl#142]
GE45的2.1版本，ComboBoxBaseStyle的Height变更为MinHeight，导致控件的默认外观异常。
影响控件 ComboBox
不影响控件 hc:ComboBox
在2.0版本中表现正常

2.0样式https://github.com/HandyOrg/HandyControl/blob/832513af6fe66c34a4bcbaed203683cf73972ce6/src/Net_GE45/HandyControl_Net_GE45/Themes/Styles/Base/ComboBoxBaseStyle.xaml#L514

2.1样式https://github.com/HandyOrg/HandyControl/blob/41f2f039cec4be3bb1ff480af35ef4f687ac5131/src/Net_GE45/HandyControl_Net_GE45/Themes/Styles/Base/ComboBoxBaseStyle.xaml#L514

![使用2 1版本](https://user-images.githubusercontent.com/21022467/62422708-62a31180-b6e9-11e9-911a-8a033ed55a92.png)

**Comment by NaBian** [comment]
@noctwolf 已解决
