### ISSUE TITLE
TabControl issue

### ISSUE THREAD

**Issue by arunkanojia1102** [HandyOrg/HandyControl#144]
I have added TabControl in a wpf page and bind the itemsource from viewmodel. But whenever I am closing a tab and trying to remove it from tabcollection it show me error.

**Environment 
 - .net: 4.6
 - IDE : 2017
 - Version 1.0.0

**Comment by M0n7y5** [comment]
Please provide more info

**Comment by NaBian** [comment]
@arunkanojia1102 To be supported
