### ISSUE TITLE
English language for issues

### ISSUE THREAD

**Issue by keytrap-x86** [HandyOrg/HandyControl#154]
**Is your feature request related to a problem? Please describe.**
I don't understand Chinese and some of the issues are written in Chinese. When I look for a solution before opening an issue it's quite difficult. For example, I have a problem with BlurWindow and I saw a closed issue [related to BlurWindow](https://github.com/HandyOrg/HandyControl/issues/116) but I don't know what it is about because when I try to translate (I'm french), as the page is half english half chinese, I translates from English to french and chinese stays the same.

**Describe the solution you'd like**
I think It would be nice that everyone creates their issues in english so that people over the world understand them.

**Comment by NaBian** [comment]
of course, it would be the most effective way, if everyone uses the same language to communicate. However the world itself is pluralistic, indeed it's troublesome to communicate or read across languages, while we can still use some translation tools, although the result may be a little vague, it is barely understandable.

actually, I translated all the above words with translation tools, there may be grammatical errors, I think you should be able to understand what I'm going to say. 

finally, I can simply translate the issue which you're talking about:

**Describe the bug**
the hc:BlurWindow will be stuttering when I drag it.

**To Reproduce**
Steps to reproduce the behavior:
clone the repo to local（commit：e514d738fe3bd5a4fa69a307b9eb900c0d52e28c）
Compile and Run HandyControlDemo_Net_GE45
Drag the window quickly

**Environment (please complete the following information):**
.net: [4.5]
IDE [vs2019]
Version [16.1.4]
Windows [Enterprise version，Insider Preview，Build 18922.rs_prerelease.190614-1427]
