### ISSUE TITLE
WaveProgressBar animation at 100%

### ISSUE THREAD

**Issue by keytrap-x86** [HandyOrg/HandyControl#156]
**Describe the bug**
When you get to 100%, you can still see the wave of the WaveProgressBar

**To Reproduce**
1. Add a WaveProgressBar
2. Set value to 100%

**Expected behavior**
I'm not sure we're supposed to see the wave when we are at 100%

**Screenshots**
![image](https://i.imgur.com/tLWqzZM.gif)

**Environment (please complete the following information):**
 - .net: 4.7.1
 - IDE Visual Studio 2019
 - Version 16.2.2

**Comment by NaBian** [comment]
yes, that's how the design is.
