### ISSUE TITLE
Set border radius as option on TransitioningContentControl

### ISSUE THREAD

**Issue by keytrap-x86** [HandyOrg/HandyControl#157]
**Is your feature request related to a problem? Please describe.**
Actually the border radius of TransitioningContentControl is hard coded in the XAML code of the control. 
![image](https://user-images.githubusercontent.com/17864005/63218304-f9df7e80-c157-11e9-8b83-6cf0839963c0.png)

It's a bit problematic when you have a side menu next to it which has no border radius. This is the result :

![image](https://user-images.githubusercontent.com/17864005/63218265-79208280-c157-11e9-8035-053d039ff769.png)

**Describe the solution you'd like**
The corner radius should be an option so that we can set it or not.

**Additional context**
Temporary fix : put the TransitioningContentControl in a grid and set it's background to `{x:Null}` then set the grid's background to the wanted color

**Comment by NaBian** [comment]
emmm, we're going to rewrite this control.

**Comment by NaBian** [comment]
we will remove the border outside in add-SplitButton branch
