### ISSUE TITLE
Cannot bind PasswordBox's Password property

### ISSUE THREAD

**Issue by keytrap-x86** [HandyOrg/HandyControl#159]
**Describe the bug**
I cannot bind the `PasswordBox`'s `Password` property to a static string (for example from Properties.Settings.Default). Error is :
`Cannot define 'Binding' of 'Password' property of type 'PasswordBox'. You can only define a binding on an DependencyObject 's DependencyProperty`

**To Reproduce**
1. Add a `hc:PasswordBox`
2. Try to bind a value to the `Password` property

**Expected behavior**
Value binds

**Environment (please complete the following information):**
 - .net: 4.5
 - IDE Visual Studio 2019
 - Version 16.2.2

**Additional context**
XAML Code :

```XAML
xmlns:properties="clr-namespace:Watchguard.Report.Properties"
```

```XAML
<hc:PasswordBox x:Name="TxtPassword"
Password="{Binding Source={x:Static properties:Settings.Default}, 
Path=Password, Mode=TwoWay}"  />
```

**Comment by ghost1372** [comment]
I don't think this is a bug.
Take a look here

> When you try to databind the password property of a PasswordBox you will recognize that you cannot do data binding on it. The reason for this is, that the password property is not backed by a DependencyProperty.
> 
> The reason is databinding passwords is not a good design for security reasons and should be avoided
> 

https://www.wpftutorial.net/PasswordBox.html

**Comment by keytrap-x86** [comment]
@ghost1372 Hello, thanks for the answer. It would be nice a to have a 'ActualPassword' DependecyProperty which will act like Text and not SecureString. Btw, why is there no PasswordChanged event ? Or TextChanged ?

**Comment by ghost1372** [comment]
@TheKeytrap  there is, Use it like this

```
        <hc:PasswordBox PasswordBox.PasswordChanged="PasswordBox_PasswordChanged"/>
```

**Comment by keytrap-x86** [comment]
@ghost1372 Thanks !
