### ISSUE TITLE
Add TransitionType for TransitioningContentControl

### ISSUE THREAD

**Issue by keytrap-x86** [HandyOrg/HandyControl#165]
**Is your feature request related to a problem? Please describe.**
I think that this control is a bit limited because we are not able to choose a transition type.

**Describe the solution you'd like**
It would be nice to add few Transition Effects (I'm inspired by [this](https://www.codeproject.com/Articles/197132/Simple-WPF-Page-Transitions))

**Comment by ghost1372** [comment]
@TheKeytrap  please check wiki first, there is Transition property with 4 animation

 [DefaultTransition, Normal, UpTransition, DownTransition]

https://github.com/ghost1372/HandyControl/wiki/TransitioningContentControl-Control
