### ISSUE TITLE
switch样式按钮宽度不能变

### ISSUE THREAD

**Issue by Princebin** [HandyOrg/HandyControl#176]
switch样式按钮宽度变大，效果不会变

**Comment by cyoann** [comment]
You need to provide more information.

Please write in English, the non-Chinese can never help if you only speak to each other.

**Comment by NaBian** [comment]
@Princebin 请稍微详细地描述一下问题

**Comment by NaBian** [comment]
在设计上，switch的宽高比是固定的，所以单独改变宽度会无效，请考虑调整高度。

**Comment by GF-Huang** [comment]
> 在设计上，switch的宽高比是固定的，所以单独改变宽度会无效，请考虑调整高度。

Modify the `Height` property not work.

![image](https://user-images.githubusercontent.com/4510984/99465885-352db600-2976-11eb-978b-dfa7434190bd.png)
