### ISSUE TITLE
Can you add the tooltip information feature??

### ISSUE THREAD

**Issue by mummyildiz** [HandyOrg/HandyControl#177]
If Tooltip Text is full on TextBox objects, can we inform the end user as in the picture?
Can we determine the color at the bottom right and separately?

to inform when it comes with the mouse.

![bbbb](https://user-images.githubusercontent.com/5136066/65300244-78767400-db7b-11e9-8b0d-8a3b1cf4b60e.png)

**Comment by AdarshRise** [comment]
It got added, I guess.

**Comment by NaBian** [comment]
you can use poptip now
