### ISSUE TITLE
Rate value is wrong

### ISSUE THREAD

**Issue by keytrap-x86** [HandyOrg/HandyControl#179]
**Describe the bug**
Rate value isn't correct while trying to get it.

**To Reproduce**
1. Clone this repo
2. Add MouseDown event on Rate control and add Console.WriteLine
![image](https://user-images.githubusercontent.com/17864005/65394220-22781b00-dd8b-11e9-905c-7903ef4834ce.png)
Click on Rateitem

**Expected behavior**
Right value is shown

**Screenshots**
![fail](https://user-images.githubusercontent.com/17864005/65394155-4424d280-dd8a-11e9-8676-778e4531e51c.gif)

**Environment (please complete the following information):**
 - .net: [e.g. 4.7.1]
 - IDE [e.g. vs2019]

**Additional context**

**Comment by NaBian** [comment]
Added valuechanged event.
Don't get value of rate in mousedown event or any other event, value property is not under its control.

**Comment by keytrap-x86** [comment]
@Nabian I was using it because there was no proper event. Thanks
