### ISSUE TITLE
SideMenu enhancement 

### ISSUE THREAD

**Issue by metheofanis** [HandyOrg/HandyControl#182]
I would like to suggest an enhancement for SideMenu:
Make it Slide In/Out on MouseEnter/MouseLeave events. Also, a button to pin it.
Something like this:
[https://www.youtube.com/watch?v=9RQ7hW5Jnu0](https://www.youtube.com/watch?v=9RQ7hW5Jnu0)
Or this:
[https://www.youtube.com/watch?v=YQ1EJJZBHyE](https://www.youtube.com/watch?v=YQ1EJJZBHyE)

Thanks

**Comment by NaBian** [comment]
now you can use Drawer to implement it.

**Comment by metheofanis** [comment]
Thank you very much!
