### ISSUE TITLE
GeometryAnimation crash

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#184]
**Describe the bug**
when i click on morphing animation i get crash

**To Reproduce**
1. Go to Demo
2. Click on Morphing Animation

**Environment (please complete the following information):**
 - IDE vs2019

`System.FormatException: 'Unexpected token 'M41/416254,90C41/88876,82/5298 41/624584,57/2716 41/416254,50/99 36/29352,49/8907 36/894651,50/4264 31/567267,50/99 31/775597,44/59305 31/931627,42/43234 31/693536,36/77758 36/340008,36/79568 35/133525,36/76858 41/542523,36/58818 41/638383,32/81458 41/675605,33/50908 41/668792,29/20144 41/851382,25/46201 41/182183,18/65836 45/961941,14/23856 50/741699,9/81876 59/568752,10/59048 68/185297,10/70302 68/141127,16/44056 68/145937,20/8288 68/185297,23/58247 63/135373,24/4635 60/876109,23/24558 57/326157,24/84516 55/922779,28/231 55/756556,29/65047 56/63466,36/77758 59/21143,36/64422 64/265254,36/63978 68/690373,36/77758 67/695215,42/78657 67/742088,44/40134 66/922606,49/8464 63/245981,49/9344 61/316885,49/6976 55/810928,49/8464 55/662114,56/6024 56/168075,82/8571 55/810928,90 49/382352,90/1786 47/63649,89/97 41/416254,90z' encountered at position '2'.'
`
![Untitled](https://user-images.githubusercontent.com/9213496/65791236-2da5bf00-e16e-11e9-8a24-e892d8b57e8d.png)

**Comment by ghost1372** [comment]
@NaBian  tnx for your commit but issue is not fixed in my pc

**Comment by NaBian** [comment]
erm....it seems that commas were replaced with slashes, can you help me to resolve this issue? due to the cultrue environment of my pc, I can't repeat this problem.

**Comment by ghost1372** [comment]
@NaBian  yeah i can what do you need? i can start a visual studio liveshare or anything you want
`https://prod.liveshare.vsengsaas.visualstudio.com/join?19F79D44B180F80D01F53354E467E90981B0`

**Comment by NaBian** [comment]
It's too late. Is tomorrow all right?

**Comment by ghost1372** [comment]
From 7am to 7pm I'm at work (GMT +3:30)
I'm online from 7pm

**Comment by ghost1372** [comment]
hi @NaBian  I think this code is not a good solution Because it makes other controls not work as well as DatePicker and anything that includes slash character (/) I think we should delete this code And we can use a better solution Like changing the way geometry is created with the help of StreamGeometry or anything else

https://github.com/HandyOrg/HandyControl/blob/cfe20a7f13822eb9450c110a6b60401a415d2eee/src/Shared/HandyControl_Shared/Tools/Helper/ConfigHelper.cs#L47

**Comment by ghost1372** [comment]
@NaBian  tnx but this fix also not work 🤔 

![Untitled](https://user-images.githubusercontent.com/9213496/67950590-20617180-fbff-11e9-92c6-2c8ad6737905.png)

I had a conversation about this [here](https://github.com/dotnet/wpf/issues/2132#issuecomment-548083460) If you have the time please take a look at it
