### ISSUE TITLE
NumericUpDown can have value outside of defined minimum and maximum

### ISSUE THREAD

**Issue by lasgor** [HandyOrg/HandyControl#189]
**Describe the bug**
NumericUpDown coerces the value if using the up/down buttons, but you can still enter number outside of min-max and when the control looses focus no coercion is performed.

**To Reproduce**
In NumericUpDown enter number outside of min-max, tab out. No coercion happens.

**Expected behavior**
Should not be able to enter value outside min-max.

**Environment**
 - .net [4.0]
 - IDE [vs2019]
 - Version [2.2.0]

**Comment by lasgor** [comment]
Commenting out this line in NumericUpDown.cs seems to fix the issue:
![image](https://user-images.githubusercontent.com/15315148/65823224-aaaa6480-e252-11e9-9036-5ef55541360f.png)

**Comment by 1111chance** [comment]
我也碰到这个问题ε=(´ο｀*)))唉
