### ISSUE TITLE
希望轮播能加入触摸滑动

### ISSUE THREAD

**Issue by yanhan-dev** [HandyOrg/HandyControl#19]
希望轮播能加入触摸滑动

**Comment by NaBian** [comment]
你好:smile:，在统一为整个控件库添加触控支持和优化时会考虑这个需求的。

**Comment by walterlv** [comment]
然而，并不需要统一设计整个控件库的触摸，因为 WPF 本身对触摸的支持也是不怎么好的，你再加设计也解决不了多少东西，反而会踩坑。

参见：[WPF 程序无法触摸操作？我们一起来找原因和解决方法！ - walterlv](https://blog.walterlv.com/wpf/2017/09/12/touch-not-work-in-wpf.html )

**Comment by NaBian** [comment]
@walterlv 那么我就关闭这个issue了

**Comment by walterlv** [comment]
@NaBian 单独解决这个就好
