### ISSUE TITLE
MVVM模式下TabItem的Header重绘问题

### ISSUE THREAD

**Issue by litliang-cn** [HandyOrg/HandyControl#191]
在MVVM开发中，如果TabItem的Header与ViewModel的属性绑定，当ViewModel属性值改变时，TabItem显示的Header不会刷新。（如果属性值变化前后的长度一致（比如都是2个字），能正常刷新，但长度不一致时，不会正常刷新）。

**Comment by ghost1372** [comment]
hi @litliang-cn  Can you give a picture of this problem? Or send a sample project?
