### ISSUE TITLE
建议: 在demo程序中能同时显示对应的*.cs 和 *.xaml. 

### ISSUE THREAD

**Issue by ghost** [HandyOrg/HandyControl#192]
这样就不用跑到源代码里面翻半天了.

**Comment by ghost1372** [comment]
@qq405165798
@NaBian 

there is a library that can help us
https://github.com/Keboo/ShowMeTheXAML

![Untitled](https://user-images.githubusercontent.com/9213496/70032340-86586480-15c2-11ea-8b15-8ca392d266d6.png)

**Comment by NaBian** [comment]
I've thought about it, but I'm not going to use it. it's too complex.
