### ISSUE TITLE
“Window”TargetType 与元素“WindowInstance”的类型不匹配。	

### ISSUE THREAD

**Issue by ghost** [HandyOrg/HandyControl#193]
用VSIX packages for Visual Studio for 2019 生成的 dotnet 4.7工程一开始就报错.
不是警告,是错误! 但程序能编译过能跑.

错误		“Window”TargetType 与元素“WindowInstance”的类型不匹配。	HandyControlProject7	MainWindow.xaml	10		
错误就在 Style="{StaticResource WindowWin10}"

vs2019  v16.3.4
.net 4.7
handycontrol 2.1

![图片](https://user-images.githubusercontent.com/5558351/66799354-4de1c600-ef43-11e9-87cd-dbafab9dd837.png)

**Comment by cyoann** [comment]
Your MainWindow should not be a Window from System.Windows but from Handy Control, as you can see here:

 https://github.com/HandyOrg/HandyControl/blob/42f17c4626e9c600d58a20c8c5dc251f9af5381b/src/Net_GE45/HandyControl_Net_GE45/Themes/Styles/Window.xaml#L59



Implement it like this 
```xml
﻿<hc:Window x:Class="App.MainWindow"
           xmlns:hc="https://handyorg.github.io/handycontrol"
           Style="{StaticResource WindowWin10}"/>

```

**Comment by NaBian** [comment]
无视该问题即可，xaml设计器问题

**Comment by walterlv** [comment]
[WPF 判断一个对象是否是设计时的窗口类型，而不是运行时的窗口 - walterlv](https://blog.walterlv.com/post/check-dependency-object-is-a-design-time-window.html)
