### ISSUE TITLE
Why not English?

### ISSUE THREAD

**Issue by avestura** [HandyOrg/HandyControl#2]
Is it possible to change the language of this repo to English? At least for codes and package? These are a great set of control libraries and it will be really helpful if it could be used worldwide, not just for a specific region.

**Comment by NaBian** [comment]
good idea, i will add localization package in a future version.

**Comment by NaBian** [comment]
Hello, the control library has been localized and the README file will be updated later

**Comment by keytrap-x86** [comment]
Hi, some controls are still in chinese. I have made a project with your visual studios extension, then added a simple DateTimePicker. When I open it, some part of the date is in chinese. How do I fix this?

![image](https://user-images.githubusercontent.com/17864005/63129394-b51ce180-bfb7-11e9-8138-bcc0551c3276.png)

**Comment by ghost1372** [comment]
@BadNiiw  hi you can set language like this
`ConfigHelper.Instance.SetLang("en");`

**Comment by keytrap-x86** [comment]
> @BadNiiw hi you can set language like this
> `ConfigHelper.Instance.SetLang("en");`

Oh, thanks ! You should put it the Wiki ;)
By the way thanks for your work with the Wiki, it's very helpful.

**Comment by ghost1372** [comment]
@BadNiiw  Yes, I will put it on the wiki
you're welcome 😉

**Comment by NaBian** [comment]
here are some brief introductions [Globalization](https://ghost1372.github.io/handycontrol/langs/)
