### ISSUE TITLE
Hamburger Menu UI 

### ISSUE THREAD

**Issue by AdarshRise** [HandyOrg/HandyControl#200]
**Is your feature request related to a problem? Please describe.**

Hamburger menu is a very popular UI feature of mobile phones, and I want to replicate that feel on desktop as well. 

**Describe the solution you'd like**

The Side menu is great, but if it could behave like "slide in and out of screen", that would be enough.{ or maybe few things extra{e.g glass design } to make it more befitting of title}

**Describe alternatives you've considered**

I Tried forcefully make one, I might succeed as well, but this got me thinking if such window could be directly become a part of Handy Control Project.

**Additional context**

Here are three images for the same

![image](https://user-images.githubusercontent.com/31347367/67848489-ca22fe80-fb2a-11e9-8364-16e53e542d47.png)

![image](https://user-images.githubusercontent.com/31347367/67848525-ddce6500-fb2a-11e9-8a8f-89a07f2bcef4.png)

![image](https://user-images.githubusercontent.com/31347367/67848546-e7f06380-fb2a-11e9-8648-aba7a92f68b0.png)

**Comment by metheofanis** [comment]
Same as issue #182

**Comment by NaBian** [comment]
duplicate if #182
