### ISSUE TITLE
hc:TabItem Header绑定内容不刷新

### ISSUE THREAD

**Issue by AFei19911012** [HandyOrg/HandyControl#201]
**hc:TabItem Header绑定内容不刷新**
xaml代码：
hc:TabItem Header="{DynamicResource Res2}" 或者
hc:TabItem Header="{Bingding Res2}"；
这两种方式Header内容不会刷新；
TabItem Header="{DynamicResource Res2}"是可以的。

**Comment by NaBian** [comment]
Duplicate of #191
