### ISSUE TITLE
datagrid 的基础样式

### ISSUE THREAD

**Issue by 1111chance** [HandyOrg/HandyControl#214]
我想要自定义一个datagrid的样式，用于项目中所有的 datagrid 控件。
` <Style x:Key="DataGridStyle1" TargetType="DataGrid">
        <Setter Property="Width" Value="100"/>
    </Style>`

但是我自定义的样式丧失了 handycontrol 的所有特性。
我希望 handycontrol 提供一个基础的 datagrid 样式让我继承，那么我就可以这样写：
`<Style x:Key="DataGridStyle1" BasedOn="xxx" TargetType="DataGrid">
        <Setter Property="Width" Value="100"/>
    </Style>`

**Comment by NaBian** [comment]
https://handyorg.github.io/handycontrol/native_controls/

**Comment by 1111chance** [comment]
> https://handyorg.github.io/handycontrol/native_controls/

顿首
