### ISSUE TITLE
Badge 控件的改进建议

### ISSUE THREAD

**Issue by Luoyingliang** [HandyOrg/HandyControl#219]
Badge控件
我建议为Badge控件添加一个专门类型来封装内容，建议字段包括：
* Status        (用于保存当Badge应该显示的内容的状态)
* Content    （用于保存Badge应该显示的内容）
* Mode （用于保存Badge应该）

我的理由如下：Badge作为一个内容装饰器，我们不应该主要通过设置样式的方式来控制Badge控件的显示样式。而是应该通过内容来决定。当用户决定显示的内容为Danger的时候我们就应该设置为BadgeDanger，这样更利于数据绑定。

**Comment by NaBian** [comment]
不太明白你的“通过内容来决定”是什么意思
