### ISSUE TITLE
改进ButtonGroup，使得Badge能够添加到ButtonGroup里面

### ISSUE THREAD

**Issue by Luoyingliang** [HandyOrg/HandyControl#220]
改进ButtonGroup，使得Badge能够添加到ButtonGroup里面。
现有ButtonGroup只能添加基类为ButtonBase的元素，但是如果Button需要使用Badge时目前现有的策略将无法实现

**Comment by NaBian** [comment]
Badge添加到ButtonGroup中，仔细想了想觉得不合适。
首先，完全可以为ButtonGroup这个容器自身添加Badge，
其次，保不齐以后还会有除了Badge以外也适合放入ButtonGroup中的控件，
如此的话，情况就复杂了，索性就不做了。
