### ISSUE TITLE
TimeBar 无法绑定时间的需求

### ISSUE THREAD

**Issue by pfjgeng** [HandyOrg/HandyControl#224]
TimeBar 有三个需求

1. 第一 目前TimeBar 不能绑定时间
2. 第二 鼠标选中的时候，红线移动到选中的时刻
3. 第三 希望加上时间范围功能

**Comment by NaBian** [comment]
可以的话，希望将2、3两点单独提出来作为一个需求类的issue发布。

**Comment by pfjgeng** [comment]
好的，我分别提交一下

**Comment by pfjgeng** [comment]
另外提交issue
