### ISSUE TITLE
Support netcoreapp3.0

### ISSUE THREAD

**Issue by vchirikov** [HandyOrg/HandyControl#23]
Hello, I think it's time to add netcoreapp3.0 to `TargetFrameworks` :)

**Comment by NaBian** [comment]
@vchirikov  I think we should wait until vs2019 is officially released 🤔

**Comment by ghost1372** [comment]
@vchirikov  i tested it before when net core 3 preview 1 released and handycontrol is compatible with net core 3, you can check your code by microsoft tool
https://docs.microsoft.com/en-us/dotnet/core/porting/
https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer

**Comment by vchirikov** [comment]
I mean publish netcoreapp build at nuget.
