### ISSUE TITLE
Any Milestone?

### ISSUE THREAD

**Issue by AdarshRise** [HandyOrg/HandyControl#231]
Was thinking if there would be  any milestone for this project?

**Comment by NaBian** [comment]
no plan is the best plan

**Comment by AdarshRise** [comment]
True.

**Comment by AdarshRise** [comment]
Though #225  seems to be a good Goal? right?

**Comment by NaBian** [comment]
NavigationView is similar to SideMenu in my opinion.

**Comment by AdarshRise** [comment]
oh, lol, I wanted to say this 
![image](https://user-images.githubusercontent.com/31347367/69162340-82ccd400-0b12-11ea-98b5-d704ef8ac1eb.png)

a window that quickly explain how to create that control using "hc:xaml", in your Demo of handy tools{ will save a lot of time in going through all docs }.

**Comment by NaBian** [comment]
well, it could be Duplicate of #192

**Comment by AdarshRise** [comment]
Can't Read Mandarin yet 😅
