### ISSUE TITLE
outlineText doesn't show up in desinger

### ISSUE THREAD

**Issue by AdarshRise** [HandyOrg/HandyControl#233]
**Describe the bug**

OutlineText doesn't show-up in Designer at the time of view, but is visible at run-time.

**To Reproduce**

![image](https://user-images.githubusercontent.com/31347367/69074540-95350800-0a55-11ea-8a5d-22a4c36942bf.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/31347367/69074341-2f488080-0a55-11ea-9d12-37fabbe00db7.png)

**Screenshots**

**Environment (please complete the following information):**

 - .net: [ 4.7.1]
 - IDE [vs2019]
 - Version [2.2.0]
vsix

**Additional context**

I think this Outline is a run-time thing, hence it doesn't show up at design time, but can any changes be done for this?

thanks

**Comment by NaBian** [comment]
it should be the designer's problem, it's normal on my computer:
![demo](https://user-images.githubusercontent.com/17383395/69160946-540c2900-0b25-11ea-9eb5-8d63b9a1554c.jpg)

**Comment by AdarshRise** [comment]
alright. How to use? custom
Messagebox? could you explain pls?

**Comment by NaBian** [comment]
Why do you mention the Messagebox?

**Comment by AdarshRise** [comment]
I am struggling to use the Handy Tools, docs are not so clear. Well I think I should ask these questions in chat forums than on github.
