### ISSUE TITLE
ListBox with many items - Scrollbar too small

### ISSUE THREAD

**Issue by Swiftpaws** [HandyOrg/HandyControl#238]
**Describe the bug**
If a ListBox contains a lot of entries (1000+) the scrollbar becomes too small to use

**To Reproduce**
1. Create ListBox
2. Add 5000 entries
3. Try to scroll 

**Expected behavior**
The vertical scrollbar should have a fixed **minimum height**

**Comment by NaBian** [comment]
You can use the following codes to specify the minimum height or width:
``` xml
<ListBox.Resources>
    <system:Double x:Key="{x:Static SystemParameters.VerticalScrollBarButtonHeightKey}">40</system:Double>
</ListBox.Resources>
```
