### ISSUE TITLE
TabControl Bug

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#241]
`                <hc:TabControl ShowCloseButton="True" IsDraggable="True" ShowOverflowButton="True" ShowScrollButton="True" IsScrollable="True" IsEnableAnimation="True" ItemsSource="{Binding DataList}" Width="800" Height="300">
`
![3](https://user-images.githubusercontent.com/9213496/69747002-c484fc80-115a-11ea-899e-8fb1656b6037.gif)

**Comment by NaBian** [comment]
Can you show the complete xaml codes?
