### ISSUE TITLE
Hide Badge

### ISSUE THREAD

**Issue by Symbai** [HandyOrg/HandyControl#247]
How can I hide the badge without hiding its children?

**Comment by NaBian** [comment]
I don't seem to have taken this into account. 😞

**Comment by Symbai** [comment]
Thanks for your reply. I was using the "new reply" badge (https://github.com/HandyOrg/HandyControl/blob/86b634e85c311addbf875a3a3ac38db571661567/src/Shared/HandyControlDemo_Shared/UserControl/Controls/BadgeDemoCtl.xaml#L25) on a button and wanted to hide that badge only when a user clicks on the button. It would be great if you can add a way to hide the badge without hiding the button too. Preferably with binding support.
