### ISSUE TITLE
2.3.0升级后SideMenuItem动态添加出错（2.2.0没问题）

### ISSUE THREAD

**Issue by 5653325** [HandyOrg/HandyControl#249]
`var tabItem = new TabItem
                {
                    Header = TitleStr[1],
                    Name= tabItemName,
                    IsSelected = true
                };`
在2.3.0下报错
![image](https://user-images.githubusercontent.com/3361135/69925452-378bcb80-14eb-11ea-8ccb-7c1e3f60b5e5.png)

**Comment by NaBian** [comment]
到底是SideMenuItem还是TabItem。

**Comment by 5653325** [comment]
using TabItem = HandyControl.Controls.TabItem;
不好意思，描述错误，是TabControl后台动态添加TabItem在2.3.0下报错了
