### ISSUE TITLE
关于Password密码的绑定

### ISSUE THREAD

**Issue by GuangZhouDekang** [HandyOrg/HandyControl#251]
使用password控件时，如果在mvvm中绑定密码？

**Comment by NaBian** [comment]
不支持，也不推荐绑定密码

**Comment by wuqihui** [comment]
`
        /// <summary>
        /// 控件输入发生变化时更改属性的值
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private static void PasswordChanged(object sender, RoutedEventArgs e)
        {
            var pwd = sender as PasswordBox;
            SetPassword(pwd, pwd.Password);
        }

        //这个附加属性的目的是初始化一个控件输入变化事件，来监听控件的输入
        public static bool GetAttach(DependencyObject obj)
        {
            return (bool)obj.GetValue(AttachProperty);
        }

        public static void SetAttach(DependencyObject obj, bool value)
        {
            obj.SetValue(AttachProperty, value);
        }

        public static readonly DependencyProperty AttachProperty =
            DependencyProperty.RegisterAttached("Attach", typeof(bool), typeof(PassWordExtensions), new PropertyMetadata(false, new PropertyChangedCallback(OnAttach)));

        private static void OnAttach(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var pwd = d as  HandyControl.Controls.PasswordBox;
            var b = (bool)e.NewValue;
            if (b)
            {
                pwd.ActualPasswordBox.PasswordChanged += PasswordChanged;
            }
            else
            {
                pwd.ActualPasswordBox.PasswordChanged -= PasswordChanged;
            }

        }`

我希望通过这种方式来绑定密码，但是进入OnAttach的时候，ActualPasswordBox为null，我应该如何做呢？

**Comment by NaBian** [comment]
已经支持绑定了，不需要使用附加属性。

**Comment by NaBian** [comment]
> ` ///
> 
> 
> /// 控件输入发生变化时更改属性的值
> ///
> 
> ///
> ///
> private static void PasswordChanged(object sender, RoutedEventArgs e)
> {
> var pwd = sender as PasswordBox;
> SetPassword(pwd, pwd.Password);
> }
> ```
>     //这个附加属性的目的是初始化一个控件输入变化事件，来监听控件的输入
>     public static bool GetAttach(DependencyObject obj)
>     {
>         return (bool)obj.GetValue(AttachProperty);
>     }
> 
>     public static void SetAttach(DependencyObject obj, bool value)
>     {
>         obj.SetValue(AttachProperty, value);
>     }
> 
>     public static readonly DependencyProperty AttachProperty =
>         DependencyProperty.RegisterAttached("Attach", typeof(bool), typeof(PassWordExtensions), new PropertyMetadata(false, new PropertyChangedCallback(OnAttach)));
> 
>     private static void OnAttach(DependencyObject d, DependencyPropertyChangedEventArgs e)
>     {
>         var pwd = d as  HandyControl.Controls.PasswordBox;
>         var b = (bool)e.NewValue;
>         if (b)
>         {
>             pwd.ActualPasswordBox.PasswordChanged += PasswordChanged;
>         }
>         else
>         {
>             pwd.ActualPasswordBox.PasswordChanged -= PasswordChanged;
>         }
> 
>     }`
> ```
> 
> 我希望通过这种方式来绑定密码，但是进入OnAttach的时候，ActualPasswordBox为null，我应该如何做呢？

已经支持绑定了，不需要使用附加属性。

**Comment by wuqihui** [comment]
> 

请问如何绑定？

**Comment by wuqihui** [comment]
不能在“PasswordBox”类型的“Password”属性上设置“Binding”。只能在 DependencyObject 的 DependencyProperty 上设置“Binding”。”

**Comment by NaBian** [comment]
> 不能在“PasswordBox”类型的“Password”属性上设置“Binding”。只能在 DependencyObject 的 DependencyProperty 上设置“Binding”。”

请参考 demo。

**Comment by hongyanfengzi** [comment]
> > 不能在“PasswordBox”类型的“Password”属性上设置“Binding”。只能在 DependencyObject 的 DependencyProperty 上设置“Binding”。”
> 
> 请参考 demo。
demo 中并没有找到相关绑定方式, 能说一下怎么绑定的吗?

**Comment by boogaloo-jw** [comment]
新版本的PasswordBox可以这样绑定：使用UnsafePassword属性进行Bind，并指定IsSafeEnabled="False"

**Comment by boogaloo-jw** [comment]
> > > 不能在“PasswordBox”类型的“Password”属性上设置“Binding”。只能在 DependencyObject 的 DependencyProperty 上设置“Binding”。”
> > 
> > 
> > 请参考 demo。
> > demo 中并没有找到相关绑定方式, 能说一下怎么绑定的吗?

新版本的PasswordBox可以这样绑定：使用UnsafePassword属性进行Bind，并指定IsSafeEnabled="False"

**Comment by tenglongwentian** [comment]
ShowPassword为true的时候，maxlength无效
