### ISSUE TITLE
DataGrid Horizontal Scrolling Bug (?)

### ISSUE THREAD

**Issue by metheofanis** [HandyOrg/HandyControl#259]
Looks like a minor bug:
I have a DataGrid with many columns. So i need to horizontally scroll to see all data.
While scrolling i get in the output window : 

`System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property. Double:'-0.028838485341793785' BindingExpression:Path=CellsPanelHorizontalOffset; DataItem='DataGrid' (Name=''); target element is 'Button' (Name=''); target property is 'Width' (type 'Double')`

Also the scrolling is not smooth as expected.

The problem looks to be on "AllGeometry" Button (DataGrid.xaml). Changing the binding on Width property to let's say "50", works as expected.

Thanks.

**Comment by NaBian** [comment]
@ghost1372 Can you reproduce the problem?

**Comment by ghost1372** [comment]
hi @NaBian  I tried,  the Datagrid seems to have a problem
The following image is taken along with the following settings as you can see that although the width of the items is specified But the items are stuck together

`HorizontalScrollBarVisibility="Visible"`
`RowHeaderWidth="130"`
 `<DataGridTextColumn Width="100"`

![1](https://user-images.githubusercontent.com/9213496/70851540-a5e96a00-1eab-11ea-8b37-b0b0515c2be3.png)

Also, when we do not specify the width, even with the scroll bar, some items cannot be displayed
In the specified section we should have checkbox and the Combobox which is not

![2](https://user-images.githubusercontent.com/9213496/70851612-55264100-1eac-11ea-80c6-47e114bc6b2a.png)

Let me also say that scrolling with 20 rows and 50 or 30 columns is slow and laggy And the other problem that exists is that you have to wait for the data to load so that the scroll bar appears

I know that 30 columns is not rational, but Should be considered

another bug is when you set width=50 with 40 columns you get this

![3](https://user-images.githubusercontent.com/9213496/70851929-e8617580-1eb0-11ea-95c8-ca0eb323da4d.png)
 

you can test with this code in HandyControlDemo ----> DatagridDemoCtl

`                <DataGrid HorizontalScrollBarVisibility="Visible" HeadersVisibility="All" RowHeaderWidth="130" AutoGenerateColumns="False" ItemsSource="{Binding DataList}">
                    <DataGrid.RowHeaderTemplate>
                        <DataTemplate>
                            <CheckBox IsChecked="{Binding IsSelected,RelativeSource={RelativeSource AncestorType=DataGridRow}}"/>
                        </DataTemplate>
                    </DataGrid.RowHeaderTemplate>
                    <DataGrid.Columns>
                        <DataGridTextColumn IsReadOnly="True" Width="80" CanUserResize="False" Binding="{Binding Index}" Header="{x:Static langs:Lang.Index}"/>
                        <DataGridTemplateColumn Width="60" CanUserResize="False">
                            <DataGridTemplateColumn.CellTemplate>
                                <DataTemplate>
                                    <Image Source="{Binding ImgPath}" Width="32" Height="32" Stretch="Uniform"/>
                                </DataTemplate>
                            </DataGridTemplateColumn.CellTemplate>
                        </DataGridTemplateColumn>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridTextColumn Binding="{Binding Name}" Header="{x:Static langs:Lang.Name}"/>
                        <DataGridCheckBoxColumn Width="100" CanUserResize="False" Binding="{Binding IsSelected}" Header="{x:Static langs:Lang.Selected}"/>
                        <DataGridComboBoxColumn ItemsSource="{Binding Source={StaticResource DemoTypes}}" Width="100" CanUserResize="False" SelectedValueBinding="{Binding Type}" Header="{x:Static langs:Lang.Type}"/>
                        <DataGridTextColumn Width="1*" Binding="{Binding Remark}" Header="{x:Static langs:Lang.Remark}"/>
                    </DataGrid.Columns>
                </DataGrid>
`

**Comment by ghost1372** [comment]
hi @metheofanis i didnt see this error 
`
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property. Double:'-0.028838485341793785' BindingExpression:Path=CellsPanelHorizontalOffset; DataItem='DataGrid' (Name=''); target element is 'Button' (Name=''); target property is 'Width' (type 'Double')
`
Can you provide more information? (Number of columns and their width)
An example project can be great if possible

**Comment by metheofanis** [comment]
Hi @ghost1372 ,
It looks like I get the error in any number of columns/rows! I had 21 columns. I removed all and kept only two.
I resized the window to make it very small, so that horizontal scrolling was required. I got that problem. I've changed the width from auto to fix 50 or 100. Same problem.
I had more than 4000 rows. I changed it to get only 10 rows, the same problem.
As I told before: The problem looks to be on "AllGeometry" Button (DataGrid.xaml). Changing the binding on Width property to let's say "50", works as expected. Kindly note: I change this in HandyControl's DataGrid.xaml , not mine!
I'll try to make a small project to show this soon.
Regards. :)

**Comment by NaBian** [comment]
remove this:
![test](https://user-images.githubusercontent.com/17383395/70864535-e4efec00-1f8d-11ea-8e4f-f83094f2c3cc.png)

**Comment by ghost1372** [comment]
@NaBian  tnx problem fixed 😁 The only problem now is that scrolling is not smooth And if there are more records, And using the SelectAllButton takes a long time for all records to be selected

@metheofanis   I tested with 4,000 records and more than 40 columns with a width of 100 and didn't get the error you said

![2](https://user-images.githubusercontent.com/9213496/70864933-dd6c1b00-1f6c-11ea-988a-5e0fad00f2a2.gif)

**Comment by metheofanis** [comment]
I got it!
I had no: RowHeaderWidth="60"
After adding it, the problem has gone. Maybe if you remove it, you could see what I mean.
I'll investigate more tomorrow!
Thank a lot!

**Comment by ghost1372** [comment]
@metheofanis  I removed but I didn't see any error again🤔

**Comment by metheofanis** [comment]
Here I'm trying to insert an animated gif. First time. Please excuse if not a success:
[Image Here](https://clarkb2gt-my.sharepoint.com/:i:/g/personal/lw990_19office_net/EafySDCc18dFphLMqAp86QsBsn_RrxL7fheJk8gG2KvZgw?e=ujyQV9)

**Comment by ghost1372** [comment]
@metheofanis  i think link is broken

**Comment by metheofanis** [comment]
What about this?
![Image](https://media.giphy.com/media/mBvomEq2Q0HKUj5OuC/source.gif)

**Comment by metheofanis** [comment]
Hello,
Here is a new test on a new project. 1 Column, 1 Row. The column MinWidth is set to a greater value than the window, just to show the scrollbar. Below the image is the project in a zipped format
 
![Image](https://media.giphy.com/media/UUgbuSrbL2cmNufo9Z/source.gif)


[HandyControlTest2.zip](https://github.com/HandyOrg/HandyControl/files/3966736/HandyControlTest2.zip)

**Comment by ghost1372** [comment]
@NaBian 
 @metheofanis 
if we specify the RowHeaderTemplate and specify the HeadersVisibility to All we will not get the error but if these two are not defined we will get an error

@metheofanis  for fixing problem you can put this code in datagrid
```
<DataGrid.RowHeaderTemplate>
                        <DataTemplate>
                            <CheckBox IsChecked="{Binding IsSelected,RelativeSource={RelativeSource AncestorType=DataGridRow}}"/>
                        </DataTemplate>
                    </DataGrid.RowHeaderTemplate>
```
Note:  HeadersVisibility="column" with  RowHeaderTemplate get errors but setting HeadersVisibility="All" fix problem
![2](https://user-images.githubusercontent.com/9213496/70902643-891b7680-2012-11ea-9e88-5cd2d84ffc99.gif)

**Comment by metheofanis** [comment]
Working!
Thanks a lot.👍
