### ISSUE TITLE
ShowBadge is true when the binding is false at start

### ISSUE THREAD

**Issue by Symbai** [HandyOrg/HandyControl#264]
**Describe the bug**
On application startup badge is shown although its binding is set to false.

**To Reproduce**
1. Add a boolean property which is FALSE to your viewmodel
`public bool ShowNotification {get; set;}`
2. Add a badge and bind it to it
```
<hc:Badge
                                Height="30"
                                ShowBadge="{Binding ShowNotification}"
                                Style="{DynamicResource BadgeDanger}"/>
```
3. Start your application, the badge shows up although it shouldn't.

**Expected behavior**
The badge should be hidden on application start as well, when the value its binding to is false.

**Environment (please complete the following information):**
 - .net: 3.1 Core
 - IDE vs2019

**Comment by NaBian** [comment]
there's nothing wrong with it. Maybe you put the ShowNotification property in the wrong place.
