### ISSUE TITLE
gifimage不能自动播放的问题

### ISSUE THREAD

**Issue by chineselzh** [HandyOrg/HandyControl#268]
首先感谢大大带来的如此优秀的控制，感谢！
在使用gifimage控制的时候，发现无论如何它都只能显示gif动画的第一帧，不能自动播放动画。不知道是怎么回事，也没找到控制的方法。我的代码如下：
**xaml文件：**
`<hc:GifImage x:Name="GifImageMain" Margin="32" />`
**cs文件：**
`GifImageMain.Uri = new Uri(@"D:\0.gif", UriKind.Absolute);`
另外测试了直接在xaml文件里写gif文件也一样只能显示第一帧。
请大大看一下这个是什么原因引起的，怎么解决这个问题呢，谢谢！
我用的是VS2019+.NET4.5

**Comment by NaBian** [comment]
你好，请使用如下代码：
GifImageMain.Uri = new Uri("pack://siteoforigin:,,,/D:/0.gif");
