### ISSUE TITLE
DataGridCellStyle problem in MultiDataTriggers at Condition:SelectionUnit 

### ISSUE THREAD

**Issue by metheofanis** [HandyOrg/HandyControl#273]
The exact error i get in output window is:

`System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1''. BindingExpression:Path=SelectionUnit; DataItem=null; target element is 'DataGridCell' (Name=''); target property is 'NoTarget' (type 'Object')`

I think that is not really related to HandyControl, but i thought i will report it. Maybe you could do some "Defensive Programming"

I found that is coming from DataGridCellStyle => <Style.Triggers> => MultiDataTrigger.

The problem is shown when i delete some rows from the datagrid.
The rows are deleted as expected, but i get a bunch of those errors in output window. For almost every Cell in Datagrid that is deleted.
It looks like the the DataGridRows are detached from the DataGrid, but are still "alive" in memory for some time. So the Binding in Triger fails and throws this errors because there is no `FindAncestor,AncestorType=DataGrid` in the MultiDataTriggers (4 of them).

Here is what i did, without success to remove the errors:
1) I have disabled virtualization by:  VirtualizingPanel.IsVirtualizing="False"
2) I have removed all data except 1 column and 2 rows.
3) Removed IsAsync=True from ItemsSource
4) Remove Database interaction. Give hard-coded values for test.

**To Reproduce**
I've spend 2 days without success to reproduce in a small project (shame to me).

I would suggest this:

Instead of binding to RelativeSource FindAncestor, bind to self, and use a converter to find the parent datagrid, and if any, return the SelectionUnit, else return null.
So Instead of:
`<Condition Binding="{Binding SelectionUnit,RelativeSource={RelativeSource FindAncestor,AncestorType=DataGrid}}" Value="XXXX"/>`

Do this:

`<Condition Binding="{Binding RelativeSource={RelativeSource Self},Converter={StaticResource ParentDataGridSelectionUnitConverter}}" Value="XXXX"/>`

And the Converter:

```
 public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value is DataGridCell _dataGridCell)
            {
                var parent = VisualTreeHelper.GetParent(_dataGridCell);
                while (parent != null && !(parent is DataGrid))
                {
                    parent = VisualTreeHelper.GetParent(parent);
                }
                if (parent is DataGrid dataGrid)
                {
                    return dataGrid.SelectionUnit;
                }
            }
            return null;
        }
```

**Screenshots**

![SelectionUnit](https://user-images.githubusercontent.com/20851608/71313186-ed3ca100-243d-11ea-8088-79dd9ec6f0b7.gif)

**Environment (please complete the following information):**
 - .net Core
 - vs2019]
 - Latest Version

**Comment by metheofanis** [comment]
I found a workaround!
Setting the DataGrid's SelectedIndex = -1 stops the MultiDataTrigers to fall into an exception.

**Comment by NaBian** [comment]
fantastic 😆

**Comment by GF-Huang** [comment]
Same issue when I replacing item of `DataGrid.ItemsSource`.

`
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1''. BindingExpression:Path=SelectionUnit; DataItem=null; target element is 'DataGridCell' (Name=''); target property is 'NoTarget' (type 'Object')
`
