### ISSUE TITLE
.Net Framework版本的Demo程序中的Controls/Badge显示异常

### ISSUE THREAD

**Issue by DingpingZhang** [HandyOrg/HandyControl#274]
如下图所示，在Core的版本中是正常的，而在Framework的版本中，则被Border截断：

![image](https://user-images.githubusercontent.com/8541016/71445483-2aae7080-2755-11ea-9fa1-ecc7a2c05fc8.png)

**Comment by NaBian** [comment]
可能和系统版本、系统配置或硬件环境有关，在我电脑是正常的

**Comment by DingpingZhang** [comment]
> 可能和系统版本、系统配置或硬件环境有关，在我电脑是正常的

我在台式机和笔记本上测试都是这样，系统都是`win10 1909`。

**Comment by ghost1372** [comment]
@DingpingZhang  change your scale and layout (windows display settings) to 125% or 100% Maybe it will solve the problem

**Comment by DingpingZhang** [comment]
> change your scale and layout (windows display settings) to 125% or 100% Maybe it will solve the problem

Thank you for your suggestion, but it does not work on my machine.

![image](https://user-images.githubusercontent.com/8541016/71447834-a9fc6e00-276e-11ea-9bfa-d7bba88c7720.png)

**Comment by DingpingZhang** [comment]
Hi all,

I found this issue related to the .NET version. I just retarget the .NET version of the Demo project to .NET46 (must > .NET452), and the issue will not be repeated.

**Comment by NaBian** [comment]
maybe a bug of wpf. anyway, we have to solve this problem.

**Comment by NaBian** [comment]
besides .NET version, it has to do with the system version, my windows version is 1903.
