### ISSUE TITLE
Provide a Demo App

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [HandyOrg/HandyControl#275]
Please provide a demo app so we can experiment what's possible and what component library have in a demo app.

**Comment by ghost1372** [comment]
@HamidRezaAshkiyan  سلام حمیدرضا جان منظورت از برنامه دمو چیه؟ همین الانش هم پروژه دمو تو سورس موجوده

**Comment by NaBian** [comment]
demo was provided from the beginning.

**Comment by HamidRezaAshkiyan** [comment]
I cant download them right now. Can you send me a direct link?

**Comment by HamidRezaAshkiyan** [comment]
Oh I found it. I didn't look carefully in source. sorry.

But I think it is good to have a separate app something like material in xaml demo app.

**Comment by ghost1372** [comment]
@HamidRezaAshkiyan  mybe this
https://github.com/AFei19911012/HandyControl
