### ISSUE TITLE
Foreground Color Problem

### ISSUE THREAD

**Issue by AdarshRise** [HandyOrg/HandyControl#281]
**Describe the bug**

** The Foreground Color Doesn't work with Textbox, but works with PasswordBox 

**To Reproduce**

** Use Foreground in both textbox and password box of {hc:} 

**Expected behavior**

** chose color appear in Password box but not in textbox

**Screenshots**

![image](https://user-images.githubusercontent.com/31347367/71557090-3c4e8b80-2a67-11ea-92f3-0cc836e21092.png)

The Xaml
![image](https://user-images.githubusercontent.com/31347367/71557096-55573c80-2a67-11ea-8f17-17a6a0d35d7b.png)

**Environment (please complete the following information):**
 - .net: [e.g. 4.6.2]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

 - .net: 4.7.2
 - IDE : VS19
 - Version: HC 2.3v

**Additional context**

**Comment by ghost1372** [comment]
@AdarshRise  fixed in https://github.com/HandyOrg/HandyControl/pull/282
You have to wait for Nabian to agree to the request Or you can make changes to the project yourself

**Comment by AdarshRise** [comment]
Thanks, will wait for a merge.
