### ISSUE TITLE
Outline Text problem with flow direction

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [HandyOrg/HandyControl#292]
**Describe the bug**
There is a bug in outline text box that when I use it with persian text (right to left text) it reverse it and I should use flow direction left to right to fix it. 

**Screenshots**
Following screenshot show two panel the upper panel is right to left and the panel beneath it is left to right and it works.
![image](https://user-images.githubusercontent.com/38791873/71819238-902d2600-30a0-11ea-8651-8785c4456036.png)

**Comment by ghost1372** [comment]
Hi, all texts have this problem. And it has nothing to do with language
@NaBian  Is this normal behavior?
![Untitled](https://user-images.githubusercontent.com/9213496/71986449-c2c25480-3241-11ea-8353-64f3f452c7ee.png)

**Comment by NaBian** [comment]
outlinetext is geometry in essence, its behavior can not be consistent with textblock, textbox and so on. so i close this issue.
