### ISSUE TITLE
Running TextBlock character show bug

### ISSUE THREAD

**Issue by hupo376787** [HandyOrg/HandyControl#293]
**Describe the bug**
When setting flow direction to `RightToLeft`, the last character becomes the first one.

**To Reproduce**
Steps to reproduce the behavior
Use code:
```
<hc:RunningBlock 
            Width="300"
            Height="100"
            Foreground="YellowGreen"
            BorderThickness="0"
            Content="今天天气好晴朗，处处好风光。"
            FlowDirection="RightToLeft"
            FontSize="32"
            FontWeight="Bold"
            IsRunning="True"/>
```
This result in:
![image](https://user-images.githubusercontent.com/14960168/72035411-c3ef9200-32d2-11ea-96e2-72851b75e44f.png)

But if I add a simple character "1" to the end like "今天天气好晴朗，处处好风光。1", it becomes normal.
![image](https://user-images.githubusercontent.com/14960168/72035512-1335c280-32d3-11ea-83e4-8b096d0b2c97.png)

So this bug maybe caused by the Chinese character "。"

**Environment (please complete the following information):**

vs2019 16.4.2

**Comment by NaBian** [comment]
It's not a bug, it's the native mechanism of textblock, you can try the following codes:
``` xml
<TextBlock Text="今天天气好晴朗，处处好风光。" FlowDirection="RightToLeft"/>
```

**Comment by hupo376787** [comment]
Wow, yes! This means I found a Microsoft's bug? LOL😂

**Comment by NaBian** [comment]
use TextAlignment="Right", if you just want words right alignment

**Comment by hupo376787** [comment]
No, just the charater "。", still not in the right place.

**Comment by hupo376787** [comment]
Closing now, thanks.
