### ISSUE TITLE
Can add Korean language in Handycontrol?

### ISSUE THREAD

**Issue by BareungakServer** [HandyOrg/HandyControl#296]
i translated (handycontrol, no demo) korean language (ko-KR), can u upload this?
[Lang.ko-KR.zip](https://github.com/HandyOrg/HandyControl/files/4038801/Lang.ko-KR.zip)

**Comment by NaBian** [comment]
@ghost1372 @BareungakServer You are working hard 😆

**Comment by ghost1372** [comment]
Oh sorry @NaBian I forgot to add to the demo😁 tnx
