### ISSUE TITLE
More controls and Dark Mode for controls themes

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#3]
hi first of all, tnx for  great and beautiful controls, if possible please add Dark and Light Themes for controls
also please add more controls like this:

Datagrid control
Textbox
PasswordBox
Label
Slider
Scrollbar
Listview
Listbox
Checkbox
Calendar
DateTime Picker
and more...

**Comment by NaBian** [comment]
These controls have been developed, and I'll take the time to open source one by one.The theme you said is a good idea, and I'll consider adding it in a future version.
