### ISSUE TITLE
NumericUpDown中，设置DecimalPlaces和Value的顺序会影响Value的值

### ISSUE THREAD

**Issue by DinoChan** [HandyOrg/HandyControl#313]
**Describe the bug**
NumericUpDown中，先Value再设置DecimalPlaces的话会执行`Math.Floor`忽略Value的小数位。

**To Reproduce**

``` XML
<hc:NumericUpDown DecimalPlaces="2"
                  Value="100.12345" />
<hc:NumericUpDown Value="100.12345"
                  DecimalPlaces="2" />
```

**Screenshots**

![图片](https://user-images.githubusercontent.com/6076257/72677112-c6709980-3ad3-11ea-857e-bc56e53029fa.png)

**建议**
我认为属性值的设置应该无关它们的顺序。应该时这句代码出了问题：

``` CS
result = Math.Floor(result);
```

**Environment (please complete the following information):**
 - .net: 4.5以上
 - IDE VS2019
 - Version 2.4

**Comment by ReverseLw** [comment]
谢谢您，编写 XAML 的顺序确实会影响其显示效果。
Thank you, the order in which you write xaml does affect the display
