### ISSUE TITLE
SideMenuItem Header text problem

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#317]
The text is not fully displayed and will change as the window opens and closes
![3](https://user-images.githubusercontent.com/9213496/72743573-2f820b00-3bc1-11ea-84b9-635358b77e30.gif)

**Comment by NaBian** [comment]
can you provide a demo?

**Comment by ghost1372** [comment]
@NaBian  https://github.com/ghost1372/ganjineh

**Comment by NaBian** [comment]
use command instead of selected event
