### ISSUE TITLE
Dialog Style

### ISSUE THREAD

**Issue by HackMemory** [HandyOrg/HandyControl#329]
Hi. How i can set Style property to Dialog?

**Comment by NaBian** [comment]
you can override DialogBaseStyle

**Comment by HackMemory** [comment]
like that?

`<Style x:Key="DialogBaseStyle" TargetType="{x:Type controls:Dialog}" BasedOn="{StaticResource DialogBaseStyle}">`

**Comment by NaBian** [comment]
yes
