### ISSUE TITLE
Excessive GPU usage with Badge status set to "Processing"

### ISSUE THREAD

**Issue by keytrap-x86** [HandyOrg/HandyControl#336]
**Describe the bug**
When I set the property Status of the Badge control to "Processing", my GPU goes crazy usage

**To Reproduce**
```XAML
<hc:Badge Status="Processing" Background="#FFFB0781"  >
     <TextBox Text="Test" />
</hc:Badge >
```

**Expected behavior**
Not as much GPU usage

**Screenshots**
![handy](https://user-images.githubusercontent.com/17864005/76405192-0e9b9200-6388-11ea-9af3-6b1cc48f6798.gif)

**Environment (please complete the following information):**
 - .net: [e.g. 4.5.1]
 - IDE [e.g. vs2019]
 - Version [e.g. 16.4.6]

**Additional context
On the Gif we see the GPU doing to 40%, but It can go up to **72**% !

**Comment by kumamiko** [comment]
I set the DesiredFrameRate Property at a lower value on the StoryBoard of BadgeProcessingTemplate.
GPU usage will be improved a lot，if you don't care the animation's smoothness too much.😗

**Comment by NaBian** [comment]
> I set the DesiredFrameRate Property at a lower value on the StoryBoard of BadgeProcessingTemplate.
> GPU usage will be improved a lot，if you don't care the animation's smoothness too much.😗

tnx

**Comment by keytrap-x86** [comment]
> I set the DesiredFrameRate Property at a lower value on the StoryBoard of BadgeProcessingTemplate.
> GPU usage will be improved a lot，if you don't care the animation's smoothness too much.😗

Thanks.
But sometimes I don’t understand WPF. When I play Call Of Duty it uses about 70% of my GPU. But with WPF animation you need only one little dot to use up to 70% lol
