### ISSUE TITLE
How can I do a graph similar to git clients?

### ISSUE THREAD

**Issue by helloitsm3** [HandyOrg/HandyControl#343]
![image](https://user-images.githubusercontent.com/13825491/77824426-89f99380-713d-11ea-9f92-48a763b14f33.png)
![image](https://user-images.githubusercontent.com/13825491/77824433-967dec00-713d-11ea-9184-a65232156a99.png)

**Comment by NaBian** [comment]
sorry, but this issue is not in touch with hc
