### ISSUE TITLE
Rate Control not update after Property Changed

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#345]
hi @NaBian  rate control not update after propertychanged but if we focus control with mouse, it can be update
![2020-03-31_15-05-10](https://user-images.githubusercontent.com/9213496/78017208-28b20a00-7361-11ea-80aa-75a787299359.gif)

**Comment by NaBian** [comment]
can you provide a simple demo? together with #346

**Comment by ghost1372** [comment]
@NaBian  please check this project

[HandyControlProject1.zip](https://github.com/HandyOrg/HandyControl/files/4410147/HandyControlProject1.zip)

**Comment by ghost1372** [comment]
@NaBian , @DinoChan  [commit ](https://github.com/DinoChan/HandyControl/commit/110ac1d36d68414fa0526f776dae2a3be6e25df2) fixed this issue (tnx bro👍)
