### ISSUE TITLE
I can't seem to use geometries even when I included it in the merged dictionaries

### ISSUE THREAD

**Issue by helloitsm3** [HandyOrg/HandyControl#351]
**Describe the bug**
Unable to use geometries even when the resource is included in the App.xaml
![image](https://user-images.githubusercontent.com/13825491/78330764-4d9fba80-75b7-11ea-83a1-a75d8a03fe20.png)

Error:
![image](https://user-images.githubusercontent.com/13825491/78330841-70ca6a00-75b7-11ea-8cd7-148c13f552c3.png)

**To Reproduce**
1. Go to App.xaml
2. Add ```<ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Basic/Basic.xaml"/>``` to merged dictionaries
3. Add ``` <Path Data="{StaticResource GithubGeometry}" />``` to UserControl.xaml

**Expected behavior**
A Github Geometry

**Screenshots**
![image](https://user-images.githubusercontent.com/13825491/78330764-4d9fba80-75b7-11ea-83a1-a75d8a03fe20.png)

![image](https://user-images.githubusercontent.com/13825491/78330841-70ca6a00-75b7-11ea-8cd7-148c13f552c3.png)

**Environment (please complete the following information):**
 - .net Core [3.1]
 - IDE [e.g. vs2019]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by codingdna2** [comment]
GithubGeometry is part of the Demo app and not included with the HandyControl dll. If you want to use it, you have to copy it from there...

**Comment by ghost1372** [comment]
@helloitsm3  you dont need to include `<ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Basic/Basic.xaml"/>` in app.xaml
As @codingdna2  said, this is part of the demo program and you need to add this geometry.

after `MergedDictionary` add this code
`    <Geometry x:Key="GithubGeometry">M512 0C229.12 0 0 229.12 0 512c0 226.56 146.56 417.92 350.08 485.76 25.6 4.48 35.2-10.88 35.2-24.32 0-12.16-0.64-52.48-0.64-95.36-128.64 23.68-161.92-31.36-172.16-60.16-5.76-14.72-30.72-60.16-52.48-72.32-17.92-9.6-43.52-33.28-0.64-33.92 40.32-0.64 69.12 37.12 78.72 52.48 46.08 77.44 119.68 55.68 149.12 42.24 4.48-33.28 17.92-55.68 32.64-68.48-113.92-12.8-232.96-56.96-232.96-252.8 0-55.68 19.84-101.76 52.48-137.6-5.12-12.8-23.04-65.28 5.12-135.68 0 0 42.88-13.44 140.8 52.48 40.96-11.52 84.48-17.28 128-17.28 43.52 0 87.04 5.76 128 17.28 97.92-66.56 140.8-52.48 140.8-52.48 28.16 70.4 10.24 122.88 5.12 135.68 32.64 35.84 52.48 81.28 52.48 137.6 0 196.48-119.68 240-233.6 252.8 18.56 16 34.56 46.72 34.56 94.72 0 68.48-0.64 123.52-0.64 140.8 0 13.44 9.6 29.44 35.2 24.32A512.832 512.832 0 0 0 1024 512c0-282.88-229.12-512-512-512z</Geometry>
`
