### ISSUE TITLE
TabControl/TabPanel Resize issue when using IsTabFillEnabled

### ISSUE THREAD

**Issue by codingdna2** [HandyOrg/HandyControl#352]
**Resize issue**
Here an image that describe the issue:
![TabPanelResizeIssue](https://user-images.githubusercontent.com/6033635/78377779-55b82400-75d0-11ea-8f5c-aaf1ab9a26fa.gif)

**To Reproduce**
The issue is asymptomatic. At program start is there. The attached project uses binding and ObservableCollection and after the collection change, the issue disappears.

[TabControlIssue.zip](https://github.com/HandyOrg/HandyControl/files/4428296/TabControlIssue.zip)

My TabControl is configured as following:
```
<hc:TabControl
    Grid.Column="1"
    HorizontalAlignment="Stretch"
    IsAnimationEnabled="True"
    IsDraggable="True"
    IsScrollable="True"
    ItemsSource="{Binding Documents}"
    ShowCloseButton="True"
    ShowOverflowButton="False"
    ShowScrollButton="True">
        <TabControl.ItemTemplate>
            <DataTemplate>
                <TextBlock Text="{Binding Header}" />
            </DataTemplate>
        </TabControl.ItemTemplate>
</hc:TabControl>
```

And the view model is as following:
```
public class Document
{
    public string Header { get; set; }
}

public class MainWindowViewModel
{
    private int counter;

    public MainWindowViewModel()
    {
        Documents = new ObservableCollection<Document>()
        {
            new Document() { Header = "Tab 1" },
            new Document() { Header = "Tab 2" },
        };

        counter = Documents.Count;

        AddCommand = new DelegateCommand(() => { Documents.Add(new Document() { Header = $"Tab {++counter}" }); });

        RemoveCommand = new DelegateCommand(() => { Documents.RemoveAt(0); });
    }

    public ICommand AddCommand { get; }

    public ICommand RemoveCommand { get; }

    public ObservableCollection<Document> Documents { get; }
}
```

**Environment (please complete the following information):**
 - .NET Core 3.1
 - IDE: VS 2019
 - Version 2.4.0

**Additional context**

I've added to TabControl.OnRenderSizeChanged the last 3 lines of code (see below). It works but I'm too new to the project and I'll appreciate your thoughts.
```
protected override void OnRenderSizeChanged(SizeChangedInfo sizeInfo)
{
    base.OnRenderSizeChanged(sizeInfo);
    UpdateOverflowButton();

    HeaderPanel.ForceUpdate = true;
    HeaderPanel.Measure(new Size(HeaderPanel.DesiredSize.Width, TabItemHeight));
    HeaderPanel.ForceUpdate = false;
}
```

**Comment by mircoso** [comment]
quick code check and this is missing ...
![image](https://user-images.githubusercontent.com/12988330/78462194-140ea280-76d0-11ea-8a7b-1dc3ea42f41e.png)
I hope to be help

**Comment by NaBian** [comment]
> quick code check and this is missing ...
> ![image](https://user-images.githubusercontent.com/12988330/78462194-140ea280-76d0-11ea-8a7b-1dc3ea42f41e.png)
> I hope to be help

tnx 😆
