### ISSUE TITLE
binding not work in RunningBlock

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#355]
hi @NaBian  binding not work in RunningBlock I tested the following

`<hc:RunningBlock Content="{Binding Status}"/>
`
```
 <hc:RunningBlock >
                <hc:RunningBlock.Content>
                    <TextBlock Text="{Binding Status}"/>
                </hc:RunningBlock.Content>
            </hc:RunningBlock>
```

```
<hc:RunningBlock>
                <ListBox ItemsSource="{Binding data}"/>
            </hc:RunningBlock>
```

**Comment by NaBian** [comment]
i can't reproduce, it‘s better to provide a demo.

**Comment by ghost1372** [comment]
@NaBian  please check attached project, After running the program, datagrid on the left side shows the information well, but on the right, the same datagrid is inside the running block and cannot display the information

[CoronaVirusPandemic.zip](https://github.com/HandyOrg/HandyControl/files/4438718/CoronaVirusPandemic.zip)

![op2](https://user-images.githubusercontent.com/9213496/78565720-8ea40300-7833-11ea-8fde-d483b08cffb7.gif)

**Comment by NaBian** [comment]
assign a fixed height for datagrid

**Comment by ghost1372** [comment]
@NaBian  tnx issue Fixed😁❤
