### ISSUE TITLE
TabControl ShowButtonOverflow Behavior

### ISSUE THREAD

**Issue by codingdna2** [HandyOrg/HandyControl#357]
**Describe the bug**
There are two things which I found strange. 
1. First the button overflow is shown before the space is filled. 

![image](https://user-images.githubusercontent.com/6033635/78508477-7ecee500-7787-11ea-9459-7bc6f78e914f.png)

This is due the `TabControl.UpdateOverflowButton` which uses a `>=` instead of `>` (changing it fix the behavior):
```c#
private void UpdateOverflowButton()
{
    if (!IsTabFillEnabled)
    {
        _itemShowCount = (int)(ActualWidth / TabItemWidth);
        _buttonOverflow?.Show(ShowOverflowButton && Items.Count > 0 && Items.Count >= _itemShowCount);
    }
}

```
2. Second, if you select an invisible tab using the menu which requires the scrollviewer to scroll, the tab is moved instead of simply being selected. 

![image](https://user-images.githubusercontent.com/6033635/78508796-eb4ae380-7789-11ea-80e4-acfb2e2b1fab.png)
![image](https://user-images.githubusercontent.com/6033635/78508814-0fa6c000-778a-11ea-98a2-15ba0e552fe7.png)

This is due the `_buttonOverflow.Click` event (TabControl.cs line 348):
```c#
if (index >= _itemShowCount)
{
    list.Remove(actualItem);
    list.Insert(0, actualItem);
    // REST OF CODE
```
I found this a strange behavior. I expect the tab to be selected, not to be moved. I've changed as following:
```c#
if (index >= _itemShowCount)
{
    _scrollViewerOverflow?.ScrollToHorizontalOffsetInternal((item.CurrentIndex - this.SelectedIndex) * TabItemWidth, 0);
    // REST OF CODE
```

The above in order to work requires an addition in TabControl.xaml (line 174) to enable the right style. 

**EDIT**: _I removed IsScrollable = True condition and included IsTabFillEnabled = false. I guess scrolling should be implicit if you don't use IsTabFilled._ 

```xaml
<MultiTrigger>
    <MultiTrigger.Conditions>
        <Condition Property="IsTabFillEnabled" Value="False" />
        <Condition Property="ShowOverflowButton" Value="True" />
    </MultiTrigger.Conditions>
    <Setter Property="Template" Value="{StaticResource TabControlPlusScrollableTemplate}" />
</MultiTrigger>
```

**Contributions**
I don't want to bother too much the author, I can prepare a PR if required. On the other end, I'm not that expert and I don't want to push modifications prior some confirmation.

Thanks for the great controls and thanks in advance for any support.
Regards

**Comment by NaBian** [comment]
part of tabcontrol behavior is copy from vs.  you can modify some codes to implement custom function or behavior.

**Comment by codingdna2** [comment]
I've been checking the VS behavior and is like I've described here (and it's also more complex). By the way, I would like to contribute and I'll do my best to provide you with a PR on this. I'll use this issue to keep track of modifications.

- [x] Button overflow is shown when Tabs space is full
- [x] Selection of a tab outside the visible area move the scrollbar
- [x] New tab when the tab area is full, should move the scrollbar
- [x] During resize, the active tab should be kept visible 

About VS behavior on (2): Visual Studio switch the order inside the context menu but not the order of the tabs. In fact the context menu is bound to the **navigation order** while the UI only keep the position. As HandyControl doesn't handle the navigation order, I guess the correct behavior is the suggested one. This feature (navigation order) can be a future enhancement.

**Comment by codingdna2** [comment]
Done! Let me know what you think.
Kind Regards,
D.
