### ISSUE TITLE
TabControl theme issue

### ISSUE THREAD

**Issue by codingdna2** [HandyOrg/HandyControl#358]
**Describe the issue**
The Background color of TabControl should be SecondaryRegionBrush

![image](https://user-images.githubusercontent.com/6033635/78547048-b75dd580-77fe-11ea-9a9d-49f933684b45.png)

**Comment by mircoso** [comment]
1. change on basic control
![image](https://user-images.githubusercontent.com/12988330/78598971-8e663080-7850-11ea-96e0-838044eb7f12.png)

or

2. change on the tabcontrol in the window
![image](https://user-images.githubusercontent.com/12988330/78599241-177d6780-7851-11ea-902e-7aa6b5c12b76.png)

or

3. definition of the style
![image](https://user-images.githubusercontent.com/12988330/78599724-ef423880-7851-11ea-9c65-95ceb0338f42.png)


I hope I have helped you
