### ISSUE TITLE
上下文菜单（代码仓库、关于等那些）无法点击出菜单

### ISSUE THREAD

**Issue by zhongwcool** [HandyOrg/HandyControl#359]
**Describe the bug**
当将target framework设定为4.8的时候，上下文菜单（代码仓库、关于等那些）无法点击出菜单

**To Reproduce**
1. 右键属性将target framework设定为4.8
2. 点击上下文菜单

**Expected behavior**
正常弹出菜单并点击有响应

**Screenshots**
![](https://i.loli.net/2020/04/07/a6QzT3gWGCoiYtr.png)

**Environment (please complete the following information):**
 - IDE vs2019 Community or Rider 2019.3
 - Version 2.4.0 and 最新

**Additional context**
None.

**Comment by zhongwcool** [comment]
Screenshots
![](https://sm.ms/image/a6QzT3gWGCoiYtr)

**Comment by zhongwcool** [comment]
Screenshots
![](https://i.loli.net/2020/04/07/a6QzT3gWGCoiYtr.png)

**Comment by NaBian** [comment]
无法复现该问题，可以提供复现demo
