### ISSUE TITLE
Simplify ResourceDictionary

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#361]
In one of the controls, I saw that this is how they wrote their dictionaries
```
<Application
    ...
    xmlns:ui="http://schemas.modernwpf.com/2019">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemeResources />
                <ui:XamlControlsResources />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

This is very good and simple, It would be great if the HandyControl also supported it something like this:
```
<hc:Controls/>
<hc:Theme Skin="Light"/>
```

**Comment by NaBian** [comment]
if we use simple ResourceDictionary, we will lost Intelligent! that's too bad, we must resolve it.

**Comment by ghost1372** [comment]
@NaBian  Take a look at this project https://github.com/Kinnara/ModernWpf
I think this project has a solution 
It seems, the problem has been solved through the design time file
https://github.com/Kinnara/ModernWpf/tree/master/ModernWpf/DesignTime
https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf.Controls/Properties/DesignTimeResources.xaml

**Comment by ghost1372** [comment]
Hi @NaBian  
Thank you about https://github.com/HandyOrg/HandyControl/commit/f835f25165ff09b10f47744d45952b6f3963c4df
Performance has been great
By putting all the resources in one file (Theme.xaml) I think this issue has been solved right?

**Comment by NaBian** [comment]
no, I wonder that although there can be a simple way to app.xaml, while we must add a designtimeresources.xaml file in properties folder, is there any essential difference?

**Comment by ghost1372** [comment]
The reason for adding Design Time is that styles, brushes, etc. can be easily identified
Unfortunately, Visual Studio can not properly detect Resources
I installed different versions of Visual Studio and I have this problem every time.
I'm surprised that this problem does not happen to you
![1](https://user-images.githubusercontent.com/9213496/101043172-43451e80-3593-11eb-930c-329ebf4e9ad9.png)
![2](https://user-images.githubusercontent.com/9213496/101043180-450ee200-3593-11eb-9b68-a68dcf1639c1.png)

**Comment by NaBian** [comment]
I think I've found a solution, wait a second.

**Comment by NaBian** [comment]
I have failed 😭

**Comment by ghost1372** [comment]
oh 😔
What do you think about Design Time?

**Comment by ghost1372** [comment]
@NaBian Check my PR to see if the problem is resolved?
This implementation allows us to use several different themes at the same time
I put the classes in a folder called Theme
In this way, the program can be launched
```
<hc:ThemeResources RequestedTheme="Dark"/>
  <hc:XamlControlsResources/>
```
DO-NOT-MERGE this PR for now
I have not yet been able to implement the possibility of multiple themes  at the same time. I think it needs a little change in the static and dynamic structure of the resources.
Just check to see if the Intelligent problem has improved or not. in My system is much better than your PR.

**Comment by ghost1372** [comment]
I came up with some interesting results
If there is no problem, [this ](https://github.com/HandyOrg/HandyControl/issues/500) feature will be added and simplified dictionary will be get improveme😁
