### ISSUE TITLE
HandyControl.Controls.Window”的类型初始值设定项引发异常

### ISSUE THREAD

**Issue by Echolh** [HandyOrg/HandyControl#364]
**Describe the bug**
调用MessageBox.Show时有时会引发此异常.
如：
HandyControl.Controls.MessageBox.Show("添加成功", "提示", MessageBoxButton.OK, MessageBoxImage.Information) 

HandyControl.Controls.Window”的类型初始值设定项引发异常
内部错误：
XamlParseException: Baml 流中出现意外记录。尝试添加到不是集合或具有 TypeConverter 的 Setter

 NuGet版本： HandyControl  2.4.0
 IDE: vs2019
 WPF开发
 .net:软件环境 .net 4.5.2

**Comment by ghost1372** [comment]
@Echolh  Can you attach an example project?
I couldn't reproduce your problem and project Run without error I tested 50 times

**Comment by NaBian** [comment]
请提供最小复现demo

**Comment by DineshSolanki** [comment]
System.TypeInitializationException: 'The type initializer for 'HandyControl.Controls.Window' threw an exception.'
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

Please help, it happens sometimes and randomly. 

![image](https://user-images.githubusercontent.com/15937452/87802219-79953200-c86e-11ea-8dbc-034340c1ee4a.png)

**Comment by GF-Huang** [comment]
Similar issue, https://github.com/HandyOrg/HandyControl/discussions/821
