### ISSUE TITLE
麻烦帮忙看看为什么项目获取下来就报一堆错

### ISSUE THREAD

**Issue by Zoranner** [HandyOrg/HandyControl#365]
![20200416175256](https://user-images.githubusercontent.com/20719726/79442849-a9ccfa80-800b-11ea-810c-bd3ab46beb4d.png)

环境都有，项目获取下来什么都没动就报错。
找了好久没发现问题，可以帮忙看看可能是哪里出了问题么？谢谢。

**Comment by ghost1372** [comment]
Mostly because of Visual Studio and the inability of the xaml designer
Ignore it and try to rebuild project

**Comment by NaBian** [comment]
1、确定ide是否是vs2019；
2、确定是否安装了core30、core31、net48、net47；
3、确定启动项目和解决方案配置是否配对正确；

**Comment by Zoranner** [comment]
> 1、确定ide是否是vs2019；
> 2、确定是否安装了core30、core31、net48、net47；
> 3、确定启动项目和解决方案配置是否配对正确；

以上条件经过确认都满足，但是还是报这些错😫
