### ISSUE TITLE
Please, add 'ru' localization

### ISSUE THREAD

**Issue by youshida-sama** [HandyOrg/HandyControl#369]
Hello!
You can add Russian localization?
I can send for you edited file with translated messages.

There is ResX file: [Lang.ru.resx.txt](https://github.com/HandyOrg/HandyControl/files/4509125/Lang.ru.resx.txt)
Rename to 'Lang.ru.resx'.

Thank you in advance!

**Comment by ghost1372** [comment]
@Youshida-sama  i created a PR https://github.com/HandyOrg/HandyControl/pull/370
