### ISSUE TITLE
希望可以将Demo改为独立工程（类似基于SDK开发的Demo），对新手太不友好了

### ISSUE THREAD

**Issue by zhongwcool** [HandyOrg/HandyControl#371]
想要提取比如更换主题的功能，结果嵌套太深，不知道哪些是该抽取的资源 😔

**Comment by NaBian** [comment]
工程量太大，个人无力改动，[这里](https://github.com/AFei19911012/HandyControl)有一些例子，可供参考。

**Comment by zhongwcool** [comment]
感谢回复。
