### ISSUE TITLE
Resource Error

### ISSUE THREAD

**Issue by youshida-sama** [HandyOrg/HandyControl#374]
Resource bug when adding ListBox with ModernStyle.
Working good, but Preview in VS don't work.
This errors appeared after today's update.

![BugScreen](https://user-images.githubusercontent.com/35883698/80223711-52550d00-8651-11ea-8e46-549a291a92a2.png)

**Comment by ghost1372** [comment]
@Youshida-sama  this style is only available in [Custom ](https://github.com/ghost1372/handycontrols)version
Please pay attention to the [documentation](https://ghost1372.github.io/handycontrol/native_controls/listBox/#ListBoxModernStyle)

**Comment by youshida-sama** [comment]
Thanks
