### ISSUE TITLE
SetLang get NullRefrenceException in ctor

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#376]
if we use following code in ctor we get null refrence exception

```
 public App()
        {
            GlobalData.Init();
            ConfigHelper.Instance.SetLang(GlobalData.Config.Lang);
        }
```

also this code get null refrence exception too
```
 public App()
        {
ResourceHelper.GetTheme("HandyTheme", Resources).Skin = skin;
        }
```

**Comment by NaBian** [comment]
shouldn't have done this here. the right place is "protected override void OnStartup(StartupEventArgs e)"

**Comment by kababu2021** [comment]
@ghost1372 
What if i am having a WPF Window (triggered by a button click) from within an Microsoft word add-in. In this scenario, I am getting the same error as above (null reference). 

Where should the SetLang be at that point?
