### ISSUE TITLE
using LangProvider with Prism

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#377]
Hi, I want to use a LangProvider in my application with prism But binding doesn't work
`        <Label Content="{ex:Lang  Key={Binding hello}}"/>
`
and this is my property in viewmodel
```
private string _hello = "hello";
        public string hello
        {
            get { return _hello; }
            set { SetProperty(ref _hello, value); }
        }
```
I tried this too but it didn't work
`        <Label Content="{ex:Lang  Key={Binding DataContext.hello}}"/>
`
It works well without the use of prism

**Comment by NaBian** [comment]
ok, demo pls.

**Comment by ghost1372** [comment]
tnx
[HandyControlProject3.zip](https://github.com/HandyOrg/HandyControl/files/4538942/HandyControlProject3.zip)

**Comment by ghost1372** [comment]
tnx @NaBian  binding now work but now another problem exist 😁
language can not change i use this codes
```
LangProvider.Culture = new CultureInfo("fa");
ConfigHelper.Instance.SetLang("fa");
```

**Comment by NaBian** [comment]
try again! i guess it worked!

**Comment by ghost1372** [comment]
thank you it worked😉
