### ISSUE TITLE
Very poor performance when using ReactiveUI With HandyControl

### ISSUE THREAD

**Issue by AlBannaTechno** [HandyOrg/HandyControl#383]
**Describe the bug**
Very poor performance when using [ReactiveUI](https://github.com/reactiveui/reactiveui) With HandyControl

**To Reproduce**
1. Go to [ReactiveUiVmVhWithHCPerformance](https://github.com/AlBannaTechno/ReactiveUiVmVhWithHCPerformance)
2. Clone This repository

There are Two Branches 
* Master: this contains a sample to use reactiveUI with handy control, and show performance problem
  * To see performance without handy control, just omit HC imports  in `App.xaml` 
* Using-MaterialDesignXaml: contains a sample to use the same project but with [Material Design In Xaml](http://materialdesigninxaml.net/)

**Actual/Expected behavior**

When do navigation from side menu `Master-Branch`, you will notice poor performance `About 500 - 1133 ms delay`

But this should be done instantly, this problem occurs even if no binding, so this happens for very simple UI

#### Also Mirrored This Issue to [ReactiveUi-Team as an Issue](https://github.com/reactiveui/ReactiveUI/issues/2409)

  `There is someone from the RUI team reply, but now deleted his reply? :(`

### Screenshots: I [Upload Videos](https://mega.nz/folder/vhQxTAaZ#COS_CN6My4wPPN13m1os4g) for
* Sample App With Three States `RUI & HC -- RUI Only -- RUI - XamlMaterialDesign`
* Second App With intermediate  UI : `This contains explanation of performance even with empty ViewModel & no binding`
* Third App With Complex UI

I provide another two apps because, with additional UI elements performance go down and down, so I want to show that from real-life Scenario

### Environment 
 - .net: 4.7.2
 - IDE Visual Studio 2019 `16.5.3`
 - Version 2.4.0

**Comment by NaBian** [comment]
fixed in f835f25
