### ISSUE TITLE
nuget升级到2.5.0.1后的样式资源问题

### ISSUE THREAD

**Issue by Denny0503** [HandyOrg/HandyControl#387]
**Describe the bug**
使用nuget更新到2.5.0.1后使用GlowWindow窗体，运行时就提示找不到WindowWin10的静态资源样式了？？

**Comment by GF-Huang** [comment]
3.0 也有这个问题。

![image](https://user-images.githubusercontent.com/4510984/101243327-6bbb4d00-373a-11eb-81e2-a699acf5f623.png)

**Comment by ghost1372** [comment]
@GF-Huang  You do not need to set the style

**Comment by GF-Huang** [comment]
> @GF-Huang You do not need to set the style

It's generated by the HandyControl project template 😭

**Comment by ghost1372** [comment]
> > @GF-Huang You do not need to set the style
> 
> It's generated by the HandyControl project template 😭

template is outdated
use my vsix  It is always up to date😅

**Comment by GF-Huang** [comment]
> > > @GF-Huang You do not need to set the style
> > 
> > 
> > It's generated by the HandyControl project template 😭
> 
> template is outdated
> use my vsix It is always up to date😅

Could you give me a link? Thanks.

**Comment by ghost1372** [comment]
> > > > @GF-Huang You do not need to set the style
> > > 
> > > 
> > > It's generated by the HandyControl project template 😭
> > 
> > 
> > template is outdated
> > use my vsix It is always up to date😅
> 
> Could you give me a link? Thanks.

first  remove old
then install it
https://marketplace.visualstudio.com/items?itemName=MahdiHosseini.HandyControls
