### ISSUE TITLE
当TagPanel作为ItemsPanelTemplate使用时，点击关闭Tag会触发Invalid'OperationException

### ISSUE THREAD

**Issue by Luoyingliang** [HandyOrg/HandyControl#401]
**Describe the bug**
当TagPanel作为ItemsPanelTemplate使用时，点击关闭Tag会触发Invalid'OperationException，异常信息如下：
System.InvalidOperationException:“Cannot explicitly modify Children collection of Panel used as ItemsPanel for ItemsControl. ItemsControl generates child elements for Panel.”

**如何复现**
1. 将 TagPanel作为ItemsPanelTemplate的内容
2. 在ItemsSource里面添加几个Tag
3. 点击删除
4. 查看错误

**Comment by NaBian** [comment]
嗯。。。TagPanel现在看来是有些错误设计了，本意只是一个容器，不该被利用为ItemsPanelTemplate，那么接下来的工作是重构TagPanel，甚至可能完全移除这个控件，用新的TagContainer代替，所以本issue我选择关闭了。

**Comment by NaBian** [comment]
加了 #408
