### ISSUE TITLE
Add pt-br language?

### ISSUE THREAD

**Issue by adnan-54** [HandyOrg/HandyControl#416]
Hi, I've made a pt-br translation, may you add it? Thanks :)
[Lang.pt-br.zip](https://github.com/HandyOrg/HandyControl/files/4808851/Lang.pt-br.zip)

**Comment by ghost1372** [comment]
Hi @adnan-54 thank you
can you make a Pull Request? I'm a little busy😁

**Comment by adnan-54** [comment]
Uh, I dont know how to work with the project files... I'm kinda new to these things, and the project seems to use some shared project things that doesnt allows me to add the resource file, so ....  🙁

**Comment by NaBian** [comment]
@adnan-54 tnx, it would be better, if you could provide translation for hc demo. 😆

**Comment by adnan-54** [comment]
Sure!
[Lang.pt-br (demo).zip](https://github.com/HandyOrg/HandyControl/files/4822319/Lang.pt-br.demo.zip)

**Comment by NaBian** [comment]
thank you for your contribution 😆
