### ISSUE TITLE
NumericUpDown组件点击组件外的区域不会失去焦点

### ISSUE THREAD

**Issue by zhongwcool** [HandyOrg/HandyControl#419]
**Describe the bug**
NumericUpDown组件点击组件外的区域不会失去焦点，必须点击另外一个输入组件才会失去焦点

**To Reproduce**
1. 在NumericUpDown输入“22sdcvsd”
2. 点击组件外的任何区域

**Expected behavior**
点击NumericUpDown组件外的区域应该失去焦点，并触发输入事件

**Screenshots**
N/A

**Environment (please complete the following information):**
 - .net:  4.8
 - IDE Rider
 - Version 2.5.2

**Additional context**
N/A

**Comment by NaBian** [comment]
改控件与其它wpf输入类控件（如textbox）的行为一致。
