### ISSUE TITLE
Window MinHeight property doesn't word when set values

### ISSUE THREAD

**Issue by Luoyingliang** [HandyOrg/HandyControl#425]
Window MinHeight property doesn't word when set values

**Comment by ghost1372** [comment]
@Luoyingliang this issue exist in nuget package but seems to be fixed in the Github version so You'll have to wait for the next version of Nuget

**Comment by Luoyingliang** [comment]
thx for feedback




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mahdi Hosseini"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月4日(星期六) 晚上10:24
收件人:&nbsp;"HandyOrg/HandyControl"<HandyControl@noreply.github.com&gt;;
抄送:&nbsp;"Acoris"<731984870@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [HandyOrg/HandyControl] Window MinHeight property doesn't word when set values (#425)





 
@Luoyingliang this issue exist in nuget package but This problem seems to be fixed in the Github version so You'll have to wait for the next version of Nagt
