### ISSUE TITLE
内容控件的错误信息显示

### ISSUE THREAD

**Issue by unicorn1009** [HandyOrg/HandyControl#426]
可以添加带有错误消息显示的TextBox, ComboBox控件吗? 以便做前端数据校验的时候可以在文本框旁边明确提示错误信息
![TIM图片20200705122337](https://user-images.githubusercontent.com/39911458/86525492-61123880-beba-11ea-8380-35f2be4bf422.png)

**Comment by NaBian** [comment]
详见demo
