### ISSUE TITLE
Relative Panel Declaration Order Matters

### ISSUE THREAD

**Issue by danwalmsley** [HandyOrg/HandyControl#430]
**Describe the bug**
```
<h:RelativePanel Background="White">
            <Rectangle Name="rect1" Height="10" Width="20" Fill="Red" h:RelativePanel.Below="rect2" />
            <Rectangle Name="rect2" Height="10" Width="10" Fill="Yellow" />
</h:RelativePanel>
```

does not produce the expected output.

**To Reproduce**

**Expected behavior**

**Screenshots**
expected:
![image](https://user-images.githubusercontent.com/4672627/86942143-307d0980-c11b-11ea-8583-c2c7430cccbb.png)

actual:
![image](https://user-images.githubusercontent.com/4672627/86942248-4d194180-c11b-11ea-8fea-02753a8257e0.png)

**Environment (please complete the following information):**
 - .net: [e.g. 4.6.2]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by danwalmsley** [comment]
btw im not just an issue filer, with some direction or pointers I could submit a PR.

**Comment by NaBian** [comment]
tnx for your feedback

**Comment by danwalmsley** [comment]
https://github.com/HandyOrg/HandyControl/issues/433 related...
