### ISSUE TITLE
RelativePanel does not measure correct size in certain configuration

### ISSUE THREAD

**Issue by danwalmsley** [HandyOrg/HandyControl#431]
**Describe the bug**
Expected behavior (according to UWP) is that relativepanel sizes to the content, unless alignment = stretch.

```
<RelativePanel Background="White" VerticalAlignment="Top" HorizontalAlignment="Left">
            <Rectangle Name="rect1" Height="20" Width="20" Fill="Red"  />
            <Rectangle Name="rect2" Height="10" Width="10" Fill="Yellow" RelativePanel.AlignBottomWithPanel="True" />
          </RelativePanel>
```
 in uwp this produces.. 
![image](https://user-images.githubusercontent.com/4672627/86942753-e8121b80-c11b-11ea-9c8c-51a909feb9cd.png)

but in HandyControl.RelativePanel we get...
![image](https://user-images.githubusercontent.com/4672627/86942808-fb24eb80-c11b-11ea-804d-72b2f56b1b2e.png)

The issue is that Measure does not create a graph and calculate the correct size.

So arrange tells the graph is has the available space.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - .net: [e.g. 4.6.2]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by danwalmsley** [comment]
btw im not just an issue filer, with some direction or pointers I could submit a PR.

**Comment by NaBian** [comment]
fixed
