### ISSUE TITLE
RelativePanel doesnt measure correctly when items are relative to each other and panel isnt stretched

### ISSUE THREAD

**Issue by danwalmsley** [HandyOrg/HandyControl#433]
**Describe the bug**
```
<RelativePanel Background="White" VerticalAlignment="Top" HorizontalAlignment="Left">
            <Rectangle Name="rect1" Height="20" Width="20" Fill="Red"  />
            <Rectangle Name="rect2" Height="10" Width="10" Fill="Yellow" RelativePanel.Below="rect1" />
 </RelativePanel>
```

I expect:
![image](https://user-images.githubusercontent.com/4672627/87062386-5ff74900-c1e3-11ea-86d5-8018a68d1e12.png)

however.... (provided cliptobounds=true)

I actually get...

![image](https://user-images.githubusercontent.com/4672627/87062482-78fffa00-c1e3-11ea-8f4e-b711a88dffb0.png)

This is because the measure is just looking for the largest object and not taking into account the positioning.

Probably needs to use the graph to measure also.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - .net: [e.g. 4.6.2]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by NaBian** [comment]
fixed, but more tests may be needed
