### ISSUE TITLE
[Feature-request] Video Timeline - new Control

### ISSUE THREAD

**Issue by axel578** [HandyOrg/HandyControl#439]
Video edition timeline, implementing this feature would be just amazing because they are nearly no good alternative on the market, the timeline would allow mulitple control layer using a row system where every control on the timeline can be moved freely and where the timeline zone can be zoomed in/out and scrolling feature may be implemented with the zoom feature.

The Idea would be so to make a video editor timeline like Adobe premiere pro or better < crazy ?

**Comment by NaBian** [comment]
not surprisingly, it can be very complicated. better to create a separate project than to put it in HC as a control. so i close this issue.
