### ISSUE TITLE
The RunningBlock : height property doesn't adapt better.

### ISSUE THREAD

**Issue by JeremyWu917** [HandyOrg/HandyControl#447]
Hi brother,

I'm always frustrated when I use runningblock as a item of statusbar, cuz there is no height property to set and it changes the statusbar's sharp or the value is incomplete.

It will be great if I can set runningblock's property height just like common control, such as textblock.

Thank you!

**Comment by ghost1372** [comment]
@JeremyWu917  you can set height property,
```
<StatusBar VerticalAlignment="Bottom">
            <Label Content="test"/>
            <Label Content="test"/>
            <hc:RunningBlock Height="120">
                <Label Content="Hello"/>
            </hc:RunningBlock>
        </StatusBar>

```

i tested and worked fine, If you still have problems, please upload a demo project

**Comment by JeremyWu917** [comment]
> @JeremyWu917 you can set height property,
> 
> ```
> <StatusBar VerticalAlignment="Bottom">
>             <Label Content="test"/>
>             <Label Content="test"/>
>             <hc:RunningBlock Height="120">
>                 <Label Content="Hello"/>
>             </hc:RunningBlock>
>         </StatusBar>
> ```
> 
> i tested and worked fine, If you still have problems, please upload a demo project

Thanks for your reply.

After review the runningblock source code, it does allow you to set the height property, but when you set the height property to less than 51(Cuz most of the time, the height of the status bar will not exceed 30), another new problem arises, which is that the height doesn't adapt and the value doesn't display in full.

Maybe I should change the title of this issue to something like - The RunningBlock control height property doesn't adapt better.

Thanks again.

**Comment by JeremyWu917** [comment]
> @JeremyWu917 you can set height property,
> 
> ```
> <StatusBar VerticalAlignment="Bottom">
>             <Label Content="test"/>
>             <Label Content="test"/>
>             <hc:RunningBlock Height="120">
>                 <Label Content="Hello"/>
>             </hc:RunningBlock>
>         </StatusBar>
> ```
> 
> i tested and worked fine, If you still have problems, please upload a demo project

@ghost1372 
Sorry for the late response and here is the demo you can refer, thanks.
`<StatusBar VerticalAlignment="Bottom">
            <Label Content="test"/>
            <Label Content="test"/>
            <hc:RunningBlock Height="30">
                <Label Content="Hello"/>
            </hc:RunningBlock>
 </StatusBar>`

**Comment by ghost1372** [comment]
@JeremyWu917  Set the padding value to 0
```
 <hc:RunningBlock Padding="0" Height="30">
                <Label Content="Hello"/>
            </hc:RunningBlock>
```
![Untitled](https://user-images.githubusercontent.com/9213496/89987524-733e7e00-dc93-11ea-8a83-f331f9f247fb.png)


@NaBian  Wouldn't it be better if the padding was set to 0 by default? It is currently at 10
https://github.com/HandyOrg/HandyControl/blob/b4d1616753e67fe0015bf1062097df5a0d782164/src/Shared/HandyControl_Shared/Themes/Styles/Base/RunningBlockBaseStyle.xaml#L15

**Comment by NaBian** [comment]
> @JeremyWu917 Set the padding value to 0
> 
> ```
>  <hc:RunningBlock Padding="0" Height="30">
>                 <Label Content="Hello"/>
>             </hc:RunningBlock>
> ```
> 
> ![Untitled](https://user-images.githubusercontent.com/9213496/89987524-733e7e00-dc93-11ea-8a83-f331f9f247fb.png)
> 
> @NaBian Wouldn't it be better if the padding was set to 0 by default? It is currently at 10
> https://github.com/HandyOrg/HandyControl/blob/b4d1616753e67fe0015bf1062097df5a0d782164/src/Shared/HandyControl_Shared/Themes/Styles/Base/RunningBlockBaseStyle.xaml#L15

padding with a value of 10 is common in hc, such as button, textbox. so should RunningBlock.

**Comment by JeremyWu917** [comment]
@NaBian @ghost1372 Thanks for your reply.

When I set the height to 30 and the padding to 0, it does work fine, but when the height is even smaller, it still doesn't show up all the way. Please see the screenshot below.

So, if possible, I think it's a little better to set the height to adaptive, what do you think? Thank you.

`<hc:RunningBlock Padding="0" Height="20">
     <Label Content="Hello"/>
</hc:RunningBlock>`
![tip](https://user-images.githubusercontent.com/54832272/90080251-b6a0f700-dd3c-11ea-8c5e-e59dd064707d.gif)

**Comment by NaBian** [comment]
@JeremyWu917 ok, you can use codes following:

```cs
<hc:RunningBlock Height="20" Padding="0">
    <Label Content="Hello" Height="Auto" Padding="0"/>
</hc:RunningBlock>
```
