### ISSUE TITLE
2.5.0.2 use the client code but it wouldn't work（couldn't find ex:Lang...）

### ISSUE THREAD

**Issue by HHubbert** [HandyOrg/HandyControl#448]
hello:
I install the 2.5.0.2 nuget pacakge and use your demo to code , but it couldn't word, what 's the problem should i modify?
thanks!
![image](https://user-images.githubusercontent.com/20009150/88677396-ce169800-d11f-11ea-9421-6720a81b1f1c.png)
![image](https://user-images.githubusercontent.com/20009150/88677433-da9af080-d11f-11ea-8d09-f9a6b1bed863.png)

**Comment by ghost1372** [comment]
Our demo is multi languages you dont need to use `ex:lang`, so just fix content this way
`Content=" your button"`

**Comment by HHubbert** [comment]
omg, so easy, thanks!
