### ISSUE TITLE
messagebox.show()调用错误

### ISSUE THREAD

**Issue by 1111chance** [HandyOrg/HandyControl#45]
调用messagebox.show()时会出现一个大白框，demo中调用这个接口的时候好像依赖demo项目中的一堆资源文件：    
Style = ResourceHelper.GetResource<Style>("MessageBoxCustom")

**Comment by NaBian** [comment]
@1111chance  当使用 [MessageBox.Show(MessageBoxInfo info)](https://github.com/HandyOrg/HandyControl/blob/5d8e4e566a13c89d213a08c33990a2e7c73f7f0f/HandyControl/Controls/Window/MessageBox.cs#L210) 这个重载方法时需要自己指定MessageBox的样式
