### ISSUE TITLE
SearchBar还未输入完文字就开始执行搜索

### ISSUE THREAD

**Issue by wihalo** [HandyOrg/HandyControl#454]
设置IsRealTime="True"之后，在搜索栏输入中文时，文字还没有打出来(拼音)就已经在执行搜索了，希望能改成在文字输入完之后再去执行搜索。

**Comment by NaBian** [comment]
防抖的逻辑应该由业务层处理。

**Comment by GF-Huang** [comment]
> 防抖的逻辑应该由业务层处理。

业务层似乎无法得知目前用户输入的是拼音还是字母。如果按照 单引号 `'` 来判断，程序就太不健壮了。
另外有个问题就是点击 `清除` 按钮时，也会触发一次 **带有清除前的文本** 搜索。

![devenv_qPiW7zdbYy](https://user-images.githubusercontent.com/4510984/218327807-9872820c-c799-4154-b4f9-3cb846538182.gif)

作为对比，VS 的 NuGet 搜索没有这个问题。

![devenv_OJfQ9aRwlg](https://user-images.githubusercontent.com/4510984/218327954-8edec5ba-1bdd-4a04-83c4-785696a3c677.gif)
