### ISSUE TITLE
关于给PropertyGrid控件的SelectedObject属性赋一个对象耗时长

### ISSUE THREAD

**Issue by Yslelf** [HandyOrg/HandyControl#459]
就是现在PropertyGrid控件的SelectedObject属性赋一个对象耗时比较长，我比如想点击界面上一个控件，我点击了控件，要把该控件对象里的Tag属性传给PropertyGrid控件以便于可以编辑Tag属性里的实体类对象，但是现在现在赋值会耗时较长时间，PropertyGrid控件要过一会才会做出反应，这样会很不舒服，希望作者能优化下这个问题，winform的PropertyGrid控件赋对象很快的，瞬间就好了

**Comment by NaBian** [comment]
对 .net 4.5 及以上版本做了优化，4.0保持原样
