### ISSUE TITLE
密码框问题

### ISSUE THREAD

**Issue by towerDLH** [HandyOrg/HandyControl#460]
在密码框明文（点击小眼睛显示时）修改密码，密码的值保留上一个值

**Comment by ghost1372** [comment]
@towerDLH  I could not recreate your problem. Please provide an example (A project or a gif image)

**Comment by towerDLH** [comment]
就是小眼睛不关闭的情况下修改密码的值（明文修改），然后不关闭小眼睛（明文提交）这种情况下，密码是不会修改的

**Comment by ghost1372** [comment]
Do you mean this? I do not see a problem🤔
![10](https://user-images.githubusercontent.com/9213496/90364822-06076000-e07a-11ea-804c-4c47d7a87c93.gif)

**Comment by towerDLH** [comment]
这个需要配合登录一起看，就是明文输入点击登录
 https://github.com/towerDLH/wpfTestUI/blob/dev/Resources/2.gif

**Comment by JeremyWu917** [comment]
@towerDLH @ghost1372 
MVVM mode may cause this issue.
And please refer to this issue [#422](https://github.com/HandyOrg/HandyControl/issues/422)
