### ISSUE TITLE
TabControl控件 圆角 样式选择器触发出现问题

### ISSUE THREAD

**Issue by LemonAndJeo** [HandyOrg/HandyControl#461]
**bug描述**
动态加载tabControl的TabItems，页面初始化时首次加载，TabItem的圆角矩形样式为正常，当页面刷新缓存，重新对Tab的Items赋值后，圆角矩形样式发生变异。
初始化TabItems后台代码如下【Tab为tabControl控件名】
` this.Tab.Items.Clear();
                foreach (var item in _vm.Datas)
                {
                    this.Tab.Items.Add(item);
                }`
注：控件引用样式为Style="{StaticResource TabControlCapsuleSolid}" 

**截图**
GIF
![bug](https://user-images.githubusercontent.com/24291088/90476038-47bc0780-e15b-11ea-9c56-c1ad9414eb6c.gif)

相关代码
![image](https://user-images.githubusercontent.com/24291088/90476505-36272f80-e15c-11ea-872f-2db122fc7db2.png)

![image](https://user-images.githubusercontent.com/24291088/90476246-b4cf9d00-e15b-11ea-8e5d-75187ec17319.png)

正确样式
![image](https://user-images.githubusercontent.com/24291088/90476362-efd1d080-e15b-11ea-99a5-de0af9a28d1d.png)
异常样式
![image](https://user-images.githubusercontent.com/24291088/90476393-0546fa80-e15c-11ea-8bd3-a6fc73db6693.png)

**Environment (please complete the following information):**
 - .handyControl: [e.g. 2.5.0.2]
 - .net: [e.g. core3.1]
 - IDE [e.g. vs2019]
 - Version [e.g. 16.6.3]

**Comment by NaBian** [comment]
@LemonAndJeo 通过以下代码可以解决问题：
```cs
for (int i = 0; i < 5; i++)
{
    if(TabControlDemo.Items[i] is System.Windows.Controls.TabItem tabitem)
    {
        tabitem.Style = TabControlDemo.ItemContainerStyleSelector.SelectStyle(null, tabitem);
    }
}
```

此问题无法用优雅的方法解决，因为胶囊式按钮中的每个元素的样式会随着Items的数量而变化，不该在 `StyleSelector` 中更新其它Item，所以请使用以上方案解决问题，此issue因此关闭。
