### ISSUE TITLE
文本框问题

### ISSUE THREAD

**Issue by towerDLH** [HandyOrg/HandyControl#463]
<hc:TextBox TextType="Digits" hc:InfoElement.Placeholder="{ex:Lang Key={x:Static langs:LangKeys.PlsEnterEmail}}" hc:InfoElement.Title="{ex:Lang Key={x:Static langs:LangKeys.TitleDemoStr2}}" hc:InfoElement.Necessary="True" Margin="0,16,0,0"/>

TextType="Digits" 类型为Digits 可以输入非0-9 的字符

**Comment by ghost1372** [comment]
Yes, you can enter any character, only if it is not digit, you will receive an format error 
![Untitled](https://user-images.githubusercontent.com/9213496/90618427-3c351300-e225-11ea-88ec-a5f9a111b8ca.png)

**Comment by NaBian** [comment]
设计如此
