### ISSUE TITLE
Cannot use Growl module in App.xaml.cs

### ISSUE THREAD

**Issue by JeremyWu917** [HandyOrg/HandyControl#469]
Hi Guys

There is a bug (maybe not, I don't know), please help to check and advise.

Here is the demo

app.xaml.cs
`
namespace WpfApp1
{
    /// <summary>
    /// App.xaml 的交互逻辑
    /// </summary>
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);
            DispatcherUnhandledException += App_DispatcherUnhandledException;
        }

        private void App_DispatcherUnhandledException(object sender, DispatcherUnhandledExceptionEventArgs e)
        {
            // set as resolved
            e.Handled = true; 
            string errMsg = e.Exception.Message.ToString();

            // works well
            HandyControl.Controls.MessageBox.Show($"Unkonwn error -[{errMsg}]");
            
            // can see nothing!!!
            Growl.Error($"Unkonwn error -[{errMsg}]");
        }
    }
}
`

MainWindow.xaml
`
<Button x:Name="Start" Width="80" Height="30" Click="Start_Click" Content="Start" />
`

MainWindow.xaml.cs
`
private void Start_Click(object sender, RoutedEventArgs e)
{
    int i = 0;
    double result = 10 / i;
 }
`

**Comment by ghost1372** [comment]
What exactly is the problem?
First: Use 
`AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;
` instead of `DispatcherUnhandledException += App_DispatcherUnhandledException;`

Second:
If you do not have a container for the [Growl](https://ghost1372.github.io/handycontrol/extend_controls/growl/#Basic-usage), you must use the (Global methods) 
`Growl.ErrorGlobal($"Unkonwn error -[{errMsg}]");`

Third:
Move Growl top of Messagebox:
```
private void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            string errMsg = e.ExceptionObject.ToString();

            Growl.ErrorGlobal($"Unkonwn error -[{errMsg}]");

            HandyControl.Controls.MessageBox.Show($"Unkonwn error -[{errMsg}]");
        }
```

**Comment by NaBian** [comment]
请先阅读文档

**Comment by JeremyWu917** [comment]
@ghost1372 @NaBian 
Good day
Sorry for the inconvenience.
After review the doc, I know [Growl ](https://ghost1372.github.io/handycontrol/extend_controls/growl/#Basic-usage)should have a container if I wanna use it in project.
Thanks a lot
