### ISSUE TITLE
hc:Pagination 分页控件重复触发事件

### ISSUE THREAD

**Issue by 30797593** [HandyOrg/HandyControl#483]
场景：如果分页控件不是原本的第一页时，初始化分页控件绑定MaxPageCount=0或者MaxPageCount=null，此时分页控件会触发PageUpdated事件。
不同的查询条件结果都会导致重新初始化MaxPageCount，应该不需要触发事件的，因为这样会产生不要的查询

**Comment by NaBian** [comment]
你好，可以提供一份复现demo吗

**Comment by 30797593** [comment]
[HandyControlBugDemo.zip](https://github.com/HandyOrg/HandyControl/files/5368533/HandyControlBugDemo.zip)
您好，demo在附件里面，场景：先不加条件点击搜索，然后点击下一页，然后再加条件“5”搜索，会搜索出两条数据这时会更新分页控件，因为分页控件发生变化所以分页控件又会去触发事件，就会有重复触发请求。

**Comment by NaBian** [comment]
根据你写的代码，触发两次的原因是：command触发了两次，和分页控件无关
![QQ截图20201115142715](https://user-images.githubusercontent.com/17383395/99178507-b9055980-274e-11eb-9777-d02191546368.png)
