### ISSUE TITLE
Accessing and setting CheckComboBox SelectedItems 

### ISSUE THREAD

**Issue by CagatayCanK** [HandyOrg/HandyControl#485]
Hello, 
I am trying to use new CheckComboBox inside a DataGrid on my project and have some issues with it.

How can I pre-populate the selected items? 
I want to start the CheckComboBox filled with some values from a "selected items list" out of "all items list" and user can add/edit them later. I tried to databind "SelectedItems" property but it looks like its read-only. I am basically trying to assign properties like this: SelectedItems="{Binding Path=SelectedItems}" ItemsSource="{Binding Path=AllItems}"
How can I do "databind" a list to CheckComboBox and update it when an item is selected/unselected?

My second question is; is there a way to move selected items to top of the list?
![image](https://user-images.githubusercontent.com/18145716/94377564-9b8f1880-012b-11eb-8274-f024a73f7385.png)

**Comment by NaBian** [comment]
after this commit 5c11cef you can update SelectedItems by Add method:

``` cs
CheckComboBoxDemo.ItemsSource = list;
for (int i = 0; i < 10; i++)
{
    CheckComboBoxDemo.SelectedItems.Add(list[i]);
}
```

SelectedItems is not a dependency prop, while attach prop can fulfill your requirements.
for your second question, the simplest way is move selected items in your ItemsSource.
