### ISSUE TITLE
PropertyGrid绑定的对象与Prism提供的基类不兼容

### ISSUE THREAD

**Issue by tzm1119** [HandyOrg/HandyControl#486]
BindableBase是Prism框架提供的实现INotifyPropertyChanged接口的基类，我把下面的类绑定到PropertyGrid上时，直接报错了

public class PropertyGridDemoModel:BindableBase
    {
        private string bValue="66";
        public string BValue
        {
            get { return bValue; }
            set { SetProperty(ref bValue, value); }
        }
    }
这个异常还没法看详细信息
![image](https://user-images.githubusercontent.com/36020806/94411171-d71cf780-01aa-11eb-89c4-c6adf41f3b2d.png)

**Comment by tzm1119** [comment]
> BindableBase是Prism框架提供的实现INotifyPropertyChanged接口的基类，我把下面的类绑定到PropertyGrid上时，直接报错了
> 
> public class PropertyGridDemoModel:BindableBase
> {
> private string bValue="66";
> public string BValue
> {
> get { return bValue; }
> set { SetProperty(ref bValue, value); }
> }
> }
> 这个异常还没法看详细信息
> ![image](https://user-images.githubusercontent.com/36020806/94411171-d71cf780-01aa-11eb-89c4-c6adf41f3b2d.png)

我已经找到问题了，是因为下面的小括号造成的，只要对象实现了INotifyPropertyChanged，如果添加小括号，就会报错
![image](https://user-images.githubusercontent.com/36020806/94520705-523fe580-025f-11eb-93fd-afbd158023da.png)

**Comment by AlexVinci** [comment]
ImagePropertyEditor中override了CreateBinding方法，小括号未删除，所以实现了INotifyPropertyChanged的类，并包含ImageSource属性的话，仍有这个问题。
![ImagesourceEditor](https://user-images.githubusercontent.com/44226185/148325085-69232a67-f9cb-4c42-a156-abdf9cb716de.png)
![BaseEditor](https://user-images.githubusercontent.com/44226185/148325091-8ab3128e-2c31-48d7-b29c-5d51ed0c0990.png)
