### ISSUE TITLE
Dialog not closing from inside Task

### ISSUE THREAD

**Issue by DjSt3rios** [HandyOrg/HandyControl#488]
**Describe the bug**
Dialog does not close if dialog.Close(); called from a task while the application is not focused

**To Reproduce**
1. Create an empty WPF Project and download HandyControls 3.0.0-rc.1 from Nuget
2. Create a simple control to act as the dialog (I use a Border with some text on it and a spinning circle)
3. In your MainWindow.xaml.cs create an async Task, that closes the dialog after 2-3 seconds. A debug text would be helpful to check if dialog "IsClosed" is true or false
4. Create an instance of your control and show it using Dialog.Show(controlReference);
5. use Task.Run to run your async Task
6. Run the app and focus another window, and wait 3-4 seconds. Check your application and you will see the dialog still open! Run it again and have the app focused, you will notice the dialog closes just fine.

**Expected behavior**
I expected the dialog to close regardless the focus on the window

**Environment (please complete the following information):**
 - .net: .NET Core 3.1
 - IDE: VS2019
 - Version: 16.7.5

**Comment by NaBian** [comment]
pls use this method: Dialog.Show(new yourcontrol(), "custom token, anything you want, also need to set the same token for the parent container, just like Growl")

``` cs
var dialog = Dialog.Show(new UserControl1(), "123");
Task.Run(() =>
{
    Thread.Sleep(5000);

    Dispatcher.Invoke(() =>
    {
        dialog.Close();
    });
});
```

``` xml
<Window x:Class="WpfApp1.MainWindow"
        hc:Dialog.Token="123"
        ...>
    <Grid>

    </Grid>
</Window>
```
