### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by 3400442579** [HandyOrg/HandyControl#491]
add MahApps.Metro.ClipBorder

**Comment by ghost1372** [comment]
@3400442579  Please attach an image

**Comment by 3400442579** [comment]
`<Grid>
                    <Grid.RowDefinitions>
                        <RowDefinition/>
                        <RowDefinition/>
                        <RowDefinition/>

                    </Grid.RowDefinitions>
                    <Controls:ClipBorder CornerRadius="10" Width="100" Height="100">
                        <Image Source="/Assets/Photos/home.jpg"  Stretch="Fill"/>
                    </Controls:ClipBorder>

                    <Controls:ClipBorder  Grid.Row="1" CornerRadius="10" Width="100" Height="100">
                        <Grid Background="Red">
                            <TextBlock Text="Use ClipBorder"/>
                        </Grid>
                    </Controls:ClipBorder>

                    <Border  Grid.Row="2" CornerRadius="10" Width="100" Height="100">
                        <Grid Background="Blue">
                            <TextBlock Text="Use Border"/>
                        </Grid>
                    </Border>

                </Grid>          `


![image](https://user-images.githubusercontent.com/34226979/97381631-6f221400-1904-11eb-832f-cf20267cb702.png)

**Comment by NaBian** [comment]
you can try BorderClip Style, i promise you'll like it.

**Comment by GF-Huang** [comment]
Seems flawed, or am I using it incorrectly?

![image](https://user-images.githubusercontent.com/4510984/162539177-fb63ceb8-9a8b-46fe-b3b2-32a800490d53.png)
