### ISSUE TITLE
Can't add shadow effect on TabControl 

### ISSUE THREAD

**Issue by kikipoulet** [HandyOrg/HandyControl#494]
Hello ! 

So basically I'm trying to add a shadow effect on the TabControl control. 
So if I read the documentation and take the basic control : 
`<TabControl Margin="10">
    <TabItem Header="Tab 1">
    </TabItem>
    <TabItem Header="Tab 2">
    </TabItem>
    <TabItem Header="Tab 3">
    </TabItem>
</TabControl>`

I have this : 
![TabControl DefaultStyle](https://user-images.githubusercontent.com/19242427/97444720-bf14d100-192c-11eb-89a8-f89219128696.png)

And I would like to add a shadow effect on the bottom of the bar, in the red rectangle of this image : 

![TabControl DefaultStyle - Copy](https://user-images.githubusercontent.com/19242427/97444796-d5bb2800-192c-11eb-93e8-1ff52400f013.png)

I'm struggling with that, is it possible to do it ? 

Thanks for your time !

**Comment by NaBian** [comment]
just give a suggest here, modify TabControlBaseStyle, add a Border with shadow in element templateRoot:
```xml
<Border Grid.Row="0" Grid.Column="0" Margin="0,0,0,-1" VerticalAlignment="Bottom" Background="{DynamicResource BorderBrush}" Height="1">
  <Border.Effect>
    <DropShadowEffect BlurRadius="5" ShadowDepth="2" Direction="270" Opacity=".2" RenderingBias="Performance"/>
  </Border.Effect>
</Border>
```
![QQ截图20201101123148](https://user-images.githubusercontent.com/17383395/97795231-a2cfa780-1c3e-11eb-8618-41bdecb533cf.png)

**Comment by kikipoulet** [comment]
Hi !

Looks great, thanks for answering. I tried to do it, but I have a single little problem : I have no idea how to modify the TabControlBaseStyle style ! ^^
Do you have a kind of tutorial or something I could follow ?

**Comment by NaBian** [comment]
find TabControlBaseStyle in source code
