### ISSUE TITLE
Set HandyControl theme to just one WPF usercontrol

### ISSUE THREAD

**Issue by MohammadRezaKashi** [HandyOrg/HandyControl#498]
I want to set Handycontrol theme to just one WPF usercontol but when I set the handycontrol them to a specific usercontrol it is ok in the design time while at the run time it changes to the app's theme And when I apply the theme to the app it applies to the whole of the application which is not my purpose.

**Comment by ghost1372** [comment]
Hello, how are you doing this? Please show us a code snippet or example

**Comment by MohammadRezaKashi** [comment]
Hello, thank you for  your attention.
I want to use  Handycontrol theme just for one WPF usercontrol or window
not any other parts. For example, below code is a window in my application
and I want to to apply " SkinDark " just to this window not any other
parts, in the design time everything is correct and I can see that this
window has " SkinDark "  but when I run the application " SkinDark "  will
be converted to the "defaultSkin" so I have to insert " SkinDark " in to
the "Resourcedictionary" of the "App.xaml" so it leads to apply " SkinDark
" to all the application which is not my purpose:

<Window x:Class="DataUploading.UploadImageWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="
http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:DataUploading"
        xmlns:hc="https://handyorg.github.io/handycontrol"
        xmlns:controls="clr-namespace:WpfControls.Controls"
        mc:Ignorable="d"
        Title="UploadImageWindow" Height="419.062" Width="446.562"
        RenderOptions.BitmapScalingMode="HighQuality"
RenderOptions.CachingHint="Cache" RenderOptions.ClearTypeHint="Enabled"
UseLayoutRounding="True" WindowStyle="None"
        MouseDown="Window_MouseDown" AllowsTransparency="True"
Topmost="True">

    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <hc:Theme Name="HandyTheme"/>
                <ResourceDictionary
Source="pack://application:,,,/HandyControl;component/Themes/SkinDark.xaml"/>
                <ResourceDictionary
Source="ResourceDictionary/Style/MyButton.xaml"/>
                <ResourceDictionary
Source="ResourceDictionary/Style/MyToggleButton.xaml"/>
                <ResourceDictionary
Source="ResourceDictionary/MyColor.xaml"/>
            </ResourceDictionary.MergedDictionaries>
            <hc:EnumDataProvider x:Key="Sex" Type="local:PatientSex"/>
        </ResourceDictionary>
    </Window.Resources>

    <Window.Background>
        <SolidColorBrush Color = "{StaticResource DrawerLeftColor}"
Opacity="0.5" />
    </Window.Background>

    <hc:TransitioningContentControl>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"></RowDefinition>
                <RowDefinition></RowDefinition>
                <RowDefinition Height="Auto"></RowDefinition>
            </Grid.RowDefinitions>
            <Grid Grid.Row="0">
                <TextBlock VerticalAlignment="Center"
HorizontalAlignment="Center" Foreground="White" TextBlock.FontSize="30"
Margin="15">Patient Information</TextBlock>
            </Grid>
            <Grid Grid.Row="1">
                <StackPanel>
                    <hc:TextBox x:Name="TextBox_PatientName"
TextElement.FontSize="18" Margin="15" ShowClearButton="True" Width="380"
hc:InfoElement.TitleWidth="140" hc:InfoElement.Placeholder="Patient Name"
hc:InfoElement.TitlePlacement="Left" hc:InfoElement.Title="Patient Name"
 hc:InfoElement.Necessary="True"/>
                    <hc:TextBox x:Name="TextBox_PatientFamily"
TextElement.FontSize="18" Margin="15" ShowClearButton="True" Width="380"
hc:InfoElement.TitleWidth="140" hc:InfoElement.Placeholder="Patient Family"
hc:InfoElement.TitlePlacement="Left" hc:InfoElement.Title="Patient Family"
hc:InfoElement.Necessary="True"/>
                    <hc:NumericUpDown x:Name="NumericUpDown_PatientAge"
TextElement.FontSize="18" Margin="15" Width="380"
hc:InfoElement.TitleWidth="140" ShowClearButton="True"
Style="{StaticResource NumericUpDownPlus}"
hc:InfoElement.TitlePlacement="Left" hc:InfoElement.Title="Patient Age"
hc:InfoElement.Necessary="True"/>
                    <hc:ComboBox x:Name="ComboBox_PatientSex" Margin="15"
TextElement.FontSize="18" AutoComplete="True" ShowClearButton="True"
ItemsSource="{Binding Source={StaticResource Sex}}" IsEditable="True"
Width="380" hc:InfoElement.TitleWidth="140"
hc:InfoElement.Placeholder="Patient Sex"
hc:InfoElement.TitlePlacement="Left" hc:InfoElement.Title="Patient Sex"
hc:InfoElement.Necessary="True" />
                </StackPanel>
            </Grid>
            <Grid Grid.Row="2">
                <StackPanel Orientation="Horizontal"
VerticalAlignment="Center" HorizontalAlignment="Center">
                    <Button x:Name="Btn_Cancle" Style="{StaticResource
Button_Style_5}" Margin="15" Width="80" Height="30"
Click="Btn_Cancle_Click"  controls:MyButtonProperties.TextColor="White"
controls:MyButtonProperties.HoverTextColor="{DynamicResource
DrawerLeftBorderBrush}" controls:MyButtonProperties.ButtonText
="Accept"></Button>
                    <Button x:Name="Btn_Ok" Style="{StaticResource
Button_Style_5}" Margin="15" Width="80" Height="30" Click="Btn_Ok_Click"
controls:MyButtonProperties.TextColor="White"
controls:MyButtonProperties.HoverTextColor="red"
controls:MyButtonProperties.ButtonText ="Cancel"></Button>
                </StackPanel>
            </Grid>
        </Grid>
    </hc:TransitioningContentControl>
</Window>

how can I achieve my goal?

thank you.

**Comment by ghost1372** [comment]
remove this two line
```
  <hc:Theme Name="HandyTheme"/>
                <ResourceDictionary
Source="pack://application:,,,/HandyControl;component/Themes/SkinDark.xaml"/>
```
and use this single line

`<hc:Theme Skin="Dark"/>`

![1](https://user-images.githubusercontent.com/9213496/97881309-7cd9fe00-1d37-11eb-818d-457c54900801.gif)
