### ISSUE TITLE
 HandyControl theme in Windows.Resources cause PropertyGrid's some styles invalid.

### ISSUE THREAD

**Issue by maye1115** [HandyOrg/HandyControl#499]
```
<Window x:Class="Controls_TEST.MainWindow"
      ...
        xmlns:hc="clr-namespace:HandyControl.Controls;assembly=HandyControl"
        xmlns:local="clr-namespace:Controls_TEST"
      ...
        Title="MainWindow" Height="450" Width="800">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/SkinDefault.xaml"/>
                <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
    <Grid x:Name="xx" >
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="auto"></ColumnDefinition>
            <ColumnDefinition Width="10"></ColumnDefinition> 
            <ColumnDefinition Width="auto"></ColumnDefinition>
            <ColumnDefinition Width="auto"></ColumnDefinition>
            <ColumnDefinition></ColumnDefinition>
        </Grid.ColumnDefinitions>

        <local:UserControl1 >
            <hc:PropertyGrid   Width="240" SelectedObject="{Binding DemoModel}"></hc:PropertyGrid>
        </local:UserControl1>
        <Button Grid.Column="2" Content="样式被HandyControl覆盖"></Button>
        <hc:PropertyGrid Grid.Column="3"  Width="240" ></hc:PropertyGrid>
       
    </Grid>
</Window>
```
**description**
  "\< Button Grid.Column="2" \> " can be set by HandyControl theme,but  some of hc:PropertyGrid‘s styles will not be changed, such as  the toggle button at the top and button.
  But  if
 \<ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/SkinDefault.xaml"\/\>
 \<ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml"\/\> 
set at Application.Resources ,it will work well. 

What's  wrong?

**Comment by maye1115** [comment]
![对比](https://user-images.githubusercontent.com/56068387/98342545-858a4700-204b-11eb-8c43-1bf94a20a799.png)

Like :https://github.com/HandyOrg/HandyControl/issues/498
I just want to set Handycontrol theme to just one WPF usercontol.This problem make me only set handycontrol theme at Application.Resources. 
Thank you!

**Comment by ghost1372** [comment]
Similar to https://github.com/HandyOrg/HandyControl/issues/593

**Comment by NaBian** [comment]
如果要在window中添加资源，请在静态构造函数中以代码方式添加

**Comment by maye1115** [comment]
> 如果要在window中添加资源，请在静态构造函数中以代码方式添加

我查看源码 要用的样式资源是在App里查找的  以代码方式添加似乎也不会起作用呀？
![56`7N(P34L EBVUX(D2O05E](https://user-images.githubusercontent.com/56068387/104808356-9d86ff80-5820-11eb-88cc-a0bd5cc4f087.png)
