### ISSUE TITLE
button icon with text

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#5]
hi can we use buttonIcon style with text?
this is a simple button that only show a text
```
<Button
Content="{x:Static langs:Lang.Danger}"
Style="{StaticResource ButtonDanger}" />
```
this is a IconButton that only show a icon
```
<Button
controls:IconElement.Geometry="{StaticResource AddGeometry}"
Style="{StaticResource ButtonIconDanger}" />
```
so i tested this but only show icon
```
<Button
content="Something Text"
controls:IconElement.Geometry="{StaticResource AddGeometry}"
Style="{StaticResource ButtonIconDanger}" />
```

**Comment by NaBian** [comment]
Iconbutton will be removed in version 1.2.2, and the IconElement.Geometry property can be used on simple button, therefore, you can use text and icon at the same time.

**Comment by ghost1372** [comment]
tnx @NaBian  Is it possible to release the control of the combobox and datagrid in the next version? also Is there a specific place to talk about controls? Sometimes the features for the controls come to my mind, it's good if there's a place to share them

**Comment by NaBian** [comment]
No, they're not in the plan yet,  instead, timepicker, datepicker and stepbar will release in the next version. As for the place you mentioned, I recommend it : https://gitter.im/HandyControl/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
