### ISSUE TITLE
[Feature request] Support for multiple themes in the running app and Accent Color

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#500]
Theme support needs to be improved (Perhaps related to #361 )
In [Modern WPF](https://github.com/Kinnara/ModernWpf) we can use several different themes at the same time

The application theme is applied as follows
```
<ResourceDictionary.MergedDictionaries>
                <ui:ThemeResources RequestedTheme="Light" AccentColor="Red" />
                <ui:XamlControlsResources />
</ResourceDictionary.MergedDictionaries>
```

or

```
ThemeManager tm = ThemeManager.Current;
tm.ApplicationTheme = ApplicationTheme.Light;
```

As you can see, the theme of the program is set to Light
If we want a button or any other control to have a theme other than light (for example, dark) we can do this
`<Button ui:ThemeManager.RequestedTheme="Dark"/>`
And if we run the program, we can use both themes at the same time

But in HandyControl of how to set the theme is different and it is not possible to use 2 themes at the same time

![image](https://user-images.githubusercontent.com/9213496/98680833-314ad400-2377-11eb-8b44-5a9550e47ec4.png)

**Comment by Offline-R503B** [comment]
The addition of this would greatly improve the customizability of controls without to much of a hassle! 
Looking forward to it and patiently waiting for it! 👍
