### ISSUE TITLE
Is there a way to add Images to Cover Flow without using a URI ?

### ISSUE THREAD

**Issue by AnesHamdani08** [HandyOrg/HandyControl#501]
I love the idea of the cover flow but what i want is to add images of my songs to the cover flow which aren't resources that i can point to using URI's so what i'm asking is if there is any way to add Images(bitmap image ...) to the cover flow

**Comment by NaBian** [comment]
use this method:
```
CoverFlowMain.AddRange(new[]
{
    new Image(),
    new Image(),
    new Image()
});
```
