### ISSUE TITLE
BlurWindow no blur effect

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#502]
**Describe the bug**
`BlurWindow` no blur effect.

**Screenshots**
![pno6gXFLXt](https://user-images.githubusercontent.com/4510984/99458853-2b9d5180-2968-11eb-9b6e-6feec1408540.gif)

**Environment (please complete the following information):**
 - .net: `.net 5`
 - IDE `vs2019`
 - Version `2.5.0.2`

**Comment by ghost1372** [comment]
This is window 10 bug
https://ghost1372.github.io/handycontrol/extend_controls/blurWindow/

Blurwindow only support in windows 10 version 10240 ~ 18362

**Comment by GF-Huang** [comment]
Does Win10 1909 in range?

**Comment by ghost1372** [comment]
> Does Win10 1909 in range?

No
