### ISSUE TITLE
TitleElement.Title not works for ToggleButton

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#504]
**Describe the bug**
`TitleElement.Title` not works for `ToggleButton`.

**Environment (please complete the following information):**
 - .net: `.net 5`
 - IDE `vs2019`
 - Version `2.5.0.2`

**Comment by ghost1372** [comment]
Hi @GF-Huang  
This Attached Property is only available on some controls Unfortunately, toggle button is not one of them
@NaBian , will this feature be added to this control in the future?

**Comment by NaBian** [comment]
@ghost1372 no, only for some input elements
