### ISSUE TITLE
How to make NumericUpDown display thousands comma separator?

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#507]
I had try `TextType` property, but seems not work.

![image](https://user-images.githubusercontent.com/4510984/99694790-bea0cd80-2ac7-11eb-8d5b-2f90038104d4.png)

**Comment by ghost1372** [comment]
`TextType` is  not supported in **NumericUpDown**

**Comment by GF-Huang** [comment]
#514
