### ISSUE TITLE
[Feature request]可以更改本地化功能是否启用（Can change whether localization is enabled or not）

### ISSUE THREAD

**Issue by MisakaCirno** [HandyOrg/HandyControl#509]
我没有在代码中使用HandyControl的本地化功能，但在编译后在软件目录下也会多出很多语言文件。不过删掉这些文件好像也并不会影响程序的使用。

那么这个功能是否可以设置为默认关闭（不再自动生成许多语言文件），只有使用功能后再开启呢？

Translated by translation software:
I don't use HandyControl localization in my code, but there are many more language files in the software directory after compilation. But deleting these files doesn't seem to affect how the program works.

Can this feature be turned off by default (instead of automatically generating many language files) and only turned on after using the feature?

**Comment by NaBian** [comment]
如果你使用的是nuget包，可以将包中语言文件删除，如果是引用的源代码，则可以直接将项目中的多语言删除，如果怕麻烦还可以通过“编译事件”执行命令行自动删除语言包

**Comment by MisakaCirno** [comment]
> 
> 
> 如果你使用的是nuget包，可以将包中语言文件删除，如果是引用的源代码，则可以直接将项目中的多语言删除，如果怕麻烦还可以通过“编译事件”执行命令行自动删除语言包

按照第一种方式已解决问题，非常感谢

**Comment by ghost1372** [comment]
@MisakaCirno  you can also do this in csproj file
`    <SatelliteResourceLanguages>en;fr</SatelliteResourceLanguages>
`
