### ISSUE TITLE
How to choose seconds in DateTimePicker?

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#511]

**Comment by ghost1372** [comment]
@GF-Huang  are you mean this?
`var sec = dateTimePicker.SelectedDateTime.Value.Second;`

**Comment by GF-Huang** [comment]
> @GF-Huang are you mean this?
> `var sec = dateTimePicker.SelectedDateTime.Value.Second;`

I means choose in GUI by user...

**Comment by ghost1372** [comment]
@GF-Huang  Hover the mouse over the seconds And change it with the middle mouse roller
![1](https://user-images.githubusercontent.com/9213496/99955015-e37f9400-2d98-11eb-82ed-52273b6976d0.gif)

**Comment by GF-Huang** [comment]
Got it, thanks.
