### ISSUE TITLE
How to change the language of the default context menu?

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#527]
![image](https://user-images.githubusercontent.com/4510984/100536214-065aee00-325a-11eb-91fe-bd9f2b053e9b.png)

**Comment by ghost1372** [comment]
I think you have to create a Context menu yourself

**Comment by ghost1372** [comment]
or mybe 
`        <TextBox Language="cz" />
`

**Comment by GF-Huang** [comment]
> or mybe
> ` <TextBox Language="cz" />`

Can I global it in all windows?

**Comment by ghost1372** [comment]
> > or mybe
> > ` <TextBox Language="cz" />`
> 
> Can I global it in all windows?

I do not know😅

**Comment by NaBian** [comment]
https://handyorg.github.io/handycontrol/langs/

**Comment by ghost1372** [comment]
> https://handyorg.github.io/handycontrol/langs/

Oh you're right this method works

**Comment by ghost1372** [comment]
Not all languages work
Persian and Chinese did not work, but French did

**Comment by NaBian** [comment]
> Not all languages work
> Persian and Chinese did not work, but French did

you must install specified language package in your system

**Comment by GF-Huang** [comment]
`ConfigHelper.Instance.SetLang` not works for the `hc:TextBox` default context menu.

**Comment by NaBian** [comment]
try these codes:
```
public partial class App
{
    protected override void OnStartup(StartupEventArgs e)
    {
        base.OnStartup(e);

        ConfigHelper.Instance.SetLang("zh-cn");
    }
}

```

**Comment by GF-Huang** [comment]
Yes, I had try this. Do I need install .net 5 runtime with Chinese pack?

**Comment by NaBian** [comment]
Uh, maybe!

**Comment by GF-Huang** [comment]
> Uh, maybe!

Do you try deploy the demo in .NET 5/Core desktop app? The current demo seems like target to .NET framework, so it works well.

**Comment by NaBian** [comment]
i can't find lang packs for .net 5.0, the native textbox has the same behavior too.

**Comment by GF-Huang** [comment]
I think it's .NET runtime issue.
