### ISSUE TITLE
Breaking change log suggestion

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#529]
The 3.0 was released. 

But the `rename TitleElement.TitleAlignment to TitleElement.TitlePlacement` change in `3.0-rc1` is a breaking change. 

It should be listed in 3.0 release log.

![image](https://user-images.githubusercontent.com/4510984/100541806-42ee1000-3281-11eb-99a0-ad9f1f37f100.png)

**Comment by ghost1372** [comment]
It may be better to create a separate page on the documentation and mention the Breaking changes there

**Comment by ghost1372** [comment]
added in https://github.com/HandyOrg/HandyControl/pull/566
