### ISSUE TITLE
Status bar foreground doesn't change with change in theme!

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#530]
**Description**
StatusBarItem foreground stays "black" when theme is switched from light to dark.

**To Reproduce**
1. Create a HandyControls project in Visual Studio 2019.
2. Add light, dark and voilet themes to the app.
3. In MainWindow xaml add a StatusBar.
4. Then to this StatusBar add a StatusBarItem and set it's content.
5. Now run the app. And change the theme between light and dark or violet. You'll notice when the theme has been changed to dark from light the StatusBarItem's foreground does not change from black to white.

**Expected behavior**
When the theme has changed from light to dark I expect the StatusBarItem's foreground to change from black to white.

**Environment:**
 - .net: [e.g. 4.7.2]
 - IDE [vs2019]
 - Version [e.g. 16.8.2]

All other controls I've add to the app  change their foreground as expected when the theme changes.

**Comment by ghost1372** [comment]
Thank you
for now you can use this way:
`            <StatusBarItem Foreground="{DynamicResource PrimaryTextBrush}" Content="Test"/>
`
