### ISSUE TITLE
Issues with Jetbrains Rider

### ISSUE THREAD

**Issue by DineshSolanki** [HandyOrg/HandyControl#536]
**Describe the bug**
When opening a project made with HandyControl visual studio template, in [Rider](https://www.jetbrains.com/rider/), I got a warning that 
_Project 'myProject' load finished with warnings: [NETSDK1022] Duplicate 'Page' items were included. The .NET SDK includes 'Page' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultPageItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Properties\DesignTimeResources.xaml' at (69:5)_

this warning becomes an error when building or running the project in Rider, and won't let me proceed.
so I added a line 

```xml
<EnableDefaultPageItems>false</EnableDefaultPageItems>
```
in myProject.csProj (I believe this value is default TRUE).
and that error went away but a bunch of other errors appeared such as "Cannot resolve symbol 'InitlizeComponent'"
, cannot convert expression type MainWindow to return type System.windows.window (at CreateShell) MainWindow is hc:Window.

leaving EnabledDefaultPageItems to FALSE give all these same error in visual studio also, but setting to true make it work in visual studio.
 there are this ItemGroup in *.csProj file 
 ```xml
<ItemGroup>
    <Page Include="Properties\DesignTimeResources.xaml" Condition="'$(DesignTime)'=='true' OR ('$(SolutionPath)'!='' AND Exists('$(SolutionPath)') AND '$(BuildingInsideVisualStudio)'!='true' AND '$(BuildingInsideExpressionBlend)'!='true')" >
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <ContainsDesignTimeResources>true</ContainsDesignTimeResources>
    </Page>
  </ItemGroup>
```

**Removing these lines and setting EnabledDefaultPageItems to TRUE. Made the project work in Rider.**

but when I change theme while any TextBox on the current page has the property VerticalScrollBarVisibility = true, the project throws an exception - 
[See stacktace here](https://gist.github.com/DineshSolanki/b2a860199ef628500733c90e0ef2da4f#file-stacktrace-md)
**To Reproduce**
1. Create a project with HandyControl Visual Studio AddOn template
2. open it inJetbrains [Rider](https://www.jetbrains.com/rider/) -**First error**
3. Add <EnableDefaultPageItems> FALSE </EnableDefaultPageItems> -**Second Error**
4. Create a TextBox and set VerticalScrollBarVisibility = Visible and then change Theme. -**Third Error**

**Environment :**
 - .net: core 3.0
 - IDE [e.g. vs 2019/ Rider 2020 2.3

**Comment by ghost1372** [comment]
Hi @DineshSolanki  This is not a bug at least not related to HandyControl and is related to Rider
However, it looks like Rider can't render DesignTimeResource You can delete the Properties folder along with the DesignTimeResources.xaml file Also do not forget to remove the following code from the csproject file
```
<ItemGroup>
   <Page Include="Properties\DesignTimeResources.xaml" Condition="'$(DesignTime)'=='true' OR ('$(SolutionPath)'!='' AND Exists('$(SolutionPath)') AND '$(BuildingInsideVisualStudio)'!='true' AND '$(BuildingInsideExpressionBlend)'!='true')" >
     <Generator>MSBuild:Compile</Generator>
     <SubType>Designer</SubType>
     <ContainsDesignTimeResources>true</ContainsDesignTimeResources>
   </Page>
 </ItemGroup>
```

The program compiles and runs without any problems also You do not need this line
`<EnableDefaultPageItems>false</EnableDefaultPageItems>
`

**Comment by DineshSolanki** [comment]
I know I do not need the last line because the default is true, about this being a ReSharper issue, I'll post it there,
And can you give me any insight on the theme changing exception?

**Comment by DineshSolanki** [comment]
Deleting properties folder will not have any negative consequences? Even in visual studio?

**Comment by ghost1372** [comment]
@DineshSolanki  I created a new project and changing the theme did not cause any problems

**Comment by DineshSolanki** [comment]
Did you set verticalScrollBarVisibility = visible of the textbox?
After deleting that item group lines from csproj?

**Comment by ghost1372** [comment]
> Did you set verticalScrollBarVisibility = true of textbox?
> After deleting that item group lines from caproj?

yes

**Comment by DineshSolanki** [comment]
It happens with me though, might be caused by something else, I'll try to figure out.
Thanks🙂

**Comment by DineshSolanki** [comment]
I tried googling almost every search term I could but couldn't solve it. Can you try looking at it?
![image](https://user-images.githubusercontent.com/15937452/100759755-ffc5a580-3416-11eb-84d2-ffd5c58ab760.png)

**Comment by DineshSolanki** [comment]
This is driving me crazy, I added back the properties folder, also added back those lines, anything else wasn't changed, and this still is not working, It was working before I removed those lines for the first time.
does this help ? [https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/scrollviewer-styles-and-templates?view=netframeworkdesktop-4.8](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/scrollviewer-styles-and-templates?view=netframeworkdesktop-4.8)

**Comment by ghost1372** [comment]
1.are you using HandyControl latest version? [3.0.0]
2.if you can please send me your project
3.Properties folder and DesignTimeResource They do not matter I added this file so that if there is a problem in identifying the resources in Visual Studio Designer, their absence will not cause a problem in running the program.

**Comment by DineshSolanki** [comment]
Yes I'm using HandyControl v3.0.0
Where can I find your email ?

**Comment by ghost1372** [comment]
> Yes I'm using HandyControl v3.0.0
> Where can I find your email ?

upload your project here in your issue

**Comment by DineshSolanki** [comment]
[ERSB.zip](https://github.com/HandyOrg/HandyControl/files/5623748/ERSB.zip)

Steps to reproduce - 
First click on Data Extractor then change Theme. (the TextBox and Toggle Button looks strange becuase There were in stackpanel and Replaced with grid to see if that helps)

**Comment by ghost1372** [comment]
@DineshSolanki  I found the problem
Change Height of rows like this:
```
<Grid.RowDefinitions>
                <RowDefinition Height="*"/>
                <RowDefinition Height="50" />
                <RowDefinition Height="auto" />
            </Grid.RowDefinitions>
```

**Comment by DineshSolanki** [comment]
@ghost1372 Still the same problem.

**Comment by ghost1372** [comment]
> @ghost1372 Still the same problem.

In general, this problem is due to the design of your user interface
With this change, I was able to run your program without any problems

**Comment by DineshSolanki** [comment]
I don't find anything unusual, and it was working, suddenly I don't know what caused it.

**Comment by DineshSolanki** [comment]
I changed the height of TextBox and the theme change started working, but as I input text in it and it auto changes the height, Then changing the theme causes the exception. (means when VerticalScrollBar is visible)
I think I'll just go with disabling the scrollbar.
Thank you so much for your help. for your efforts and ah..faster replies. 😄
