### ISSUE TITLE
建议将代码格式化风格限制在 .editorconfig 中，并提交到储存库中

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#540]
这样不必使用其他方式来限制格式化风格，所有使用这个储存库的解决方案的人都不必额外设置，或者提交代码前手工调整。

![image](https://user-images.githubusercontent.com/4510984/100835850-3f3cd200-34a9-11eb-87fa-941c79f34d32.png)

**Comment by GF-Huang** [comment]
@ghost1372 Should we add space when force cast?

![image](https://user-images.githubusercontent.com/4510984/100838516-81681280-34ad-11eb-8ab2-8ec15e9e7fbb.png)

**Comment by ghost1372** [comment]
> @ghost1372 Should we add space when force cast?
> 
> ![image](https://user-images.githubusercontent.com/4510984/100838516-81681280-34ad-11eb-8ab2-8ec15e9e7fbb.png)

In my opinion, no

**Comment by NaBian** [comment]
与 #533 重复
