### ISSUE TITLE
CoverFlow封面流的 Loop属性不起作用

### ISSUE THREAD

**Issue by DotnetManGoYu** [HandyOrg/HandyControl#542]
**Describe the bug**
设置Loop=true后，封面流图片不会自动循环
```
  public static readonly DependencyProperty LoopProperty =
        DependencyProperty.Register(
        "Loop", typeof(bool), typeof(CoverFlow), new PropertyMetadata(ValueBoxes.FalseBox));
```
缺少callback

**Comment by DotnetManGoYu** [comment]
![image](https://user-images.githubusercontent.com/38211635/100851230-dad93d00-34bf-11eb-997f-c57062a01f0f.png)
我仿照轮播图控件做了下，不知道有没有什么优化的意见

**Comment by NaBian** [comment]
Loop属性不是自动播放，而是当在最后一张封面上使用滚轮操作后，会跳转到第一张封面，如果为false，则不会跳转。
