### ISSUE TITLE
Designer error

### ISSUE THREAD

**Issue by NaBian** [HandyOrg/HandyControl#556]
after f835f251, if you open any xxxdemoctrl.xaml, you will have the following errors:
![QQ图片20201206003612](https://user-images.githubusercontent.com/17383395/101258125-53a7f580-375b-11eb-8c9a-28039374fb1a.png)

**Comment by ghost1372** [comment]
@NaBian 
first read this blog post Which has completely provided various solutions
https://michaelscodingspot.com/wpf-merged-dictionary-problemsandsolutions/
Then take a look at this sample
If I understand correctly, the order of the styles must be observed and DynamicsResource must also be used
https://github.com/michaelscodingspot/WpfMergingXamlResources

>  Just remember to order them correctly if the resources rely on each other.

**Comment by cuiliang** [comment]
I have checked the combined xaml file and find no resource order problem.

Tool used: https://github.com/cuiliang/CombinedXamlChecker

**Comment by cuiliang** [comment]
Error List 里有许多警告，不知道是不是和这个问题有关系
![image](https://user-images.githubusercontent.com/1972649/101268816-af49a180-37a2-11eb-8433-e34664dcaf43.png)

**Comment by NaBian** [comment]
> Error List 里有许多警告，不知道是不是和这个问题有关系
> ![image](https://user-images.githubusercontent.com/1972649/101268816-af49a180-37a2-11eb-8433-e34664dcaf43.png)

应该没啥影响

**Comment by NaBian** [comment]
error disappeared after commenting codes related to TranslateTransform in Theme,xaml

**Comment by GF-Huang** [comment]
Has this issue been deemed resolved? But I still encounter the same problem.

![image](https://user-images.githubusercontent.com/4510984/120505818-ecac8600-c3f7-11eb-9a14-acc0a43dc329.png)
