### ISSUE TITLE
[Feature request]Add link to component document on demo UI

### ISSUE THREAD

**Issue by cuiliang** [HandyOrg/HandyControl#575]
![image](https://user-images.githubusercontent.com/1972649/102000293-162a0600-3d21-11eb-867b-7907b6b5cd4b.png)

**Comment by ghost1372** [comment]
I already had in mind to make the demos interactive
I will start an interactive demo soon, of course, if @NaBian  agrees with these changes

Document Button can be to the right or bottom of the page
![Untitled](https://user-images.githubusercontent.com/9213496/102008941-49808b00-3d49-11eb-9fb0-b141e3e35af6.png)
