### ISSUE TITLE
Reduce size of arrow in Combbox

### ISSUE THREAD

**Issue by cuiliang** [HandyOrg/HandyControl#584]
关于设计的问题我也不懂，这是有个设计师用户提出的建议，供参考😂
![image](https://user-images.githubusercontent.com/1972649/102029280-d0387500-3de8-11eb-98e9-2145588a25c0.png)

**Comment by NaBian** [comment]
关于设计不太好去判定，就算是设计师，苹果和微软也是大相径庭，就多个控件比较而言，我认为combobox下拉框大小还是合适的
![QQ截图20201214095143](https://user-images.githubusercontent.com/17383395/102032227-2e6a5580-3df3-11eb-8612-c59a37be4f01.png)
当然，如果这位设计师能贡献一套整体的方案，那就更好了。

**Comment by cuiliang** [comment]
嗯，这套看起来确实是统一的👍
