### ISSUE TITLE
[Features request]  Add Grouping to the DataGrid, Auto Suggestion For SearchBox

### ISSUE THREAD

**Issue by o-coder-s** [HandyOrg/HandyControl#586]
Hello, first i would to thank you for such a great UI controls you provided. i would like to see more on the datagrid control as it wan be more powerful that it is, i would appreciate if you add the ability to group, drag and drop columns to change their positions, i also would like to see auto suggestion in the search box. Thank you.

**Comment by ghost1372** [comment]
@oSethoumOld  We have recently added an AutoCompleteTextBox control, I think this control can meet your needs
I'm closing this issue. If your datagrid needs are still not met, please open a new issue
