### ISSUE TITLE
Drawer won't close sometimes

### ISSUE THREAD

**Issue by igeeksng** [HandyOrg/HandyControl#589]
**Describe the bug**
It's hard to replicate. Anytime i use the drawer and i close hit close, it tries closing but it then hangs half way. I won't be able to click on any content behind it. The only way forward is to restart the application. I hope to keep updating these issue once i discovery it again.

**Comment by ghost1372** [comment]
@ehinolakingsley  please provide a demo project

**Comment by igeeksng** [comment]
@ghost1372 I will

**Comment by igeeksng** [comment]
> @ghost1372 It happens mostly when application losses focus at the point of about to open or about to close.

**Comment by ghost1372** [comment]
I can not reproduce your problem, please attach a sample project so we can check it.

**Comment by ghost1372** [comment]
@NaBian 
can we close this issue after https://github.com/HandyOrg/HandyControl/commit/d37ab735eaafe3c5f98656036358a7b0d0fbb165 ?

**Comment by NaBian** [comment]
It should be solved
