### ISSUE TITLE
3.0版本MessageBox控件顺序和高亮颜色反了

### ISSUE THREAD

**Issue by xianyun666** [HandyOrg/HandyControl#592]
旧
![1](https://user-images.githubusercontent.com/22339210/102683356-5a2e7680-420b-11eb-95b4-50e03f6410ee.png)

新
![2](https://user-images.githubusercontent.com/22339210/102683359-5f8bc100-420b-11eb-84c7-107a3140ee4a.png)

这样变动，会导致用户一直操作的逻辑，突然反了，影响用户体验

如果是一个按钮，2.5版本是有颜色底。现在3.0是白底。

**Comment by xianyun666** [comment]
有问题的是 MessageBox 下的一些静态方法
尝试Show MessageBoxInfo 又是另外一种情况

**Comment by adsf130162** [comment]
+1

**Comment by NaBian** [comment]
1、确定在左，取消在右，是和系统一致的行为，旧版本这个错误已经在新版本中修复；
2、MessageBox.Ask 符合确定在左，取消在右；
3、MessageBox.Ask是hc独有的方法，该方法被设计成默认选中按钮为“取消”，这可以防止用户误操作，如果认为这个设计不合理可以使用Show来代替；

综上所述：
旧版本hc存在按钮和系统不一致的问题，此问题相较于用户体验更严重，两权相害取其轻。

**Comment by xianyun666** [comment]
@NaBian  对于第3点，我不是很认同。参考了其他软件，询问弹框，默认都是选中OK状态。
至于用户误操作，用户需要先点击功能，然后再跳出弹框，已经够防止误操作了。
@guanguanchuangyu 
![image](https://user-images.githubusercontent.com/22339210/104880676-f9759380-599a-11eb-842b-10c0996c3bef.png)
![image](https://user-images.githubusercontent.com/22339210/104880690-04302880-599b-11eb-9849-9c2f9d8381e1.png)
