### ISSUE TITLE
Dialog covers the entire window!

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#594]
**Description of the bug**
When I want to display a dialog with the following code the dialog is displayed but covers the entire bounds of the parent window with a translucent background.

**To Reproduce**
Code to reproduce the behavior:

```
var dialog = new Dialog();

private void OpenDialog(object sender, RoutedEventArgs e)
{
dialog = Dialog.Show("Test"); 
}

private void CloseDialog(object sender, RoutedEventArgs e)
{
dialog.Close();
}

```

**Expected behavior**
The dialog must appear like a dialog as shown in the HandyControl's documentation. Instead it covers the entire parent window.

**Screenshots**  

This what Im getting:
![Screenshot (164).png](https://user-images.githubusercontent.com/32904377/102707978-9b835c80-42c5-11eb-9717-9c66226b2c96.png)

This what I wish (supposed) to get:  
![Dialog.png](https://user-images.githubusercontent.com/32904377/102708010-ca99ce00-42c5-11eb-97cf-2a2907347046.png)

**Environment:**
 - .net: [e.g. 4.7.2]
 - IDE [e.g. vs2019]
 - Version [e.g. 16.8.2]

**Comment by ghost1372** [comment]
Please Read the documentation carefully
https://ghost1372.github.io/handycontrol/extend_controls/dialog/
Because you did not specify an appearance for your dialogue
Create a user control and change its content as follows
```
<Border x:Class="HandyControlDemo.UserControl.TextDialog"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:hc="https://handyorg.github.io/handycontrol"
        CornerRadius="10"
        Width="400"
        Height="247"
        Background="{DynamicResource RegionBrush}">
    <hc:SimplePanel>
        <TextBlock Style="{StaticResource TextBlockLargeBold}" Text="Please Wait"/>
        <Button Width="22" Height="22" Command="hc:ControlCommands.Close" Style="{StaticResource ButtonIcon}" Foreground="{DynamicResource PrimaryBrush}" hc:IconElement.Geometry="{StaticResource ErrorGeometry}" Padding="0" HorizontalAlignment="Right" VerticalAlignment="Top" Margin="0,4,4,0"/>    
    </hc:SimplePanel>
</Border>
```
also
```
namespace HandyControlDemo.UserControl
{
    public partial class TextDialog
    {
        public TextDialog()
        {
            InitializeComponent();
        }
    }
}
```

now call your dialog:

`Dialog.Show(new TextDialog());
`
