### ISSUE TITLE
How to apply theme to all windows?

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#598]
I'm using the code provided in the documentation (wiki) to apply theme for my application as shown in below code:  
```
public void UpdateSkin(SkinType skin)
        {
            SharedResourceDictionary.SharedDictionaries.Clear();
            Resources.MergedDictionaries.Add(ResourceHelper.GetSkin(skin));
            Resources.MergedDictionaries.Add(new ResourceDictionary
            {
                Source = new Uri("pack://application:,,,/HandyControl;component/Themes/Theme.xaml")
            });
            Current.MainWindow?.OnApplyTemplate();
        }
```

 But only the MainWindow's theme changes when I change the theme at runtime the other windows are set to light colored theme.   
If I understand the code properly `Current.MainWindow?.OnApplyTemplate();` is what causes the theme to be applied to the MainWindow and MainWindow only. Am I right?

 How do I apply the theme for all windows (application wide) and not just for the main window?

**Comment by ghost1372** [comment]
> I'm using the code provided in the documentation (wiki) to apply theme for my application as shown in below code:
> 
> ```
> public void UpdateSkin(SkinType skin)
>         {
>             SharedResourceDictionary.SharedDictionaries.Clear();
>             Resources.MergedDictionaries.Add(ResourceHelper.GetSkin(skin));
>             Resources.MergedDictionaries.Add(new ResourceDictionary
>             {
>                 Source = new Uri("pack://application:,,,/HandyControl;component/Themes/Theme.xaml")
>             });
>             Current.MainWindow?.OnApplyTemplate();
>         }
> ```
> 
> But only the MainWindow's theme changes when I change the theme at runtime the other windows are set to light colored theme.
> If I understand the code properly `Current.MainWindow?.OnApplyTemplate();` is what causes the theme to be applied to the MainWindow and MainWindow only. Am I right?
> 
> How do I apply the theme for all windows (application wide) and not just for the main window?

![2](https://user-images.githubusercontent.com/9213496/102790310-80464900-43ba-11eb-825a-69fba512018a.gif)
Everything works well

**Comment by ms-somanna** [comment]
> > I'm using the code provided in the documentation (wiki) to apply theme for my application as shown in below code:
> > 
> > ```
> > public void UpdateSkin(SkinType skin)
> >         {
> >             SharedResourceDictionary.SharedDictionaries.Clear();
> >             Resources.MergedDictionaries.Add(ResourceHelper.GetSkin(skin));
> >             Resources.MergedDictionaries.Add(new ResourceDictionary
> >             {
> >                 Source = new Uri("pack://application:,,,/HandyControl;component/Themes/Theme.xaml")
> >             });
> >             Current.MainWindow?.OnApplyTemplate();
> >         }
> > ```
> > 
> > But only the MainWindow's theme changes when I change the theme at runtime the other windows are set to light colored theme.
> > If I understand the code properly `Current.MainWindow?.OnApplyTemplate();` is what causes the theme to be applied to the MainWindow and MainWindow only. Am I right?
> > 
> > How do I apply the theme for all windows (application wide) and not just for the main window?
> 
> ![2](https://user-images.githubusercontent.com/9213496/102790310-80464900-43ba-11eb-825a-69fba512018a.gif)
> Everything works well
> 

Is there something I have to put in the xaml of every window for the theme to work?

**Comment by ghost1372** [comment]
> > > I'm using the code provided in the documentation (wiki) to apply theme for my application as shown in below code:
> > > ```
> > > public void UpdateSkin(SkinType skin)
> > >         {
> > >             SharedResourceDictionary.SharedDictionaries.Clear();
> > >             Resources.MergedDictionaries.Add(ResourceHelper.GetSkin(skin));
> > >             Resources.MergedDictionaries.Add(new ResourceDictionary
> > >             {
> > >                 Source = new Uri("pack://application:,,,/HandyControl;component/Themes/Theme.xaml")
> > >             });
> > >             Current.MainWindow?.OnApplyTemplate();
> > >         }
> > > ```
> > > 
> > > 
> > > But only the MainWindow's theme changes when I change the theme at runtime the other windows are set to light colored theme.
> > > If I understand the code properly `Current.MainWindow?.OnApplyTemplate();` is what causes the theme to be applied to the MainWindow and MainWindow only. Am I right?
> > > How do I apply the theme for all windows (application wide) and not just for the main window?
> > 
> > 
> > ![2](https://user-images.githubusercontent.com/9213496/102790310-80464900-43ba-11eb-825a-69fba512018a.gif)
> > Everything works well
> 
> Is there something I have to put in the xaml of every window for the theme to work?

No.
If you attach a project example that has a problem, we can better solve your problem
Anyway, I think you used the background in your Windows
If you use the color in the background (Background="white"), the theme will not be applied, you must either delete the color or use the colors in HandyControl as a dynamic resource. (Background="{DynamicResource RegionBrush}")

**Comment by GF-Huang** [comment]
Similar issue, why this does not work?

```cs
public class ThemeManager : IThemeService {
    private const string SkinResourcePrefix = "pack://application:,,,/HandyControl;component/Themes/Skin";
    private const string ThemeResource = "pack://application:,,,/HandyControl;component/Themes/Theme.xaml";

    public void ChangeSkin(SkinType type) {
        var appMergedDictionaries = App.Current.Resources.MergedDictionaries;

        var skinResourceIndex = appMergedDictionaries.IndexOf(d => d.Source.OriginalString.StartsWith(SkinResourcePrefix));
        appMergedDictionaries[skinResourceIndex].MergedDictionaries.Clear();
        appMergedDictionaries[skinResourceIndex].MergedDictionaries.Add(new ResourceDictionary {
            Source = new Uri($"{SkinResourcePrefix}{type}.xaml", UriKind.Absolute)
        });

        var themeResourceIndex = appMergedDictionaries.IndexOf(d => d.Source.OriginalString == ThemeResource);
        appMergedDictionaries[themeResourceIndex].MergedDictionaries.Clear();
        appMergedDictionaries[themeResourceIndex].MergedDictionaries.Add(new ResourceDictionary {
            Source = new Uri(ThemeResource, UriKind.Absolute)
        });

        App.Current.MainWindow.OnApplyTemplate();
    }
}
```

Screenshot for easy reading:

![image](https://user-images.githubusercontent.com/4510984/105574874-4a71f700-5da2-11eb-845d-abe69693ce98.png)

**Comment by ghost1372** [comment]
@GF-Huang  I did not test your code but it looks like you did not write the file extension
change this line
`    private const string SkinResourcePrefix = "pack://application:,,,/HandyControl;component/Themes/Skin";
`
to 
`    private const string SkinResourcePrefix = "pack://application:,,,/HandyControl;component/Themes/Skin.xaml";
`

**Comment by GF-Huang** [comment]
It's write the tail at here.

![image](https://user-images.githubusercontent.com/4510984/105575923-3df19c80-5daa-11eb-9dd6-9ffcd4681782.png)

And the extensions if you need to debug:

```cs
    public static class IListExtension {
        public static int IndexOf<T>(this IList<T> list, Predicate<T> predicate) {
            for (int i = 0; i < list.Count; i++) {
                if (predicate(list[i]))
                    return i;
            }
            
            return -1;
        }
    }
```

**Comment by ghost1372** [comment]
Why are you making it so complicated?
Why are you not using the following code?
```
SharedResourceDictionary.SharedDictionaries.Clear();
            Resources.MergedDictionaries.Add(ResourceHelper.GetSkin(type));
            Resources.MergedDictionaries.Add(new ResourceDictionary
            {
                Source = new Uri("pack://application:,,,/HandyControl;component/Themes/Theme.xaml")
            });
```

**Comment by GF-Huang** [comment]
I don't know.. There's no docs talking about themes..

**Comment by ghost1372** [comment]
> I don't know.. There's no docs talking about themes..

https://ghost1372.github.io/handycontrol/theme/

**Comment by GF-Huang** [comment]
I think I should moving from HandyControl to HandyControls... Dam..

**Comment by ghost1372** [comment]
Theme documentation is also valid for HandyControl You should not have a problem

**Comment by GF-Huang** [comment]
So the Chinese docs is out of date?

![image](https://user-images.githubusercontent.com/4510984/105577051-0be43880-5db2-11eb-9458-6aabbfb50e7c.png)

**Comment by ghost1372** [comment]
Yes, the Chinese documentation is very old
Documents related to HandyControls have been identified
![Untitled](https://user-images.githubusercontent.com/9213496/105577116-e55fd680-5d8c-11eb-9853-15e9adeb7e89.png)

**Comment by GF-Huang** [comment]
Now, the skin changine works, but can these safe to ignore? It happens when I change skin by `hc:ComboBox`.

```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=HorizontalContentAlignment; DataItem=null; target element is 'ComboBoxItem' (Name=''); target property is 'HorizontalContentAlignment' (type 'HorizontalAlignment')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=VerticalContentAlignment; DataItem=null; target element is 'ComboBoxItem' (Name=''); target property is 'VerticalContentAlignment' (type 'VerticalAlignment')

```

![image](https://user-images.githubusercontent.com/4510984/105577384-4222b780-5db4-11eb-8322-5edb17889baa.png)

![image](https://user-images.githubusercontent.com/4510984/105577405-5ff01c80-5db4-11eb-9635-f6812fb9b1a2.png)

**Comment by ghost1372** [comment]
> Now, the skin changine works, but can these safe to ignore? It happens when I change skin by `hc:ComboBox`.
> 
> ```
> System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=HorizontalContentAlignment; DataItem=null; target element is 'ComboBoxItem' (Name=''); target property is 'HorizontalContentAlignment' (type 'HorizontalAlignment')
> System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=VerticalContentAlignment; DataItem=null; target element is 'ComboBoxItem' (Name=''); target property is 'VerticalContentAlignment' (type 'VerticalAlignment')
> ```
> 
> ![image](https://user-images.githubusercontent.com/4510984/105577384-4222b780-5db4-11eb-8322-5edb17889baa.png)
> 
> ![image](https://user-images.githubusercontent.com/4510984/105577405-5ff01c80-5db4-11eb-9635-f6812fb9b1a2.png)

this is combobox issue
