### ISSUE TITLE
Deigner not show handy controls

### ISSUE THREAD

**Issue by david2020** [HandyOrg/HandyControl#599]
Dear handy control powerful team,
Hi
I update vs 2019 to the latest version and use the latest version of hc
but not show any handycontrol in the XAML designer

![image](https://user-images.githubusercontent.com/4964172/103096511-622a5400-4619-11eb-97d6-58950909f7da.png)

I change the DesignTimeResources file to 

`<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="/HandyControl;Component/Themes/Theme.xaml" />
    </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>`

and add this item group to csproj file:

`<ItemGroup>
    <Page Include="Properties\DesignTimeResources.xaml"
          Condition="'$(DesignTime)'=='true' OR ('$(SolutionPath)'!='' AND Exists('$(SolutionPath)') AND '$(BuildingInsideVisualStudio)'!='true' AND '$(BuildingInsideExpressionBlend)'!='true')">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <ContainsDesignTimeResources>true</ContainsDesignTimeResources>
    </Page>
  </ItemGroup>`

Its works but the visual studio is hanged

do you have a solution?

**Comment by ghost1372** [comment]
The problem is due to Visual Studio designer It has nothing to do with HandyControl.
also If you have a problem with DesignTimeResources, remove it and use the AbsoluteUri.

Replace the `<hc:Theme/>` with:

```
<ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/SkinDefault.xaml"/>
            <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml"/>
</ResourceDictionary.MergedDictionaries>
```
