### ISSUE TITLE
Expander with Left, Right and Up expand directions?

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#600]
Unlike the native Expander control the Handycontrol expander seems to have only a Downward expansion. I want to to have a right-sidewise expansion. The following code doesn't work.  
`<expander ExpandDirection="Right"/>`.  
And sometimes I may even need a left-sidewise expansion.
Anyway I can have a sidewise expansion?

**Comment by ms-somanna** [comment]
Is this feature added yet?

**Comment by ghost1372** [comment]
> Is this feature added yet?

not yet we are a bit busy but we will add it😉

**Comment by ms-somanna** [comment]
Ok Thank you.
