### ISSUE TITLE
添加HandyControl后，使用原生样式ComboBox{x:null}则箭头会变大

### ISSUE THREAD

**Issue by asdf130162** [HandyOrg/HandyControl#605]
Demo环境：新建Framework4.5项目，只添加了HandyControl和HandyControls
添加HandyControl前
![image](https://user-images.githubusercontent.com/38516259/103252122-5f7f8400-49b6-11eb-8941-55a5a9a95d04.png)
添加HandyControl后
![image](https://user-images.githubusercontent.com/38516259/103252174-9a81b780-49b6-11eb-97fa-7bd3936a6d5b.png)

祝HandyControl越来越好

**Comment by ghost1372** [comment]
> Demo environment: New Framework 4.5 project, only added HandyControl and
> HandyControls added HandyControl
> [ ![image](https://user-images.githubusercontent.com/38516259/103252122-5f7f8400-49b6-11eb-8941-55a5a9a95d04.png) ](https://user-images.githubusercontent.com/38516259/103252122-5f7f8400-49b6-11eb-8941-55a5a9a95d04.png)
> before adding HandyControl
> ![image](https://user-images.githubusercontent.com/38516259/103252174-9a81b780-49b6-11eb-97fa-7bd3936a6d5b.png)
> 
> I wish HandyControl better and better

Are you sure you're using properly?
Because I do not see HandyControl style in your image
The combobox should look like this:
![image](https://user-images.githubusercontent.com/9213496/103348827-6d193480-4ab0-11eb-84c5-84e15052d6ae.png)

**Comment by NaBian** [comment]
请按照文档，在app中引用资源
