### ISSUE TITLE
DesignTimeResource not loading

### ISSUE THREAD

**Issue by o-coder-s** [HandyOrg/HandyControl#606]
**Description**
Static Resource suggestion is not showing.

**Screenshots**
The App.xaml file 
![image](https://user-images.githubusercontent.com/46224889/103290266-6c699b00-49e9-11eb-9c75-01b84484ccbb.png)

The showcase for the error. 
![image](https://user-images.githubusercontent.com/46224889/103290235-578d0780-49e9-11eb-9eeb-8dc275c1544a.png)

**Environment (please complete the following information):**
 - .net: [e.g. 4.6]
 - IDE [e.g. vs2017]

**Comment by ghost1372** [comment]
> **Description**
> Static Resource suggestion is not showing.
> 
> **Screenshots**
> The App.xaml file
> ![image](https://user-images.githubusercontent.com/46224889/103290266-6c699b00-49e9-11eb-9c75-01b84484ccbb.png)
> 
> The showcase for the error.
> ![image](https://user-images.githubusercontent.com/46224889/103290235-578d0780-49e9-11eb-9eeb-8dc275c1544a.png)
> 
> **Environment (please complete the following information):**
> 
> * .net: [e.g. 4.6]
> * IDE [e.g. vs2017]

First, create a new ResourceDictionary and rename it to `DesignTimeResources.xaml`, and put it in `Properties\`.

```xml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="/HandyControl;Component/Themes/Theme.xaml" />
    </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
```

Then edit your `csproj`, and add the following `ItemGroup`:

```xml
<ItemGroup>
    <Page Include="Properties\DesignTimeResources.xaml"
          Condition="'$(DesignTime)'=='true' OR ('$(SolutionPath)'!='' AND Exists('$(SolutionPath)') AND '$(BuildingInsideVisualStudio)'!='true' AND '$(BuildingInsideExpressionBlend)'!='true')">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <ContainsDesignTimeResources>true</ContainsDesignTimeResources>
    </Page>
  </ItemGroup>
  ```

  Reload the project, Intellisense now should work…

**Comment by o-coder-s** [comment]
I can't find csproj in the project nor in the file explorer

![image](https://user-images.githubusercontent.com/46224889/103292188-9fae2900-49ed-11eb-8f3a-bbeda63d0941.png)

**Comment by ghost1372** [comment]
> I can't find csproj in the project nor in the file explorer
> 
> ![image](https://user-images.githubusercontent.com/46224889/103292188-9fae2900-49ed-11eb-8f3a-bbeda63d0941.png)

1.Right-click on your project in solution explorer and select Unload Project
2.Right-click on the project (**Handy**) and click "Edit Handy.csproj". This will open up your CSPROJ file for editing.
3.After making the changes you want, save, and close the file. Right-click again on the node and choose Reload Project when done.

**Comment by DineshSolanki** [comment]
I can't get it to work even after adding itemGroup and reloading.
