### ISSUE TITLE
Spacing between controls.

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#608]
In wpf space between controls is usually controlled with margins, paddings and grid rows and columns. To make sure the space is consistent in every spot, a fixed size can be chosen that is used everywhere (or a multiple of it). It would be great if HandyControl provides a system supporting us in doing so. By default, the base value for space should be set, but this should be adjustable for horizontal and vertical space separately.

This spacing feature is already provided by [Adonis-UI](https://benruehl.github.io/adonis-ui/docs/guides/space/). Please take a look at it.

**Comment by ghost1372** [comment]
https://github.com/HandyOrg/HandyControl/pull/570

**Comment by NaBian** [comment]
closed in 9a1951eb9bf46052ef2c1a5adf91731867ed66bb
