### ISSUE TITLE
Content not showing on radio button styled as toggle button!

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#610]
I've added three RadioButtons styled as `ToggleButtonInfo` in a StackPanel as shown in code below. The problem is the content set for each RadioButton is not being shown. All I see is three blank circular toggle buttons. Any clue why the content is not being shown?

```
<Border Width="75" Height="20" Background="{DynamicResource DarkInfoBrush}" BorderThickness="1" BorderBrush="{DynamicResource SecondaryRegionBrush}" CornerRadius="10">
<StackPanel Orientation="Horizontal" Background="Transparent">
<RadioButton Style="{StaticResource ToggleButtonInfo}" hc:BorderElement.CornerRadius="15" Width="18" Height="18" hc:BorderElement.Circular="True" Content="X" Margin="1,0,0,0" FontSize="5" FontFamily="{StaticResource MaterialDesignIconsDesktop}"/>
<RadioButton Style="{StaticResource ToggleButtonInfo}" hc:BorderElement.CornerRadius="15" Width="20" Height="20" hc:BorderElement.Circular="True" Content="Y" Margin="4,0,4,0"/>
<RadioButton Style="{StaticResource ToggleButtonInfo}" hc:BorderElement.CornerRadius="15" Width="20" Height="20" hc:BorderElement.Circular="True" Content="Z" Margin="0,0,1,0"/>
</StackPanel>
</Border>
```

**Comment by ghost1372** [comment]
Because you assign the wrong style to the wrong control
`RadioButton` does not have a style called `ToggleButtonInfo`
If you want to use the `ToggleButtonInfo` style, you must use the `ToggleButton` control

https://ghost1372.github.io/handycontrol/native_controls/toggleButton/#Related-styles
https://ghost1372.github.io/handycontrol/native_controls/radioButton/

**Comment by SwaroopSomanna** [comment]
Then how do I make a radio button look like a regular button that can display a content but behave like a radio button itself.
