### ISSUE TITLE
NotifyIcon Control Custom Context Content Is Blurred on HiDPI Display

### ISSUE THREAD

**Issue by M0n7y5** [HandyOrg/HandyControl#62]
Hi, 
i have hiDPI display and i tried new Demo (version 1.5.4). The context content window seems to be blurred AKA it's not DPI aware.

![image](https://user-images.githubusercontent.com/17201053/55713144-55527080-59f0-11e9-9990-dfe1a98e2691.png)

The context menu looks fine:

![image](https://user-images.githubusercontent.com/17201053/55713311-b1b59000-59f0-11e9-8a08-bd2359b5fa3f.png)

**To Reproduce**
Just compile & run demo (version 1.5.4) and go to Notify Icon Section. You must have HiDPI monitor in order to reproduce this bug.

**Expected behavior**
Clear font render, DPI Awareness

**Environment:**
 - .net: 4.7.2
 - IDE VS 2019 CE
 - Version 1.5.4
 - OS: Windows 10 build 1809

**Comment by NaBian** [comment]
Since I don't have HiDPI monitor, it's difficult to solve this problem. I hope someone can help me.  😟

**Comment by M0n7y5** [comment]
OK ... I'll try fix it 😉

**Comment by NaBian** [comment]
@M0n7y5 hi, @DingpingZhang  helped me fix the problem. I've submitted the latest code. 😀
