### ISSUE TITLE
【控件】对话框，窗口内的弹框无法关闭

### ISSUE THREAD

**Issue by KYLEMYWORLD** [HandyOrg/HandyControl#624]
**【控件】对话框，窗口内的弹框无法关闭**
在新建的窗口中显示对话框，然后再次创建窗口，这样原窗口的对话框无法关闭

![snipaste_20210116_103642](https://user-images.githubusercontent.com/33379105/104795090-be326380-57e6-11eb-8372-f4d4ad41d7fc.png)

**Comment by ghost1372** [comment]
I tested but did not see any problem
