### ISSUE TITLE
Can not drag Sprite to another monitor

### ISSUE THREAD

**Issue by cuiliang** [HandyOrg/HandyControl#625]
![test_dragproblem](https://user-images.githubusercontent.com/1972649/104812986-23b33e00-5841-11eb-93a5-75065c43e746.gif)

**Comment by NaBian** [comment]
没有双屏，需要帮助

**Comment by cuiliang** [comment]
```
sprite._leftMax = desktopWorkingArea.Width - sprite.ActualWidth;
```
这句限制了只能在主屏上了。

**Comment by NaBian** [comment]
> ```
> sprite._leftMax = desktopWorkingArea.Width - sprite.ActualWidth;
> ```
> 
> 这句限制了只能在主屏上了。

可以的话麻烦你提个pr吧

**Comment by cuiliang** [comment]
看起来整个Current_PostProcessInput都是不必要的。
双屏或多屏的0点坐标在主屏的左上角。如果主屏在右侧，左侧的副屏会有负值x坐标；如果副屏在上面，上面的副屏会有负值Y坐标。
修改后的代码，大佬看下。
另外我比较疑惑，这个小窗口是怎么自动实现了拖拽呢？
```
using System.Windows;
using System.Windows.Input;

namespace HandyControl.Controls
{
    public sealed class Sprite : System.Windows.Window
    {
        private Sprite()
        {
            WindowStyle = WindowStyle.None;
            AllowsTransparency = true;
        }


        public static Sprite Show(object content)
        {
            var sprite = new Sprite
            {
                Content = content
            };

            sprite.Show();

            var desktopWorkingArea = SystemParameters.WorkArea;
            sprite.Left = desktopWorkingArea.Width - sprite.ActualWidth - 50;
            sprite.Top = 50 - sprite.Padding.Top;

            return sprite;
        }
    }
}
```

**Comment by NaBian** [comment]
拖拽是通过 `WindowAttach.IsDragElement` 实现的

**Comment by cuiliang** [comment]
哦哦，明白了

**Comment by NaBian** [comment]
这个控件除了拖拽，其实原计划还要添加自动停靠隐藏的功能，所以才会有 `Current_PostProcessInput` 这个方法，但是这个功能可能当时被终止了

**Comment by NaBian** [comment]
现在的行为就是：当控件被拖到边缘，一部分看不见时，需要强行移动位置使其完全显示，但是最新的代码取消了这个限制，似乎也没什么不好

**Comment by cuiliang** [comment]
靠边隐藏的话，如果靠的那个边有别的屏幕，会把要隐藏的内容显示在那个屏幕上😂 
小窗口靠边隐藏的意义不大，而且这种方式操作效率也比较低，打开窗口时间比较长。
