### ISSUE TITLE
Difference between HandyControl and HandyControls?

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#627]
Other than the fact that HandyControls includes a Persian toolkit and HandyControl does not what other differences are present between the two libraries?

**Comment by ghost1372** [comment]
@SwaroopSomanna 
- Persian Toolkit (Like date, calendar)
- Extra styles and controls
- [Extra Attributes for some controls](https://ghost1372.github.io/handycontrol/persianToolkit/#Attributes)
- Faster release of nuget
- [Helper Classes](https://ghost1372.github.io/handycontrol/persianToolkit/helpers/)
- [Extensions Method
](https://ghost1372.github.io/handycontrol/persianToolkit/extensions/)
- Updated [VSIX ](https://marketplace.visualstudio.com/items?itemName=MahdiHosseini.HandyControls) extension with the latest Nuget package + MVVM project template

You can see the list of changes [here](https://ghost1372.github.io/handycontrol/persianToolkit/)
