### ISSUE TITLE
hc:Empty issue in combobox control

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#628]
![1](https://user-images.githubusercontent.com/9213496/105047475-9f023300-5a7f-11eb-9421-349444f563ba.gif)

**Comment by NaBian** [comment]
fetch newest source code, rebuild project and try again

**Comment by ghost1372** [comment]
@NaBian The demo is based on the latest source code
There is no problem separately, but when used together, there is a problem
you can see that native combobox first time work fine but after using hc combobox, native combobox cant show empty layout
