### ISSUE TITLE
Bad Context Menu/Content Position When Tray Icon Menu is Opened

### ISSUE THREAD

**Issue by M0n7y5** [HandyOrg/HandyControl#63]
Hi, 
when i click on Notify Tray Icon, the context menu open every time in bottom-right corner. No matter where is my cursor.

**To Reproduce**
Compile & Run Demo (version 1.5.4) and go to Notify Icon section.

**Expected behavior**
Menu will open next to the cursor

**Screenshots**
![image](https://user-images.githubusercontent.com/17201053/55717933-c3039a00-59fa-11e9-8bea-c038ec83e5af.png)

![image](https://user-images.githubusercontent.com/17201053/55717945-c9921180-59fa-11e9-8e52-241441fda9b3.png)

**Environment (please complete the following information):**
 - .net: 4.7.2
 - IDE VS 2019 CE
 - Version 1.5.4
 - OS: Windows 10 1809

**Comment by NaBian** [comment]
this problem may also be caused by the api, just like #62

**Comment by NaBian** [comment]
@M0n7y5 tnx!!!!! 😆
