### ISSUE TITLE
NotifyIcon 在某些全屏游戏内切回桌面时，图标会变得逐渐模糊

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#637]
**Describe the bug**
随着切回桌面再回切游戏全屏再切回桌面的次数增多，会越来越模糊。

**To Reproduce**
~1. 运行使用 `NotifyIcon` 的程序。
2. 运行全屏的游戏，并把游戏的分辨率设置得跟桌面分辨率不一致，例如我的桌面是 1920x1080，把游戏内分辨率改为 1600x900。
3. `alt+tab` 切回桌面。
4. 切回游戏全屏。
5. 切回桌面，重复多次，会看到 `NotifyIcon` 的图标越来越模糊。~

重复切换不同的缩放级别即可。

![image](https://user-images.githubusercontent.com/4510984/106146124-45051a00-61b1-11eb-8ffb-79a1d365712e.png)

**Expected behavior**
不会变模糊，像 QQ 微信等程序一样保持图标清晰。

**Screenshots**
![image](https://user-images.githubusercontent.com/4510984/105538561-8c615580-5d2e-11eb-9420-cbc2379fee04.png)

![image](https://user-images.githubusercontent.com/4510984/105538723-cc283d00-5d2e-11eb-8bc8-a3fbbfb74220.png)

### 程序所使用的 `.ico` 文件包含的图标尺寸：

![image](https://user-images.githubusercontent.com/4510984/105539450-bb2bfb80-5d2f-11eb-8099-da4c52e9ebe0.png)

**Environment (please complete the following information):**
 - .net: `.net 5`
 - IDE `vs2019`
 - Version `3.0.0`
 - System `Win10 20H2`

**Additional context**

**Comment by NaBian** [comment]
暂时无法复现

**Comment by GF-Huang** [comment]
@NaBian 你的缩放有设置到超过 100% 吗?

![image](https://user-images.githubusercontent.com/4510984/106142746-d1f9a480-61ac-11eb-829b-8794bdfd15f6.png)

**Comment by NaBian** [comment]
你的复现步骤太复杂了，什么都不需要，只需要不停切换缩放即可复现

**Comment by GF-Huang** [comment]
好吧。😂
