### ISSUE TITLE
Cannot clear UnsafePassword in plaintext state by vm code

### ISSUE THREAD

**Issue by JeremyWu917** [HandyOrg/HandyControl#645]
**Describe the bug**
After binding `UnsafePassword` to `hc:PasswordBox`, the value of  `UnsafePassword`  cannot be cleared by backend code in _plaintext state_, but can be cleared by `ClearButton` in frontend.  And in _ciphertext state_, everything is ok.

**Expected behavior**
The `value` should be cleared regardless of whether it is in _plaintext_ or _ciphertext_ state

**Screenshots**
![issue_passwordbox_bug](https://user-images.githubusercontent.com/54832272/105671470-bfb60700-5f1d-11eb-9f5d-526020f73d23.gif)

**Environment (please complete the following information):**
 - .net: [NET 5.0]
 - IDE [VS2019 16.8.4]
 - HC Version [3.0.0]

**Additional context**
Here is the partial code
- .XAML
`
<hc:PasswordBox
                    hc:InfoElement.Placeholder="请输入密码"
                    IsSafeEnabled="False"
                    ShowClearButton="True"
                    ShowEyeButton="True"
                    UnsafePassword="{Binding Password}" />
`
- VM
`
private string _Password;
`
        `public string Password
        {
            get { return _Password; }
            set
            {
                _Password = value;
                this.RaisePropertyChanged(nameof(Password));
            }
        }
`
`
 public DelegateCommand CancelCommand { get; set; }
        private void Cancel(object parameter)
        {
            Password = "";
        }
`

**Comment by JeremyWu917** [comment]
@ghost1372 
pls help to check and advise
many thx

**Comment by ghost1372** [comment]
@JeremyWu917 
I think it is a binding problem, You can use the internal command to clear
```
<Button Content="clear" Command="hc:ControlCommands.Clear" CommandTarget="{Binding ElementName=xx}"/>
        <hc:PasswordBox Name="xx" hc:InfoElement.Placeholder="请输入密码" IsSafeEnabled="False" ShowClearButton="True" ShowEyeButton="True" UnsafePassword="{Binding Password}" />
```

**Comment by JeremyWu917** [comment]
@ghost1372 

Thanks for your reply.
It's works for me if I use the the internal command to clear, but in this case I wanna clear all params not just one element, and most of the time there is more than one element to clear. 
And it make no sence cause other controls with the same binding method do not have this problem.
Thanks

**Comment by JeremyWu917** [comment]
Hi @NaBian @ghost1372 

There is still a concern not about `Clear` , it is `Set value`, cause when I set  `ShowEyeButton` as `true`,  I cannot set `UnsafePassword` in vm, means `FrameworkPropertyMetadataOptions.BindsTwoWayByDefault` not work any more.
Please review, thanks.

BTW, I declare `Password` in vm as below

       `private string _Password;
        public string Password
        {
            get { return _Password; }
            set
            {
                _Password = value;
                this.RaisePropertyChanged(nameof(Password));
            }
        }`

**Comment by NaBian** [comment]
i can not reproduce your problem, can you provide a demo.

**Comment by JeremyWu917** [comment]
@NaBian 

Thanks for your replay.

[Here](https://github.com/JeremyWu917/HandyControl/tree/check-password-box-sample/src/Sample.WPF.Demo) is the demo.
![issue_passwordbox_sample](https://user-images.githubusercontent.com/54832272/106430835-5860ff80-64a7-11eb-8f95-e27bfefaebc6.gif)

> I cannot copy value from param one to param two when passwordbox's eyes on, means I cannot perform a `set` property.

Thanks

**Comment by NaBian** [comment]
还是无法复现
![demo](https://user-images.githubusercontent.com/17383395/106482351-553a3380-64e8-11eb-80af-08cb99bef00f.gif)
