### ISSUE TITLE
What happened to the "Switching Configurator"?

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#666]
Some time ago I saw a `SwitchingConfigurator` in the list of controls of this GitHub project page. Now it's gone. I really wanted the `SwitchingConfigurator` and is also helpful to others as it can be used to switch app language and theme. Can you please tell me what happened to it?

**Comment by ghost1372** [comment]
Nothing, the image has been removed from the page, still available in the demo

**Comment by ms-somanna** [comment]
It's very useful. Can you please plan on adding it to future versions?

**Comment by ghost1372** [comment]
> It's very useful. Can you please plan on adding it to future versions?

This is just a simple pop-up
https://github.com/HandyOrg/HandyControl/blob/83a44aa6768270335af76518ce75e009be0befbc/src/Shared/HandyControlDemo_Shared/UserControl/Main/NonClientAreaContent.xaml#L118

**Comment by ms-somanna** [comment]
> > It's very useful. Can you please plan on adding it to future versions?
> 
> This is just a simple pop-up
> https://github.com/HandyOrg/HandyControl/blob/83a44aa6768270335af76518ce75e009be0befbc/src/Shared/HandyControlDemo_Shared/UserControl/Main/NonClientAreaContent.xaml#L118
> 

Oh ok
