### ISSUE TITLE
Accent color doesn't change when theme changes from System Theme to HandyControl light or dark theme.

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#668]
When I switch the app theme from HandyControl light or dark theme to System Theme the accent color in my app changes to match the system accent color. But when I change back the app theme from System Theme to HandyControl light or dark theme the accent color remains the same. I mean the accent color is set to System Accent color and not the default accent color for HandyControl light or dark theme.

Below is the code I'm using to switch themes with the click of radio buttons:  
```
private void RadioButtonThemeLight_Click(object sender, System.Windows.RoutedEventArgs e)
        {
            ThemeResources.Current.UsingSystemTheme = false;
            ThemeManager.Current.ApplicationTheme = ApplicationTheme.Light;
        }
        
	private void RadioButtonThemeDark_Click(object sender, System.Windows.RoutedEventArgs e)
        {
            ThemeResources.Current.UsingSystemTheme = false;
            ThemeManager.Current.ApplicationTheme = ApplicationTheme.Dark;
        }
	
	private void RadioButtonThemeWinDefault_Click(object sender, System.Windows.RoutedEventArgs e)
        {
            ThemeResources.Current.UsingSystemTheme = true;
            ThemeManager.Current.ApplicationTheme = ThemeManager.GetSystemTheme();
        }
```

**Comment by ghost1372** [comment]
Thanks for the report, I will solve this problem

**Comment by ghost1372** [comment]
Fixed in https://github.com/ghost1372/HandyControls/commit/91804c248c4de940e2abb045367806a1a98c034f

1. you can enable or disable UsingSystemTheme from ThemeManager/ThemeResources
2. you no longer need to set the ApplicationTheme after enabling UsingSystemTheme.

> ThemeManager.Current.ApplicationTheme = ThemeManager.GetSystemTheme();

 This is done automatically.
![2](https://user-images.githubusercontent.com/9213496/107220049-23185c80-6a27-11eb-82af-8f320f84da04.gif)

**Comment by ms-somanna** [comment]
> Fixed in https://github.com/ghost1372/HandyControls/commit/91804c248c4de940e2abb045367806a1a98c034f
> 
> 1. you can enable or disable UsingSystemTheme from ThemeManager/ThemeResources
> 2. you no longer need to set the ApplicationTheme after enabling UsingSystemTheme.
> 
> > ThemeManager.Current.ApplicationTheme = ThemeManager.GetSystemTheme();
> 
>  This is done automatically.
> ![2](https://user-images.githubusercontent.com/9213496/107220049-23185c80-6a27-11eb-82af-8f320f84da04.gif)
> 

If I don't use `ThemeManager.Current.ApplicationTheme = ThemeManager.GetSystemTheme();` my application theme won't switch to system theme when I check the "Win Default theme" RadioButton. That's could be bug. Please see the below images.  
    
----------------------------------------------------  
Windows light theme with app theme set to dark. Works well. 
![IMG_20210209_210338159.jpg](https://user-images.githubusercontent.com/32904377/107387171-92bb4400-6b1a-11eb-992b-4d553fd22b67.jpg)  

----------------------------------------------------  
Windows light theme with app theme set to Windows Default. App theme still dark and not switching to light as expected.
![IMG_20210209_210349289.jpg](https://user-images.githubusercontent.com/32904377/107387537-ecbc0980-6b1a-11eb-8582-c765c1eaede0.jpg)

**Comment by ghost1372** [comment]
@SwaroopSomanna 
I know, I said from now this will be done automatically and there will be no need to write additional code😅
The image I posted showed the modified Commit function.
In version 3.1.0 you wrote the correct code, but for the next version this process has been modified😉

**Comment by ms-somanna** [comment]
Another issue,
When a custom accent color is set and afterwards when the default HandyControl light or dark theme is set the accent color remains the same as custom accent color.

**Comment by ms-somanna** [comment]
If I can get the corresponding accent color of default light and dark themes I may be able to programmatically set that accent color for the selected default light or dark theme.
But how do I get the accent color built-into default light and dark theme?

**Comment by ghost1372** [comment]
> Another issue,
> When a custom accent color is set and afterwards when the default HandyControl light or dark theme is set the accent color remains the same as custom accent color.

this is not issue, its normal
Changing the theme does not change the accentcolor

**Comment by ghost1372** [comment]
> If I can get the corresponding accent color of default light and dark themes I may be able to programmatically set the that accent color for the selected default light or dark theme.
> But how do I get the accent color for the default light and dark theme?

There is no specific method for this situation
You can use the following color code, which is the default accent color
`#326cf3`

**Comment by SwaroopSomanna** [comment]
> > Another issue,
> > When a custom accent color is set and afterwards when the default HandyControl light or dark theme is set the accent color remains the same as custom accent color.
> 
> this is not issue, its normal
> Changing the theme does not change the accentcolor

Ok. Please see my previous comment. I want to get the accent color of the default HandyControl themes.

**Comment by ghost1372** [comment]
@SwaroopSomanna 
If it is possible to implement it, I provide the possibility that Return the accentcolor to its default value by setting accentColor to null

**Comment by ms-somanna** [comment]
> @SwaroopSomanna 
> If it is possible to implement it, I provide the possibility that Return the accentcolor to its default value by setting accentColor to null 
> 

Setting accent color to null is working. Thanks.

**Comment by ghost1372** [comment]
> > @SwaroopSomanna
> > If it is possible to implement it, I provide the possibility that Return the accentcolor to its default value by setting accentColor to null
> 
> Setting accent color to null is working. Thanks.

😂😂 it's interesting 
I have to add to the documentation
