### ISSUE TITLE
Button的Padding属性效果异常（Button Padding Error）

### ISSUE THREAD

**Issue by MisakaCirno** [HandyOrg/HandyControl#669]
Button的Padding属性，在横方向上正常向外扩展，但是纵方向上不会扩展按钮的尺寸，而是会减小文本上下的距离。

举个栗子:
![HandyButton](https://user-images.githubusercontent.com/14026438/107344160-1ebe7300-6afd-11eb-97ff-93e356324788.png)
![HandyButtonPadding](https://user-images.githubusercontent.com/14026438/107344197-2716ae00-6afd-11eb-8d90-3899008a63e2.png)

代码为：
`<Button Content="test text" HorizontalAlignment="Center" VerticalAlignment="Center" Padding="80,10"/>`
其中，”80“的效果是正常的，但是”10“的效果是不对的。

==================================================
Translated by translation software:
The Padding property of the Button, which extends normally in the horizontal direction, does not increase the size of the Button in the vertical direction, but instead reduces the distance between the top and bottom of the text.）

For example:
![HandyButton](https://user-images.githubusercontent.com/14026438/107344160-1ebe7300-6afd-11eb-97ff-93e356324788.png)
![HandyButtonPadding](https://user-images.githubusercontent.com/14026438/107344197-2716ae00-6afd-11eb-8d90-3899008a63e2.png)

Code is:
`<Button Content="test text" HorizontalAlignment="Center" VerticalAlignment="Center" Padding="80,10"/>`
Among them, the "80" effect is normal, but the "10" effect is wrong.

**Comment by NaBian** [comment]
height = auto

**Comment by MisakaCirno** [comment]
> 
> 
> height = auto

试了一下，还是会影响文本的正常显示而不会扩展Button的高度

**Comment by NaBian** [comment]
![1](https://user-images.githubusercontent.com/17383395/107346217-6cd47600-6aff-11eb-9a2f-edba06cd7e4a.png)

**Comment by MisakaCirno** [comment]
> 
> 
> ![1](https://user-images.githubusercontent.com/17383395/107346217-6cd47600-6aff-11eb-9a2f-edba06cd7e4a.png)

我尝试了一下，好像和框架有关系，在NET Framework 4.7.2中，添加了Height=Auto后就正常了。但是在NET5里就没有效果。

**Comment by NaBian** [comment]
![2](https://user-images.githubusercontent.com/17383395/107347561-e7ea5c00-6b00-11eb-946e-7a050df8359f.png)

**Comment by MisakaCirno** [comment]
> 
> 
> ![2](https://user-images.githubusercontent.com/17383395/107347561-e7ea5c00-6b00-11eb-946e-7a050df8359f.png)

我又试了几次，知道怎么回事了，加了Auto之后在设计器里面的样式是不会变的，但是运行时的显示效果是正常的。
已经解决问题了，非常感谢！
不过还是希望如果可以的话，能让在设计器中显示的效果也是正常的。

**Comment by NaBian** [comment]
这是设计器问题，可以向微软反馈

**Comment by MisakaCirno** [comment]
> 
> 
> 这是设计器问题，可以向微软反馈

了解了，多谢指点！

**Comment by MisakaCirno** [comment]
> 
> 
> 这是设计器问题，可以向微软反馈

我又花了点时间，大概知道原因了：
ButtonBaseStyle继承于ButtonBaseBaseStyle，在ButtonBaseBaseStyle中有`<Setter Property="Height" Value="{StaticResource DefaultControlHeight}"/>`，其中DefaultControlHeight的默认高度为30，这就限制了Button的高度。

即便是在基于ButtonBaseStyle的Style添加了`<Setter Property="Height" Value="Auto"/>`，在设计器中也不会直接显示出来效果，只有运行时才能显示出Auto的效果，我估计设计器的原理可能是优先找确定数值的显示。

由于对于XAML这边的理解并不深入，除了直接从BaseStyle开始继承然后写一个自定义的Button以外，暂时没有想到什么太好的办法能解决，姑且先继续研究研究吧。
