### ISSUE TITLE
Error trying to edit the template of ColorPicker

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#670]
Im trying to edit the template of a ColorPicker in the design view by following the below steps:  
`Right click on ColorPicker > Edit Template > Edit a copy > (default selections) > OK.`  
Once I click the OK button Im getting an error stated as - "Copy Template Failed".

**Comment by ghost1372** [comment]
everything work fine
mybe your vs is corrupted
![2](https://user-images.githubusercontent.com/9213496/108251480-b1e65100-716c-11eb-9127-6a7b5dd55f0d.gif)

**Comment by ms-somanna** [comment]
> everything work fine
> mybe your vs is corrupted
> ![2](https://user-images.githubusercontent.com/9213496/108251480-b1e65100-716c-11eb-9127-6a7b5dd55f0d.gif)
> 

Ok I'll see.
