### ISSUE TITLE
How to set BorderElement.CornerRadius in control defination in Code-behind?

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#672]
Im creating a new RadioButton control who's CornerRadius needs to be set in defination like this:  
```
RadioButton rb = new RadioButton
{
Background = new SolidColorBrush(...),  
<Here I want to define corner radius>
};
```

**Comment by ghost1372** [comment]
> Im creating a new RadioButton control who's CornerRadius needs to be set in defination like this:
> 
> ```
> RadioButton rb = new RadioButton
> {
> Background = new SolidColorBrush(...),  
> <Here I want to define corner radius>
> };
> ```
**BorderElement.CornerRadius** is attached property so you cant use in this way, you have to do this:

`BorderElement.SetCornerRadius(rb, new CornerRadius(10, 10, 10, 10));`
