### ISSUE TITLE
"SelectedColorChanged" event is firing multiple times when the Confirm button is clicked once!

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#673]
I'm using a ColorPicker to select color. I've added some code to the `SelectedColorChanged` event and I've noticed the code within the event is being executed multiple times when I click on the ColorPicker's Confirm button once. This should not be happening as I've not put any loops in the code. Please see.  

**Edit:**
This is what is actually happening:  
The event is fired once when I click the button for the first time, twice the second time, thrice the third time and so on.

**Comment by ghost1372** [comment]
@NaBian 
also The name of the event is not correct with what it does. I suggest the events are as follows:
**SelectedColorChanged** = Call every time the color changes
**ColorPickerConfirmed** = Call when user click on Confirm Button

SelectedColorChanged Event is currently called when confirm button is clicked that contradicts its name.

**Comment by SwaroopSomanna** [comment]
Any progress?

**Comment by ms-somanna** [comment]
Any progress?

**Comment by ghost1372** [comment]
@SwaroopSomanna  i added events in #720

**Comment by NaBian** [comment]
closed in 4db1c8a
