### ISSUE TITLE
SideMenu'Binding not work

### ISSUE THREAD

**Issue by BigHeadDev** [HandyOrg/HandyControl#674]
**Describe the bug**
通过网络获取的菜单列表，使用SideMenu.ItemSource进行绑定，但是界面没有任何反应。如果换成Menu就没问题
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - .net: [e.g. 4.6.2]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by ghost1372** [comment]
duplicate
https://github.com/HandyOrg/HandyControl/issues/335
