### ISSUE TITLE
Solid style RadioButton Geometry fill color doesnt change to white when checked.

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#676]
What it is like:  
![rb1.png](https://user-images.githubusercontent.com/32904377/108201502-eb579600-7145-11eb-87b3-d04961cd7683.png)  

What it should be like:  
![rb2.png](https://user-images.githubusercontent.com/32904377/108201553-02968380-7146-11eb-9dd1-6ff290a574e4.png)

Reasons:  
1. The geometry path fill color being black doesn't look good with a blue background.   
2. The geometry path and text both should have the same color (white).

**Comment by ghost1372** [comment]
@SwaroopSomanna thank you for report
i fixed in pr #677
