### ISSUE TITLE
自定义非客户端区域窗口与OxyPlot一起使用时出现异常

### ISSUE THREAD

**Issue by s77zz** [HandyOrg/HandyControl#68]
如果使用了Style = "{StaticResource WindowWin10}" ，图表的坐标网格绘制出现错位

**To Reproduce**
1. 在APP.XAML中引用了

ResourceDictionary>
                    ResourceDictionary.MergedDictionaries>
                    ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml"/>
                    </ResourceDictionary.MergedDictionaries>
                </ResourceDictionary>

2. 引用OxyPlot绘制一张普通线性图
private static PlotModel CreatePlotModel2(bool isSmooth = false)
        {
            var model = new PlotModel();

            model.Axes.Clear();

            var verticalAxis = new LinearAxis { Position = AxisPosition.Left, IsZoomEnabled = false, IsPanEnabled = false };
            verticalAxis.Title = "温度值";
            verticalAxis.Unit = "℃";
            verticalAxis.TickStyle = TickStyle.Outside;
            verticalAxis.MajorGridlineThickness = 1;
            verticalAxis.MinorGridlineThickness = 1;

            verticalAxis.MajorGridlineStyle = LineStyle.Solid;
            verticalAxis.MinorGridlineStyle = LineStyle.Dash;
            verticalAxis.MajorStep = 100;
            verticalAxis.MinorStep = 25;

            model.Axes.Add(verticalAxis);

            var horizontalAxis = (new LinearAxis { Position = AxisPosition.Bottom, IsZoomEnabled = false, IsPanEnabled = false });
            horizontalAxis.Title = "时间";
            horizontalAxis.Unit = "秒";
            horizontalAxis.TickStyle = TickStyle.Outside;
            horizontalAxis.MajorGridlineStyle = LineStyle.Solid;
            horizontalAxis.MinorGridlineStyle = LineStyle.Dash;
            horizontalAxis.MajorStep = 1;
            horizontalAxis.MinorStep = 0.25;
            model.Axes.Add(horizontalAxis);

            var s1 = new LineSeries
            {
                Title = "LineSeries1",
                Color = OxyColors.Red,
                MarkerType = MarkerType.Circle,
                MarkerSize = 6,
                MarkerStroke = OxyColors.White,
                MarkerFill = OxyColors.Red,
                MarkerStrokeThickness = 1.5,
                MarkerResolution = 1,

                Smooth = isSmooth,
                CanTrackerInterpolatePoints = true,

            };

            s1.Points.Add(new DataPoint(1, 380));
            s1.Points.Add(new DataPoint(2, 480));
            s1.Points.Add(new DataPoint(3, 380));
            s1.Points.Add(new DataPoint(4, 380));
            s1.Points.Add(new DataPoint(5, 380));
            s1.Points.Add(new DataPoint(6, 380));
            s1.Points.Add(new DataPoint(7, 380));
            s1.Points.Add(new DataPoint(8, 380));
            s1.Points.Add(new DataPoint(9, 380));

            model.Series.Add(s1);

            return model;
            
        }
在MainWindow.xaml:
        <oxy:PlotView Grid.Row="1"  Model="{Binding Model}" SnapsToDevicePixels="True"/>

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/20233712/56016312-64a62680-5d2e-11e9-9200-310e92763919.png)

**Environment (please complete the following information):**
 - .net: [e.g. 4.0.0]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by NaBian** [comment]
我觉得很有可能是OxyPlot的锅 😀
