### ISSUE TITLE
How to add an `IconElement.Geometry` to a TabItem?

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#686]
How to add `IconElement.Geometry` to a TabItem header?   
I found a [link](https://hosseini.ninja/handycontrol/extend_controls/window/handycontrol/extend_controls/tabControl/index.html)   by searching for "IconElement" in the website `hosseini.ninja/handycontrol` that might explain how to add icons to tabitems. But the link is broken.

**Comment by ghost1372** [comment]
@SwaroopSomanna  where you found this link?
you should remove `window/handycontrol/extend_controls/` from link

https://hosseini.ninja/handycontrol/extend_controls/window/handycontrol/extend_controls/tabControl/index.html

change to

https://hosseini.ninja/handycontrol/extend_controls/tabControl/index.html

**Comment by ms-somanna** [comment]
> @SwaroopSomanna  where you found this link?
> you should remove `window/handycontrol/extend_controls/` from link
> 
> https://hosseini.ninja/handycontrol/extend_controls/window/handycontrol/extend_controls/tabControl/index.html
> 
> change to
> 
> https://hosseini.ninja/handycontrol/extend_controls/tabControl/index.html
> 

I got that link by searching for IconElement in the search bar in your website and clicking on the TabControl option. See below image.![Screenshot_20210219-110918.png](https://user-images.githubusercontent.com/32904377/108462663-04c22480-72a3-11eb-8cb8-bb30da6c81a9.png)

**Comment by ghost1372** [comment]
thank you @SwaroopSomanna 
seems search function broken. i will try to fix it

**Comment by ghost1372** [comment]
@SwaroopSomanna  i fixed broken search😉
