### ISSUE TITLE
Unable to Close window using CloseWindow command.

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#687]
I'm trying to close the current window with the click of a button using the below xaml.  
`<Button Command="hc: ControlCommands.CloseWindow"/>`  
But it's not working. The window does not close when I click on the button.  

Ref: https://hosseini.ninja/handycontrol/interactivity/commands/

**Comment by ghost1372** [comment]
> I'm trying to close the current window with the click of a button using the below xaml.
> `<Button Command="hc: ControlCommands.CloseWindow"/>`
> But it's not working. The window does not close when I click on the button.
> 
> Ref: https://hosseini.ninja/handycontrol/interactivity/commands/

`hc: ControlCommands.CloseWindow` Does not work on Windows
See example here
https://hosseini.ninja/handycontrol/extend_controls/dialog/#Basic-usage

**Comment by ghost1372** [comment]
@SwaroopSomanna 
use like this:
`Command="hc:ControlCommands.CloseWindow" CommandParameter="{Binding RelativeSource={RelativeSource Self}}" `
i will update docs
