### ISSUE TITLE
ToggleButton Icon disappears when ToggleButton is checked.

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#694]
![20210227_134501.gif](https://user-images.githubusercontent.com/32904377/109381731-0e323900-7902-11eb-8c6f-2513f9bbc98f.gif)
  
**Control:** ToggleButton.  

**Style:** ToggleButtonIcon.  

**Issue:** ToggleButton icon disappears when button is checked and appears back when unchecked.  

**Cause:** Probably when the ToggleButton is checked the border of the ToggleButton becomes thicker causing the IconElement geometry to disappear.

**Workaround:** Decrease the width and height of the IconElement using `hc:IconElement.Width` and `hc:IconElement.Height`

**Comment by ghost1372** [comment]
@SwaroopSomanna 
A sample code can be useful
Use the following Attached Property in ToggleButton to see if the problem is resolved
`IconSwitchElement.GeometrySelected={Your Icon} IconSwitchElement.Geometry={Your Icon}`

**Comment by NaBian** [comment]
> @SwaroopSomanna
> A sample code can be useful
> Use the following Attached Property in ToggleButton to see if the problem is resolved
> `IconSwitchElement.GeometrySelected={Your Icon} IconSwitchElement.Geometry={Your Icon}`

@SwaroopSomanna Is there any feedback?

**Comment by ms-somanna** [comment]
> > @SwaroopSomanna
> > A sample code can be useful
> > Use the following Attached Property in ToggleButton to see if the problem is resolved
> > `IconSwitchElement.GeometrySelected={Your Icon} IconSwitchElement.Geometry={Your Icon}`
> 
> @SwaroopSomanna Is there any feedback?

Yes @ghost1372 's solution is working for me.
