### ISSUE TITLE
HandyControls Change ThemeManager.ApplicationTheme not effects NotifyIcon context menu

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#700]
![image](https://user-images.githubusercontent.com/4510984/109628415-af78f380-7b7d-11eb-9fdf-4f214ae24a5c.png)

**Reproduce**
1. Start app, then click the notify icon to show context menu.
2. Change theme at runtime `ThemeManager.Current.ApplicationTheme = XXX`.
3. Click the notify icon to show context menu, its theme not change.

**Environment (please complete the following information):**
 - .net: 5
 - IDE vs2019
 - Version HandyControls 3.1.1

**Additional context**

**Comment by ghost1372** [comment]
Thank you @GF-Huang 
I tested and there is no problem in **ContextContent** mode, but there is a problem in **ContextMenu** Mode.
I will try to solve the problem

**Comment by GF-Huang** [comment]
BTW, why not open the issues or discussions feature of HandyControls repository?

**Comment by ghost1372** [comment]
@GF-Huang  I opened it 12 days ago😁
https://github.com/ghost1372/HandyControls/issues

**Comment by ghost1372** [comment]
@GF-Huang i fixed this bug😁 
I released a new version on Nuget yesterday, but unfortunately I fixed this bug today, So this fix will be available in the next version, which will be at least a month away
Therefore, you can use the following solution to solve the problem until the next version is released

set a name for ContextMenu:
```
<hc:NotifyIcon.ContextMenu>
    <ContextMenu Name="context">
        
    </ContextMenu>
</hc:NotifyIcon.ContextMenu>
```

Create ActualApplicationThemeChanged event:
```
public MainWindow()
        {
            InitializeComponent();
            ThemeManager.Current.ActualApplicationThemeChanged += ActualApplicationThemeChanged;
        }
```
and finally set the context theme:
```
private void ActualApplicationThemeChanged(ThemeManager sender, object args)
        {
            if (sender.ApplicationTheme == ApplicationTheme.Light)
            {
                ThemeManager.SetRequestedTheme(context, ElementTheme.Light);
            }
            else
            {
                ThemeManager.SetRequestedTheme(context, ElementTheme.Dark);
            }
        }
```

**Comment by GF-Huang** [comment]
Great! Thank you!
