### ISSUE TITLE
预览滑块预览位置会超出设定的最小值

### ISSUE THREAD

**Issue by YJammak** [HandyOrg/HandyControl#726]
将PreviewSlider的Minimum设置为100的话，鼠标移到最小端会小于100

**Comment by NaBian** [comment]
closed in 69057c70

**Comment by ghost1372** [comment]
> closed in [69057c7](https://github.com/HandyOrg/HandyControl/commit/69057c70788316d407e052d2f8439dbf1c497cee)

closed in https://github.com/HandyOrg/HandyControl/commit/c3a5ec7bab328b444168dc60c09d66c47d7b71ca 😅

**Comment by NaBian** [comment]
> > closed in [69057c7](https://github.com/HandyOrg/HandyControl/commit/69057c70788316d407e052d2f8439dbf1c497cee)
> 
> closed in [c3a5ec7](https://github.com/HandyOrg/HandyControl/commit/c3a5ec7bab328b444168dc60c09d66c47d7b71ca) 😅

ok
