### ISSUE TITLE
TabControl: context menu is not in english

### ISSUE THREAD

**Issue by deviloper** [HandyOrg/HandyControl#735]
Describe the bug
TabControl has a default context menu which is not in English as declared default.

To Reproduce

    Add HandyControls as NuGet package without specifying a language pack
    Instantiate a TabControl with a TabItem
    Richt-click on the tab header
    Here you can see a menu which is not in the default language

Expected behavior
I expected to see a context menu with commmands in english

Screenshots
![immagine](https://user-images.githubusercontent.com/5602328/111915547-303d5800-8a77-11eb-989a-95f3a22ef32b.png)

Environment (please complete the following information):

    .net 5
    Visual Studio 2019
    HandyControls 3.2.0

**Comment by ghost1372** [comment]
This is original repo and default language is chinese
