### ISSUE TITLE
在Unity4.0.1中报以下错误，MaterialDesignThemes与 HandyControl中冲突了

### ISSUE THREAD

**Issue by longa30** [HandyOrg/HandyControl#74]
public void Register()
        {
            //自动注册
            container.RegisterTypes(AllClasses.FromLoadedAssemblies(), WithMappings.FromAllInterfaces, WithName.TypeName, WithLifetime.PerResolve);
        }

Microsoft.Practices.Unity.DuplicateTypeMappingException:“An attempt to override an existing mapping was detected for type System.Windows.Media.Composition.DUCE+IResource with name "TimePicker", currently mapped to type MaterialDesignThemes.Wpf.TimePicker, to type HandyControl.Controls.TimePicker.”

**Comment by NaBian** [comment]
@longa30 对于如何在Unity4.0.1中解决同名类冲突的问题已经超过了本项目issue的讨论范围，所以我关闭了此issue。
