### ISSUE TITLE
HandyControl.Controls.MessageBox在非ui线程上使用死锁

### ISSUE THREAD

**Issue by tiger-wwz** [HandyOrg/HandyControl#746]
如果我ui线程在等待一个task，而这个task里面使用了HandyControl.Controls.MessageBox，就会死锁

**Comment by cuiliang** [comment]
界面元素不能在非UI线程上访问。 用Dispatcher.Invoke之类的方法再封装一下。

**Comment by GF-Huang** [comment]
任何 UI 组件不能在**非UI线程**调用这是常识。
