### ISSUE TITLE
Shortcut keys need to be pressed twice to fire MessageBox Button execute result.

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#747]
**Describe the bug**
So I have a HandyControl message box that has three buttons. I've added a keyboard shortcut to each button using the underscore character (_) in the button content string. See code below.  

```
private void MainWindow_Closing(object sender, System.ComponentModel.CancelEventArgs e)
         {
            if(AllOpenTraysAreSaved == false)
            {
                var response = MessageBox.Show(new MessageBoxInfo
                {
                    Message = "One or more projects have not been saved!\nWhat do you want to do?",
                    Caption = ProductName,
                    Button = MessageBoxButton.YesNoCancel,
                    YesContent = "_Save",
                    CancelContent = "_Cancel",
                    NoContent = "_Don't Save",
                    DefaultResult = MessageBoxResult.Yes,
                    IconBrushKey = ResourceToken.WarningBrush,
                    IconKey = ResourceToken.WarningGeometry
                });
                
                
                if(response == MessageBoxResult.Cancel)
                {
                    e.Cancel = true;
                }
                else if (response == MessageBoxResult.Yes)
                {
                    //Save logic here. Not implemented.
                }
                else
                {
                    Application.Current.Shutdown();
                }
            }
        }
```

**Steps to reproduce the behavior:**
1. Implement the above code in your app.
2. Run your application.
3. Execute the above code to show the message box.
4. When the message box has shown up, click the 'Alt' key and click(once) on the shortcut key assigned to any of the message box buttons. You'll notice the button's code is not executed and hear a beep sound.
5. Click on the same key again and you'll notice the button's code gets executed.

**Expected behavior**
The button's code must get executed when the associated shortcut key is pressed just once.

**Environments**
 - IDE: vs2019 latest version.
 - HandyControls Version: 3.3.0
 - HandyControl Version: 3.1.0

**Comment by NaBian** [comment]
YesContent? Is that a api in HC ?

**Comment by ms-somanna** [comment]
> YesContent? Is that a api in HC ?

Yes.

**Comment by ghost1372** [comment]
@SwaroopSomanna your are using unofficial version **YesContent** isnt available in official version

**Comment by ms-somanna** [comment]
> @SwaroopSomanna your are using unofficial version **YesContent** isnt available in official version

Oh that's right. So should I move this issue to the HandyControls repository?

**Comment by ghost1372** [comment]
I have no idea what is happening Maybe Nabian can help

**Comment by NaBian** [comment]
> > @SwaroopSomanna your are using unofficial version **YesContent** isnt available in official version
> 
> Oh that's right. So should I move this issue to the HandyControls repository?

yes 😆
