### ISSUE TITLE
加入qq群可以不收费吗 哈哈哈哈

### ISSUE THREAD

**Issue by iamgongjun** [HandyOrg/HandyControl#750]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - .net: [e.g. 4.6.2]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by cuiliang** [comment]
大佬群，要收费才能加的😁，除非是大佬级别的人物，需要自我证明一下。

**Comment by NaBian** [comment]
可以
