### ISSUE TITLE
Provides an API for switching themes

### ISSUE THREAD

**Issue by asdf130162** [HandyOrg/HandyControl#751]
I refer to HCdemo for implementation,
The effect is not satisfactory.
My level is limited,
Hope to provide an API to switch between dark and default,
The version I use is HandyControl 3.1.0.
Thanks,Wish HC better and better.

**Comment by ghost1372** [comment]
did you read [docs](https://hosseini.ninja/handycontrol/theme/handyControl) and [here](https://hosseini.ninja/handycontrol/theme/)?

**Comment by asdf130162** [comment]
> did you read [docs](https://hosseini.ninja/handycontrol/theme/handyControl) and [here](https://hosseini.ninja/handycontrol/theme/)?

Thank you. My problem has been solved
