### ISSUE TITLE
[Feature request]UniformSpacingGrid: Grid with global cell spacing

### ISSUE THREAD

**Issue by cuiliang** [HandyOrg/HandyControl#755]
当构建表单类型的界面时，在行与行之间添加空白需要大量的处理。

<img src="https://user-images.githubusercontent.com/1972649/112921289-15d14180-913d-11eb-8d7c-9a590363cb20.png" width="300" height="Auto">

如果可以方便的从Grid级别设置行间距，就比较美妙了。

另外这个Grid里要调整行的顺序实在是太麻烦了，如果能像html那样，不用写Grid.Row Grid.Col就好了，根据控件所在的位置自动布局。

**Comment by ghost1372** [comment]
We have a grid control that may meet your needs. Have you tried it?
https://hosseini.ninja/handycontrol/extend_controls/grid/

**Comment by cuiliang** [comment]
@ghost1372 Thank you. Seems right choice.
