### ISSUE TITLE
Scrollable Tabs in TabControl

### ISSUE THREAD

**Issue by M0n7y5** [HandyOrg/HandyControl#76]
Hi,
can you make tabs in TabControl scrollable ? Like i Firefox? :)

**Comment by ghost1372** [comment]
What do you mean scrollable?
You can put scrollviewer in tabcontrol

**Comment by M0n7y5** [comment]
Oh sorry ... I mean **Tabs** in Tab Control

**Comment by M0n7y5** [comment]
For example like this:

![7U8AQXMFc6](https://user-images.githubusercontent.com/17201053/57133079-00f9a100-6da2-11e9-87f5-de2f73b8b673.gif)

**Comment by ghost1372** [comment]
Handycontrol support it You can use tabcontrol control, download demo and check it

**Comment by M0n7y5** [comment]
I already check it ... There is no scrolling Tabs option  in TabControl ...

**Comment by ghost1372** [comment]
Do not like this mode?😅
![Untitled](https://user-images.githubusercontent.com/9213496/57138942-2fd73d80-6dc9-11e9-9f8b-4ea96e9935e7.png)

**Comment by M0n7y5** [comment]
Nope ... This is not scrolling in the first place. 😅 That's just a combobox with a list of Tabs 🤔 I'll try do it by myself then ...

**Comment by M0n7y5** [comment]
So ... I am back with some progress ... This is what i want ... It's not done yet, but once i finish this, i'll make pull request 😉

P.S. I have touchpad and for some reason scrolling is quite hard ... Maybe there is a bug in Scrollviewer control ... 

![sel6LtWKgU](https://user-images.githubusercontent.com/17201053/57294473-18010180-70c8-11e9-88eb-d03e1748aa9d.gif)

**Comment by ghost1372** [comment]
@M0n7y5  tnx its very good
i can test it if you want

**Comment by M0n7y5** [comment]
That would be helpful ... I just finish something and push it to my forked repo ...

**Comment by M0n7y5** [comment]
@ghost1372 ok ... It's ready ... Also i made pull request 😉

**Comment by ghost1372** [comment]
@M0n7y5  tnx i will check it now

**Comment by ghost1372** [comment]
@M0n7y5  i tested it and everything is ok, i used touchpad and mouse and in both i dont see any bug

**Comment by M0n7y5** [comment]
@ghost1372 Yes ... The bug is not there anymore, because i fix it. See #80 😊

**Comment by ghost1372** [comment]
@M0n7y5  😅 tnx bro

**Comment by NaBian** [comment]
@M0n7y5 @ghost1372 Thank you. I'll take the time to read the code. 😄
