### ISSUE TITLE
<hc:Empty broken and not working

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#763]
@NaBian  The following controls should show <hc:Empty view if it is empty, but it is not displayed

- ListBox
- DataGrid
- TreeView
- ComboBox
- CheckComboBox
- ListView

<hc:Empty seems to be broken

also this code not work

```
<hc:ToggleBlock IsChecked="{Binding ElementName=lst, Path=HasItems, Mode=OneWay}" VerticalContentAlignment="Stretch" HorizontalContentAlignment="Stretch">
    <hc:ToggleBlock.CheckedContent>
        <ListBox Name="lst"/>
    </hc:ToggleBlock.CheckedContent>
    <hc:ToggleBlock.UnCheckedContent>
        <hc:Empty/>
    </hc:ToggleBlock.UnCheckedContent>
</hc:ToggleBlock>
```

![image](https://user-images.githubusercontent.com/9213496/113477318-30d1e780-9496-11eb-825e-7e122279fde0.png)

**Comment by NaBian** [comment]
The default behavior is not to display Empty, you must assign true to ShowEmpty
