### ISSUE TITLE
AnimationPath RepeatBehavior="1" not work as expected

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#766]
**Describe the bug**
```xaml
<hc:AnimationPath Data="M 0,0 l 5,5 l 8,-8" Stroke="White" StrokeThickness="2" RepeatBehavior="1"
                  StrokeStartLineCap="Round" StrokeEndLineCap="Round" StrokeLineJoin="Round" />
```

![pqyO3kRWr3](https://user-images.githubusercontent.com/4510984/113617621-20359300-9689-11eb-90b0-8befd5a02522.gif)

**Expected behavior**
The animation only run once then stop. 

**Screenshots**

**Environment (please complete the following information):**
 - .net: .NET 5
 - IDE VS2019
 - Version 3.1.0

**Additional context**

**Comment by ghost1372** [comment]
Did you try ``` RepeatBehavior="Forever"``` ?

**Comment by GF-Huang** [comment]
`Forever` show me same behavior.

**Comment by GF-Huang** [comment]
I found that is the Microsoft stupid design.

![image](https://user-images.githubusercontent.com/4510984/113620991-a81d9c00-968d-11eb-9632-f61c0ea78d77.png)

https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.animation.repeatbehavior?f1url=%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(System.Windows.Media.Animation.RepeatBehavior);k(DevLang-csharp)%26rd%3Dtrue&view=net-5.0

### So I use `"1x"` instead of `"1"` works well.

**Comment by GF-Huang** [comment]
But how to holds the animation path after end? Now after finish, the path disappeared.

```xaml
<hc:AnimationPath Data="M0,0 l4,5 l8,-8" Stroke="White" StrokeThickness="1.5" RepeatBehavior="1x" Duration="0:0:1"
                  StrokeStartLineCap="Round" StrokeEndLineCap="Round" StrokeLineJoin="Round" />
```

![cY59vAgQSM](https://user-images.githubusercontent.com/4510984/113622007-fa12f180-968e-11eb-8d29-b1c70cb49211.gif)

**Comment by NaBian** [comment]
> But how to holds the animation path after end? Now after finish, the path disappeared.
> 
> ```
> <hc:AnimationPath Data="M0,0 l4,5 l8,-8" Stroke="White" StrokeThickness="1.5" RepeatBehavior="1x" Duration="0:0:1"
>                   StrokeStartLineCap="Round" StrokeEndLineCap="Round" StrokeLineJoin="Round" />
> ```
> 
> ![cY59vAgQSM](https://user-images.githubusercontent.com/4510984/113622007-fa12f180-968e-11eb-8d29-b1c70cb49211.gif)

after bebe9b8 you can use ```RepeatBehavior="1x" FillBehavior="HoldEnd"```
