### ISSUE TITLE
[Feature request] Need Nightly Build

### ISSUE THREAD

**Issue by liesauer** [HandyOrg/HandyControl#769]
因为某些修复未能及时更新到nuget，所以需要自己拉取代码自己编译，但由于并不是每个人都能有编译环境，所以获取新的更新就显得非常繁琐，希望能提供一个Nightly Build的nuget包供使用

**Comment by lwqwag** [comment]
> 因为某些修复未能及时更新到nuget，所以需要自己拉取代码自己编译，但由于并不是每个人都能有编译环境，所以获取新的更新就显得非常繁琐，希望能提供一个Nightly Build的nuget包供使用

同样需要

**Comment by NaBian** [comment]
已提供 myget 日构建版本，详细请参考 readme，myget 要点可参考相关博文或官网。
