### ISSUE TITLE
NumericUpDown Minimum Issue

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#771]
Consider the following example

`<hc:NumericUpDown Name="num" Maximum="40" Minimum="5" ValueChanged="num_ValueChanged"/>`

Now we save NumericUpDown value

```
private void num_ValueChanged(object sender, HandyControl.Data.FunctionEventArgs<double> e)
        {
            var val = num.Value;
            if (val != Settings.MaxHistoryNumber)
            {
                Settings.MaxHistoryNumber = (int)val;
            }
        }
```
As we can see, the changes are stored correctly

![1](https://user-images.githubusercontent.com/9213496/114262609-35e2e980-99f6-11eb-8e17-a43b9e34c18d.png)

Now when we run the program we load the stored value

```
public General()
        {
            InitializeComponent();
            num.Value = Settings.MaxHistoryNumber;
        }
```

But as you can see, the minimum value is displayed instead of the loaded value
![2](https://user-images.githubusercontent.com/9213496/114262692-9114dc00-99f6-11eb-9ff2-d2ea412c70a1.png)

Complete gif

![0](https://user-images.githubusercontent.com/9213496/114262757-ee109200-99f6-11eb-9fea-f4d7a9796d4e.gif)

**Comment by NaBian** [comment]
I can't reproduce the issue

**Comment by ghost1372** [comment]
@NaBian  Run the program
Change the value
Close the app
Open the app 
You can see that the minimum value is loaded each time

[WpfApp15.zip](https://github.com/HandyOrg/HandyControl/files/6337226/WpfApp15.zip)

**Comment by NaBian** [comment]
This is a problem with your code, not with HC. add ```if (!IsLoaded) return;``` In the first row of NumericUpDown_ValueChanged method.

**Comment by ghost1372** [comment]
Arigato 😅
