### ISSUE TITLE
[Feature request] Simplify how to use

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#776]
@NaBian  What do you think makes the process of using the handycontrol easier?

At the moment we need first add a NameSpace: `xmlns:hc="https://handyorg.github.io/handycontrol"`
Then before each control we have to use the `hc:` prefix

We can replace the following code

```
[assembly: XmlnsDefinition("https://handyorg.github.io/handycontrol", "HandyControl.Controls")]
...
```

with the following code

```
[assembly: XmlnsDefinition("http://schemas.microsoft.com/winfx/2006/xaml/presentation", "HandyControl.Controls")]
...
```

And as you can see here, this namespace is defined without a prefix

![Untitled](https://user-images.githubusercontent.com/9213496/114303482-9bf96a80-9ae3-11eb-9096-7ffdc3de2120.png)

This way users no longer need to add a namespace and can use the handycontrol like Visual Studio local controls.

**Comment by NaBian** [comment]
This will be convenient for users, but it can also be confusing. just like hc:TextBox, TextBox and so on
