### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by Coding201212** [HandyOrg/HandyControl#8]
What an excellent job you have done.  Thanks so much. 
Could you add these common controls to your new plan, to make them more beautiful:
1. Data-Table
2. Navigator
3. Be able to be selected map (such as a China map)

**Comment by NaBian** [comment]
Thank you for your advice, datatable and map are in my plan all the time, but what is navigator? a combination button for the left and right arrows or some other form of control?

**Comment by ghost1372** [comment]
do you have any plan for chart?:D

**Comment by NaBian** [comment]
@ghost1372 No, never planned, chart is too complex

**Comment by Coding201212** [comment]
@NaBian Thanks for your reply. Actually, the navigator what I said likes the menu on the website.

**Comment by ghost1372** [comment]
@eq7755 you can create your own navigator, check demo project you can see a navigator created by treeview,
