### ISSUE TITLE
CheckComboBox doesn't display "All" text  when theme is set for just that control

### ISSUE THREAD

**Issue by dilby3** [HandyOrg/HandyControl#805]
I don't want to apply the HandyControl styles to all of my controls. I only want to apply it to the CheckComboBox. So to do this I added the HandyTheme as a resource of the control using the below code:
```
<hc:CheckComboBox ShowClearButton="True" MaxWidth="380" MinWidth="100" MaxHeight="25" ShowSelectAllButton="True">
    <hc:CheckComboBox.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <hc:Theme Name="HandyTheme"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </hc:CheckComboBox.Resources>
    <hc:CheckComboBox.Items>
        <hc:CheckComboBoxItem Content="Item1"/>
        <hc:CheckComboBoxItem Content="Item2"/>
        <hc:CheckComboBoxItem Content="Item3"/>
    </hc:CheckComboBox.Items>
</hc:CheckComboBox>
```
However, the "All" CheckComboBoxItem doesn't display any text - it is just a CheckBox with no text next to it.
If I add  `<hc:Theme Name="HandyTheme"/>` to the app.xaml ResourceDictionary then the "All" CheckComboBoxItem's text shows up. But then the HandyTheme gets applied to all controls which I do not want.

Is this a known problem? Or is there a better way to apply a a HandyTheme style to a single control?

**Comment by ghost1372** [comment]
Add resource styles as code in the windows static constructor

https://github.com/HandyOrg/HandyControl/issues/616
