### ISSUE TITLE
Does the ThemeManager's System Theme Syncing work on MacOS and Linux?

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#813]
I'm planning to build a .net core app that is supposed to run on windows, MacOS and Ubuntu. The app has a theme switcher to switch between light, dark and System Theme modes. So I just wanted to know if the app theme can sync with the system theme of MacOS and Ubuntu like it does on Windows.

**Comment by ghost1372** [comment]
@SwaroopSomanna  WPF .Net Core can not run on linux and mac (only console app can run), so you cant use handycontrol on this OS
