### ISSUE TITLE
HcTabControl.Items.Remove 子项时移除不掉。显示黑色tab

### ISSUE THREAD

**Issue by WangToCode** [HandyOrg/HandyControl#826]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - .net: [e.g. 4.6.2]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by WangToCode** [comment]
![image](https://user-images.githubusercontent.com/48405002/117965040-e70dd400-b354-11eb-91ae-0d6aa6bf13f3.png)

**Comment by NaBian** [comment]
因为未按照模板详细说明 issue，故而关闭
