### ISSUE TITLE
[Suggestion] TextBlockAttach.AutoTooltip should not change the TextTrimming property

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#827]
https://github.com/HandyOrg/HandyControl/blob/0762db0fb4b4a7378d8b8b783d09d30e7c306092/src/Shared/HandyControl_Shared/Controls/Attach/TextBlockAttach.cs#L18

It will overwrite the user defined `TextTrimming`, in my case it will overwrite my `CharacterEllipsis` to `WordEllipsis`.

--------------

### `TextTrimming.WordEllipsis` 

![image](https://user-images.githubusercontent.com/4510984/117969519-183cd300-b35a-11eb-8909-c31256ad7677.png)

--------------

### `TextTrimming.CharacterEllipsis`

![image](https://user-images.githubusercontent.com/4510984/117970038-c5175000-b35a-11eb-9bfb-5f6cac87ce70.png)

**Comment by NaBian** [comment]
you are right

**Comment by GF-Huang** [comment]
@NaBian 没看懂加了 `CalcTextWidth(textBlock) > width` 这个判断有什么意义：
https://github.com/HandyOrg/HandyControl/blob/c9fb7a2eb56ecd6971d51c644273f6f7afc916d7/src/Shared/HandyControl_Shared/Controls/Attach/TextBlockAttach.cs#L49

去掉 `CalcTextWidth(textBlock) > width` 之后反而正常，不去掉的话，某些情况下明明可以足够显示完整的文本还是弹出 `Tooltip`.
