### ISSUE TITLE
NotifyIcon disappeared after Windows Explorer restart

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#830]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4510984/147389969-ede8e281-867d-4ac7-a7d9-5f4181534933.png)

**Environment (please complete the following information):**
 - .net: 5
 - IDE vs2022
 - Version HandyControls 3.3.8

**Comment by GF-Huang** [comment]
~Sorry, it seems only occurs when explorer crashing.~

It can be duplicates when restart explorer.exe multi times.

**Comment by ghost1372** [comment]
@GF-Huang  This issue has already been fixed in handycontrols with 
`TaskbarRebuildBehavior` 😁

https://github.com/ghost1372/HandyControls/issues/91

https://hosseini.ninja/handycontrol/extend_controls/notifyIcon/


```
<hc:Window>
<hc:NotifyIcon x:Name="NotifyIcon"/>
<hc:Interaction.Behaviors>
<hc:TaskbarRebuildBehavior Element="{Binding ElementName=NotifyIcon}" />
</hc:Interaction.Behaviors>
</hc:Window>
```

**Comment by GF-Huang** [comment]
> @GF-Huang This issue has already been fixed in handycontrols with `TaskbarRebuildBehavior` 😁
> 
> [ghost1372/HandyControls#91](https://github.com/ghost1372/HandyControls/issues/91)
> 
> [hosseini.ninja/handycontrol/extend_controls/notifyIcon](https://hosseini.ninja/handycontrol/extend_controls/notifyIcon/)
> 
> ```
> <hc:Window>
> <hc:NotifyIcon x:Name="NotifyIcon"/>
> <hc:Interaction.Behaviors>
> <hc:TaskbarRebuildBehavior Element="{Binding ElementName=NotifyIcon}" />
> </behaviors:Interaction.Behaviors>
> </hc:Window>
> ```

Great, ~which version includes this fix?~ I found it is 3.3.10.

**Comment by GF-Huang** [comment]
@ghost1372 It seems not works if I define the `NotifyIcon` in `App.xaml`. Because I need show it without MainWindow display like this: https://github.com/HandyOrg/HandyControl/issues/748.

![image](https://user-images.githubusercontent.com/4510984/147392265-89ad553c-abb5-4486-8ffd-556e11abc2d6.png)

and defined in MainWindow.xaml:

![image](https://user-images.githubusercontent.com/4510984/147392278-36ae0e44-3304-4087-b824-5b6abd845c0e.png)

----------

If I define the `<hc:TaskbarRebuildBehavior Element="{Binding Source={StaticResource NotifyIcon}}" />` inside `NotifyIcon`, I will get run time exception.

![image](https://user-images.githubusercontent.com/4510984/147392335-e844cc92-8a47-40d1-8875-4ce5d9008221.png)

![image](https://user-images.githubusercontent.com/4510984/147392332-01391dc6-8de8-4070-bc16-3f3cdfcf4747.png)

**Comment by ghost1372** [comment]
Thank you @GF-Huang 
I will work on this issue

**Comment by caobug** [comment]
有进展了吗？
