### ISSUE TITLE
GrowlInfo.ActionBeforeClose not called when user click the close button

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#833]
**Describe the bug**
```cs
var info = new GrowlInfo {
    ShowDateTime = false,
    Message = "xxx",
    ActionBeforeClose = isConfirmed => Debug.WriteLine("xxx")
};
Growl.Success(info);
```

**Expected behavior**
No matter auto close or user click, should always called.

**Screenshots**

**Environment (please complete the following information):**
 - .net: 5
 - IDE vs2019
 - Version 3.1.0

**Additional context**

**Comment by ghost1372** [comment]
You should write return true

**Comment by GF-Huang** [comment]
> You should write return true

Yeah, I forget write it, but this is a example. If the `ActionBeforeClose` not called, it's meaningless no matter return true or not. The return value just for determine it to close or not.

**Comment by GF-Huang** [comment]
@NaBian Hi, I found that if clear by right click context menu, the `ActionBeforeClose` also not called. Does commit `a6a78f4` also fix this?

![image](https://user-images.githubusercontent.com/4510984/120919611-13ff9d80-c6ed-11eb-9c12-033f51dfe273.png)
