### ISSUE TITLE
 Dialog 关闭不掉

### ISSUE THREAD

**Issue by qiang9420d** [HandyOrg/HandyControl#839]
Dialog d = null;
       
        private void Lu_Read(book bk)
        {

            downloadIng dl = new downloadIng(bk);
            dl.downSu += Dl_downSu; ;
            dl.downError += Dl_downError;
            d = Dialog.Show(dl);
        }

        private void Dl_downSu(book bk)
        {
            d.Close();
        }

close()  不生效，不知道是自己用的不对，还是BUG

**Comment by NaBian** [comment]
duplicate of #488
