### ISSUE TITLE
Override button group style and apply custom styles to individual buttons in the button group?

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#844]
I have a button group consisting of several radio buttons and toggle buttons. I've set custom styles for these buttons. When I run the application the custom styles are not applied to the buttons but the button group's style is applied to the buttons. I understand that its obvious that the button group style will be applied to the containing buttons. But is there a way to override the button group style and apply custom styles to individual buttons in the button group?

**Comment by NaBian** [comment]
of course you can, just set ItemContainerStyleSelector property of ButtonGroup, it's default value is ButtonGroupItemStyleSelector, you can custom anything you want.
