### ISSUE TITLE
How to set Path size to default IconElement.Geometry Size

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#845]
I've a Button with a Path in Button.Content. I want the path's height and width to match the default IconElement.Geometry's height and width. How can I achieve that?

**Comment by NaBian** [comment]
default height and width of IconElement.Geometry is double.NaN

**Comment by ms-somanna** [comment]
> default height and width of IconElement.Geometry is double.NaN

Ok
