### ISSUE TITLE
glowl fetal cause NullReferenceException

### ISSUE THREAD

**Issue by lwqwag** [HandyOrg/HandyControl#848]
**Describe the bug**

**To Reproduce**
1. Go to HandyControlDemo 
2. Click on  信息通知-->严重
4. See error NullReferenceException cause app fetal

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - .net: all version of netcore and nfx
 - IDE [e.g. vs2019]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by NaBian** [comment]
It‘s not reasonable for the ContextMenu to disappear after reporting a fatal error, so I removed the original design
