### ISSUE TITLE
Children of UniformSpacingPanel are not horizontally stretching!

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#852]
I have a ListView and a TreeView inside a UniformSpacingPanel. The UniformSpacingPanel's orientation is set to Vertical and Spacing is set to 8.
The TreeView's and ListView's Horizontal Alignment is set to "Stretch" but they are not stretching. See image below. But if I use a StackPanel instead of the UniformSpacingPanel the children are stretched fully.

![Screenshot 2021-06-02 165641.png](https://user-images.githubusercontent.com/32904377/120473657-e51fb980-c3c4-11eb-88d5-d30601175825.png)
USP stands for UniformSpacingPanel

**Comment by ghost1372** [comment]
duplicate https://github.com/HandyOrg/HandyControl/issues/846
also fixed
