### ISSUE TITLE
Chinese language, even with language change

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#859]
@NaBian Some users have reported that some texts are displayed in Chinese, In **HandyControls** I have set the default language to English. (in my system Everything works fine, I think it's because Windows culture is in English) And I expect all the programs it builds to use English culture by default, But on other systems there is a problem And English culture is not selected
what is your idea about this?
Do we have to set English as a culture in startup (setLang("en"))?

https://github.com/HandyOrg/HandyWinGet/issues/30
https://github.com/HandyOrg/HandyWinGet/issues/34

![image](https://user-images.githubusercontent.com/9213496/121048757-53e98200-c7cc-11eb-9d5b-bd98fdd4b155.png)

**Comment by NaBian** [comment]
if user delete en lang in debug folder, hc will switch to Chinese, whether you setLang("en") or not.
i'm a Chinese, so I decided to set the default language to Chinese, let me be wayward for once 😄

**Comment by ghost1372** [comment]
Oh I did not notice the language folder may not be placed in the output
it's Fair enough😁
