### ISSUE TITLE
Brush issue

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#863]
Why is there no such color now?

![image](https://user-images.githubusercontent.com/4510984/121509915-b1bed980-ca19-11eb-90f3-d5f8a25fffdf.png)

**Comment by NaBian** [comment]
you can still achieve a gradient brush: PrimaryColor + DarkPrimaryColor = PrimaryBrush, as for why I want to remove the gradient brush, it's just my personal aesthetic 😄

**Comment by GF-Huang** [comment]
Got it, thanks guide.
