### ISSUE TITLE
Growl notification mouse over event causes exception

### ISSUE THREAD

**Issue by MohammadRezaKashi** [HandyOrg/HandyControl#867]
I am using handy control growl notification in my WPF application. But when I move my mouse on the growl notification it causes exception and close application.
I does not show any good exception report.
![growlnotification](https://user-images.githubusercontent.com/52103513/121765952-ca3b0b00-cb63-11eb-8d8f-675463c5177d.png)

**Comment by ghost1372** [comment]
Show us your codes and Follow the template instructions

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - .net: [e.g. 4.6.2]
 - IDE [e.g. vs2017]
 - Version [e.g. 1.0.0]

**Additional context**
Add any other context about the problem here.

**Comment by MohammadRezaKashi** [comment]
This is my app.xaml code

```
<Application x:Class="SurgeryTrainer.App" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:local="clr-namespace:SurgeryTrainer"
             StartupUri="MainWindow.xaml" 
             xmlns:viewModel="clr-namespace:SurgeryTrainer.MVVM.ViewModel"
             xmlns:view="clr-namespace:SurgeryTrainer.MVVM.View"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             d1p1:Ignorable="d"
             xmlns:d1p1="http://schemas.openxmlformats.org/markup-compatibility/2006">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/SkinDark.xaml" />
                <ResourceDictionary Source="pack://application:,,,/HandyControl;component/Themes/Theme.xaml" />
            </ResourceDictionary.MergedDictionaries>
            <DataTemplate DataType="{x:Type viewModel:LogInViewModel}">
                <view:LogInView />
            </DataTemplate>
            <DataTemplate DataType="{x:Type viewModel:SignUpViewModel}">
                <view:SignUpView />
            </DataTemplate>
            <DataTemplate DataType="{x:Type viewModel:HomeViewModel}">
                <view:HomeView />
            </DataTemplate>
            <DataTemplate DataType="{x:Type viewModel:AddReferenceViewModel}">
                <view:AddReferenceView />
            </DataTemplate>
            <DataTemplate DataType="{x:Type viewModel:StudentsListViewModel}">
                <view:StudentsListView />
            </DataTemplate>
            <DataTemplate DataType="{x:Type viewModel:PersonalInformationViewModel}">
                <view:PersonalInformationView/>
            </DataTemplate>
            <DataTemplate DataType="{x:Type viewModel:UploadResultViewModel}">
                <view:UploadResultView/>
            </DataTemplate>
            <DataTemplate DataType="{x:Type viewModel:StudentResultViewModel}">
                <view:StudentResultView/>
            </DataTemplate>
            <DataTemplate DataType="{x:Type viewModel:ResultViewModel}">
                <view:ResultView/>
            </DataTemplate>
            <DataTemplate DataType="{x:Type viewModel:ImageViewModel}">
                <view:ImageView/>
            </DataTemplate>          
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

this is my mainWindow.xaml

```
<Window x:Class="SurgeryTrainer.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:SurgeryTrainer"
        xmlns:viewModel="clr-namespace:SurgeryTrainer.MVVM.ViewModel"
        xmlns:hc="https://handyorg.github.io/handycontrol"
        mc:Ignorable="d"
        Title="MainWindow" Height="1080" Width="1920"
        WindowStartupLocation="CenterScreen"
        WindowState="Maximized"
        RenderOptions.BitmapScalingMode="HighQuality"
        WindowStyle="None">

    <Window.DataContext>
        <viewModel:MainViewModel/>
    </Window.DataContext>

    <Grid>
        <ScrollViewer VerticalScrollBarVisibility="Hidden" HorizontalAlignment="Right">
            <StackPanel hc:Growl.GrowlParent="True" VerticalAlignment="Top" Margin="0,10,10,10" />
        </ScrollViewer>
        <ContentControl Content="{Binding CurrentView}"></ContentControl>
    </Grid>
    
</Window>
```
 
this is the code which create my notification

`Growl.SuccessGlobal("Enter to home page");`

my issue is:
when I move my mouse on the notification my application throw  an exception which is
![growlnotification](https://user-images.githubusercontent.com/52103513/121766396-c492f480-cb66-11eb-9f5f-a1383dde767b.png)

**Comment by ghost1372** [comment]
please complete the following information:

.net: [e.g. 4.6.2]
IDE [e.g. vs2017]
Version [e.g. 1.0.0]

**Comment by MohammadRezaKashi** [comment]
.net framework 4.8
visual studio 2019
version 3.1.0

**Comment by MohammadRezaKashi** [comment]
I think because I am using MVVM design pattern and I have implemented my
own relay command class to handle command it's command may conflicts by my
relay command class.

**Comment by ghost1372** [comment]
Note that there are 2 ways to show the growl
1. If you want growl to be displayed in your application (MainWindow):
 You need a panel (Not required in the next version)
```
<ScrollViewer VerticalScrollBarVisibility="Hidden" HorizontalAlignment="Right">
            <StackPanel hc:Growl.GrowlParent="True" VerticalAlignment="Top" Margin="0,10,10,10" />
        </ScrollViewer>
```
The important thing is that you must use:
```
Growl.Success("Message");
Growl.Error("Message");
...
```
2. If you want growl to be displayed in out side of your application:
 You do not need a panel and you should remove the panel from your program and use the following method:

```
Growl.SuccessGlobal("Message");
Growl.ErrorGlobal("Message");
...
```

~~So to solve your problem, if you want to use the Global method, you have to delete the panel, Otherwise, it is enough to use a method that does not have a global keyword~~
The problem seems to be something else

**Comment by ghost1372** [comment]
@NaBian The global method interferes with the panel `hc:Growl.GrowlParent="True"`

**Comment by MohammadRezaKashi** [comment]
I implemented a simple project for test global growl notification as you said in the previous comment , but when global notification is on the main window it causes crash. while it works correctly in the version 3.0.0.

it is a bug in the newest versions. 

I can send you my source code if you want.

**Comment by MohammadRezaKashi** [comment]
thank you for your attention and answer but my problem has not solved yet.
please help to solve the problem.

**Comment by ghost1372** [comment]
Issue needs to be fixed in source code I do not have a solution at the moment

**Comment by NaBian** [comment]
i can not reproduce this problem

**Comment by MohammadRezaKashi** [comment]
You should create a global notification in the C# code and move your mouse
on the notification. You should attention that when you want to move your
mouse on the notification, notification should be on the application window.

**Comment by MohammadRezaKashi** [comment]
I have tested your source code. When the notification is shown by the
command it works correctly. For example if global notification shows by a
button command. But if you create notification from the backend you can see
the problem.

**Comment by NaBian** [comment]
I did what you said, but I still can't reproduce it

**Comment by MohammadRezaKashi** [comment]
I can send you my source code on saturday.

**Comment by ghost1372** [comment]
@NaBian 
This problem seems to occur only in debug mode
![Animation](https://user-images.githubusercontent.com/9213496/122447320-dc300a00-cfb8-11eb-8699-6a3f149f6b30.gif)

**Comment by MohammadRezaKashi** [comment]
Yes this is exactly my problem.
Thank you for your response.

I hope you solve this problem as soon as possible.

**Comment by MohammadRezaKashi** [comment]
I shall to say that I have tested this problem in the Release mode but I also have the sample problem.

**Comment by cuiliang** [comment]
@kouroshkashi  You can try if this can solve the problem:
https://github.com/HandyOrg/HandyControl/issues/793#issuecomment-820859410

**Comment by ghost1372** [comment]
@cuiliang  Tnx i tested and Your solution works, this issue can be closed

**Comment by ZGGSONG** [comment]
> @kouroshkashi You can try if this can solve the problem: [#793 (comment)](https://github.com/HandyOrg/HandyControl/issues/793#issuecomment-820859410)

[https://github.com/HandyOrg/HandyControl/issues/793#issuecomment-1011690174](https://github.com/HandyOrg/HandyControl/issues/793#issuecomment-1011690174)
