### ISSUE TITLE
Border shadow too dark in Win7

### ISSUE THREAD

**Issue by GF-Huang** [HandyOrg/HandyControl#876]
That looks different from win10.

#### Win7:

![image](https://user-images.githubusercontent.com/4510984/122486305-61440f00-d00b-11eb-985a-8ae9f2d9a1d3.png)

#### Win10:

![image](https://user-images.githubusercontent.com/4510984/122486372-8769af00-d00b-11eb-8a60-ec3eed1c6131.png)

**Comment by NaBian** [comment]
the effect is controlled by windowchrome, we can not custom.
