### ISSUE TITLE
BlurWindow NOT working on windows 10

### ISSUE THREAD

**Issue by Game-Glide** [HandyOrg/HandyControl#884]
**Describe the bug**
The "BlurWindow" control is not working on windows 10.

**To Reproduce**
1. Clone this repo: https://github.com/YT-GameWorks/terminalix
2. Open the "terminalix" solution in visual studio
3. Run in debug mode with any cpu
4. See White Screen

**Expected behavior**
The window should appear as an acrylic blur like this:
![](https://raw.githubusercontent.com/HandyOrg/HandyOrgResource/master/HandyControl/Resources/BlurWindow.png)

Instead we get this:
![image](https://user-images.githubusercontent.com/39207327/123277302-9d9fcf80-d523-11eb-8b2e-36546082f7ed.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/39207327/123277358-aabcbe80-d523-11eb-813e-197a921f7be8.png)

**Environment (please complete the following information):**
 - .net: 4.7.2
 - IDE vs2019
 - Version 3.1.0

**Additional context**
I am using this code for the blurwindow:

```xaml
<hc:BlurWindow x:Class="ui.MainWindow"
               xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
               xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
               xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
               xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
               xmlns:hc="https://handyorg.github.io/handycontrol"
               mc:Ignorable="d"
               Style="{StaticResource WindowBlur}"
               WindowStartupLocation="CenterScreen"
               Title="Terminalix"
               Height="450" 
               Width="800">
</hc:BlurWindow>
```

and here is the class:

```cs
using HandyControl.Data;
using HandyControl.Themes;
using HandyControl.Tools;
using System;
using System.Windows;

namespace ui
{
	public partial class MainWindow
	{
		public MainWindow()
		{
			InitializeComponent();
			UpdateSkin(SkinType.Dark);
		}

		public void UpdateSkin(SkinType skin)
		{
			SharedResourceDictionary.SharedDictionaries.Clear();
			Resources.MergedDictionaries.Add(ResourceHelper.GetSkin(skin));
			Resources.MergedDictionaries.Add(new ResourceDictionary
			{
				Source = new Uri("pack://application:,,,/HandyControl;component/Themes/Theme.xaml")
			});
		}
	}
}
```

**Comment by ghost1372** [comment]
First of all, read the documentation
https://hosseini.ninja/handycontrol/extend_controls/blurWindow/

`Operating system support range: win10 10240 ~ win10 18362
`

**Comment by Game-Glide** [comment]
oh, I thought I was running 18362, must've randomly updates someday! my bad! also `FORCE_ENABLE_ACRYLIC_BLUR` doesn't seem to be a property

**Comment by ghost1372** [comment]
FORCE_ENABLE_ACRYLIC_BLUR  is available Only in Custom Version

**Comment by Game-Glide** [comment]
oh alr, where do I get that 😅 ?

**Comment by ghost1372** [comment]
https://github.com/ghost1372/HandyControls

**Comment by Game-Glide** [comment]
okay, thanks!
