### ISSUE TITLE
当HC的ComBox使用Style="{StaticResource ComboBoxExtend}"时，它的AutoComplete不生效，不会调用SearchFunc。

### ISSUE THREAD

**Issue by 5653325** [HandyOrg/HandyControl#888]
去掉Style="{StaticResource ComboBoxExtend}"，HC的ComBox可以实现自动完成和调用它的SearchFunc委托。
不知道算不算一个bug。

**Comment by NaBian** [comment]
不算， ComboBoxExtend 是给原生 ComboBox 用的，而不是 hc:ComboBox
