### ISSUE TITLE
How to remove space between datagrid and its Row Details?

### ISSUE THREAD

**Issue by lukedukeus** [HandyOrg/HandyControl#891]
I have the following XAML:
` <DataGrid ItemsSource="{Binding Employees}" AutoGenerateColumns="false"
              RowDetailsVisibilityMode="Visible"
              CanUserAddRows="False" >
            <DataGrid.Columns>
                <DataGridTextColumn Header="Make" Binding="{Binding ID}"/>
                <DataGridTextColumn Header="Model" Binding="{Binding Name}"/>
            </DataGrid.Columns>
            <DataGrid.RowDetailsTemplate>
                <DataTemplate>
                    <DataGrid ItemsSource="{Binding Details}" AutoGenerateColumns="false" CanUserAddRows="False">
                        <DataGrid.Columns>
                            <DataGridTextColumn Header="ID" Binding="{Binding ManagerID}"/>
                            <DataGridTextColumn Header="Size" Binding="{Binding ManagerName}" IsReadOnly="True"/>
                          </DataGrid.Columns>
                    </DataGrid>
                </DataTemplate>
            </DataGrid.RowDetailsTemplate>
        </DataGrid>`
And its Codebehind:
`using System.Collections.Generic;

namespace HandyControlWpfApp1
{
    public partial class MainWindow
    {
        public MainWindow()
        {
            InitializeComponent();

            var detail1 = new EmployeeDetails() { ManagerID = 11, ManagerName = "11 Name", ManagerMobile = "123456" };
            var detail2 = new EmployeeDetails() { ManagerID = 12, ManagerName = "12 Name", ManagerMobile = "123456" };
            var detail3 = new EmployeeDetails() { ManagerID = 13, ManagerName = "13 Name", ManagerMobile = "123456" };

            var detail4 = new EmployeeDetails() { ManagerID = 11, ManagerName = "11 Name", ManagerMobile = "123456" };
            var detail5 = new EmployeeDetails() { ManagerID = 12, ManagerName = "12 Name", ManagerMobile = "123456" };
            var detail6 = new EmployeeDetails() { ManagerID = 13, ManagerName = "13 Name", ManagerMobile = "123456" };

            var detail7 = new EmployeeDetails() { ManagerID = 11, ManagerName = "11 Name", ManagerMobile = "123456" };
            var detail8 = new EmployeeDetails() { ManagerID = 12, ManagerName = "12 Name", ManagerMobile = "123456" };
            var detail9 = new EmployeeDetails() { ManagerID = 13, ManagerName = "13 Name", ManagerMobile = "123456" };

            var details1 = new List<EmployeeDetails>();
            details1.Add(detail1);
            details1.Add(detail2);
            details1.Add(detail3);

            var details2 = new List<EmployeeDetails>() { detail4, detail5, detail6 };
            var details3 = new List<EmployeeDetails>() { detail7, detail8, detail9 };

            Employees = new List<Employee>();
            Employees.Add(new Employee() { ID = 1, Name = "Name1", Details = details1 });
            Employees.Add(new Employee() { ID = 2, Name = "Name2", Details = details2 });
            Employees.Add(new Employee() { ID = 3, Name = "Name3", Details = details3 });

            SelectedEmployee = Employees[1];

            this.DataContext = this;
        }

        public List<Employee> Employees { get; set; }

        private Employee _selected;

        public Employee SelectedEmployee
        {
            get { return _selected; }
            set { _selected = value; }
        }

        public class Employee
        {
            public int ID { get; set; }
            public string Name { get; set; }
            public List<EmployeeDetails> Details { get; set; }
        }

        public class EmployeeDetails
        {
            public int ManagerID { get; set; }
            public string ManagerName { get; set; }
            public string ManagerMobile { get; set; }

        }
    }
}
`

It looks like this:
![detail summary](https://user-images.githubusercontent.com/23089287/123999169-35784000-d9a0-11eb-8ba9-e8c9e2be2bfa.PNG)

Is there any way to decrease the space between the rows of the datagrid?

**Comment by Yopler** [comment]
Here a solution you can try : 

Create a style that is based on the HandyControl Datagrid Row Style and modify the Margin : 
```
<Style x:Key="DataGridRowStyleBis" TargetType="DataGridRow" BasedOn="{StaticResource DataGridRowStyle}">
                <Setter Property="Margin" Value="0"/>
</Style>
```

And then refered to it with the RowStyle Property of the DataGrid : 

```
<DataGrid  RowStyle="{StaticResource DataGridRowStyleBis}" ItemsSource="{Binding Details}" AutoGenerateColumns="false" CanUserAddRows="False">
```

It give you something like this : 
![image](https://user-images.githubusercontent.com/45144437/126345380-0c27a48a-397d-44cf-a3e0-9f22b3ec6a22.png)



Here the complete solution :

```
<Grid>
        
        <Grid.Resources>
            <Style x:Key="DataGridRowStyleBis" TargetType="DataGridRow" BasedOn="{StaticResource DataGridRowStyle}">
                <Setter Property="Margin" Value="0"/>
            </Style>
        </Grid.Resources>
        
        <DataGrid ItemsSource="{Binding Employees}" AutoGenerateColumns="false" RowDetailsVisibilityMode="Visible" CanUserAddRows="False">
            <DataGrid.Columns>
                <DataGridTextColumn Header="Make" Binding="{Binding ID}"/>
                <DataGridTextColumn Header="Model" Binding="{Binding Name}"/>
            </DataGrid.Columns>
            <DataGrid.RowDetailsTemplate>
                <DataTemplate>
                    <DataGrid ItemsSource="{Binding Details}" AutoGenerateColumns="false" CanUserAddRows="False" RowStyle="{StaticResource DataGridRowStyleBis}">
                        <DataGrid.Columns>
                            <DataGridTextColumn Header="ID" Binding="{Binding ManagerID}"/>
                            <DataGridTextColumn Header="Size" Binding="{Binding ManagerName}" IsReadOnly="True"/>
                        </DataGrid.Columns>
                    </DataGrid>
                </DataTemplate>
            </DataGrid.RowDetailsTemplate>
        </DataGrid>
    </Grid>
```
