### ISSUE TITLE
Remove MergedDictionaries from Styles

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#893]
Hi @NaBian Since all styles are created by the **XamlCombine** in the `Theme.xaml` file, can we remove MergedDictionaries from styles?
If yes, let me make a PR

![00](https://user-images.githubusercontent.com/9213496/124365296-3e953580-dc5c-11eb-8804-93bdf25b6a74.png)

**Comment by NaBian** [comment]
ok, great!
