### ISSUE TITLE
TitleElement on TextBox Alignment

### ISSUE THREAD

**Issue by nlogozzo** [HandyOrg/HandyControl#894]
The Title alignment on a TextBox seems to be unaligned with the control

![image](https://user-images.githubusercontent.com/17648453/124371011-9b3c2480-dc4b-11eb-960b-e5f03438ff93.png)

Could we fix it so the title lines up with the edge of the textbox

**Comment by NaBian** [comment]
No, that's how it's designed

**Comment by nlogozzo** [comment]
May I ask why? It looks weird in my opinion

**Comment by NaBian** [comment]
the title will lines up to content or placeholder, at least our designers think it looks better, It's just a matter of design.

**Comment by SamirKharchi** [comment]
One could extent the title placement with another attached property, e.g. a margin, to support other designs more easily.
Of course this could be taken way further generalizing more areas by allowing data templates or styles to be provided by the user.

**Comment by NaBian** [comment]
Configuring everything equal to configuring nothing, we should keep a balance between set meals and buffet. Then again, HC is just a lightweight library.
