### ISSUE TITLE
the style of PreviewSlider is unreasonable

### ISSUE THREAD

**Issue by BookerLiu** [HandyOrg/HandyControl#900]
**Describe the bug**
我在SimplePanel中使用HC控件, 页面样式在3.1中表现正常, 但是在3.2中全部混乱

**To Reproduce**
1. SimplePanel 上部会有一大部分空白空间, 但我代码中的Margin="0,0,-40,-12"
2. PreviewSlider 会显示被向下挤压,但鼠标在实际位置的时候才会显示PreviewSlider.PreviewContent

**Expected behavior**
希望3.2能够不改变3.1的样式(这可能本来就是个BUG)

**Screenshots**
3.1版本  
[![Rhrqd1.png](https://z3.ax1x.com/2021/07/05/Rhrqd1.png)](https://imgtu.com/i/Rhrqd1)
3.2版本  
[![RhDc4K.png](https://z3.ax1x.com/2021/07/05/RhDc4K.png)](https://imgtu.com/i/RhDc4K)  

**Environment (please complete the following information):**
 - .net: [4.7.2]
 - IDE [vs2019]
 - Version [3.2.0]

**Additional context**
无

**Comment by NaBian** [comment]
感谢您的反馈，如果能有简单的复现 demo 就更好啦，现在我们只能根据您的描述去猜，不利于复现问题。

**Comment by BookerLiu** [comment]
> 感谢您的反馈，如果能有简单的复现 demo 就更好啦，现在我们只能根据您的描述去猜，不利于复现问题。

```
 <hc:SimplePanel Margin="50" HorizontalAlignment="Center" >
    <!--<StackPanel HorizontalAlignment="Center"  Margin="50">-->
                <hc:PreviewSlider Value="20"
                              Maximum="100"
                                  Width="200"
                              >
                    <hc:PreviewSlider.PreviewContent>
                        <Label Style="{StaticResource LabelPrimary}" Content="{Binding Path=(hc:PreviewSlider.PreviewPosition),RelativeSource={RelativeSource Self}}" ContentStringFormat="#0"/>
                    </hc:PreviewSlider.PreviewContent>
                </hc:PreviewSlider>
        <!--</StackPanel>-->
    </hc:SimplePanel>
```
 @NaBian 
您好, 经测试, 在3.2版本 SimplePannel 中使用 PreviewSlider,  
 1. **SimplePanel的高度会覆盖(?) PreviewSlider的默认高度**, 必须手动设置PreviewSlider的高度才能生效;  
 2. 将SimplePanel 改为 StackPanel,PreviewSlider**默认高度生效**

**Comment by NaBian** [comment]
经测试，3.1 和 3.2 样式行为是一致的，故而此 issue 的标题不正确，应该修改为：PreviewSlider 样式不合理
