### ISSUE TITLE
没有数据时DataGrid的表头无法显示

### ISSUE THREAD

**Issue by dswfort** [HandyOrg/HandyControl#903]
**Describe the bug**
自从`3.0`升级到`3.2`后发现用到DataGrid的地方，当`ItemSource.Count=0`时，DataGrid不会显示`ColumnHeader`，翻看了其模板后发现是特意这么改的。判断逻辑为当`HasItem`=`False`，即没有数据的时候显示的是`hc:Empty`，如下。

``` CSharp
<hc:ToggleBlock IsChecked="{Binding HasItems,RelativeSource={RelativeSource TemplatedParent},Mode=OneWay}" VerticalContentAlignment="Stretch" HorizontalContentAlignment="Stretch">
    <hc:ToggleBlock.CheckedContent>
        <ScrollViewer x:Name="DG_ScrollViewer" Focusable="false">
            ...
        </ScrollViewer>
    </hc:ToggleBlock.CheckedContent>
    <hc:ToggleBlock.UnCheckedContent>
        <hc:Empty />
    </hc:ToggleBlock.UnCheckedContent>
</hc:ToggleBlock>
```

这样一来表格区域一片空白，看着会很奇怪，就比如我这个界面：

![显示效果](https://user-images.githubusercontent.com/57698521/124890063-3e08f000-e00a-11eb-8c61-a22828b59453.PNG)

尤其是在一些设置界面，首次打开肯定是没有数据的，也不显示表头。。。

**Expected behavior**
是不是可以考虑参照Web上的表格显示效果，保留表头，下方显示`hc:Empty`，并给`hc:Empty`定以一个默认模板，这样不会导致界面上啥都不显示。

**Screenshots**

**Environment (please complete the following information):**
 - .net: 4.6.1
 - IDE vs2019
 - Version 3.2.0

**Comment by ghost1372** [comment]
First, please type in English

Second, if you want to display hc:Empty, you need to set up an AttachedProperty `hc:Empty.ShowEmpty="true"` for the datagrid.

also if you need to use hc:Empty in another way again you should set `hc:Empty.ShowEmpty="true"`

please read [docs](https://hosseini.ninja/handycontrol/extend_controls/empty/)

**Comment by lwqwag** [comment]
I found a issue  when set DataGridTextColumn Width="*“ the header not visible when data is empty as blow code.

`
<DataGrid
            hc:Empty.ShowEmpty="True"
            AutoGenerateColumns="False"
            CanUserAddRows="False"
            CanUserSortColumns="False"
            HeadersVisibility="All"
            ItemsSource="{Binding TestData}">
            <DataGrid.Columns>
                <DataGridTextColumn Width="*" Header="TEST1" />
                <DataGridTextColumn Width="*" Header="TEST2" />
                <DataGridTextColumn Width="*" Header="TEST3" />
                <DataGridTextColumn Width="*" Header="TEST4" />
            </DataGrid.Columns>
        </DataGrid>
`
`ObservableCollection<Class> TestData=new ();`
