### ISSUE TITLE
使用Nuget更新版本至3.2.0，无法单独引用资源文件

### ISSUE THREAD

**Issue by Denny0503** [HandyOrg/HandyControl#904]
**Describe the bug**
在app.xaml中引用hc的控件资源，如图：
![image](https://user-images.githubusercontent.com/34758984/125422723-8f1baaf3-46b3-46cd-aedf-3535cdd09472.png)
然后添加自定义的按钮样式资源文件，对hc的按钮样式进行重写，引用hc的按钮样式，如下图所示：
![image](https://user-images.githubusercontent.com/34758984/125423215-b3c35fbb-6062-4c8a-a04a-d189527c8b82.png)
然后，编译运行后，报错，提示无法找到资源，报错如图所示：
![image](https://user-images.githubusercontent.com/34758984/125423734-f50e115c-647f-4b66-a308-eabafa3a889c.png)
但是使用3.0.0的版本是可以的，没问题。

**Comment by NaBian** [comment]
红框内删除即可

**Comment by NaBian** [comment]
3.1 开始资源已经合并了，没有单独控件级别的资源文件，可以在 app.xaml 中直接重写
