### ISSUE TITLE
Carousel control crashes on addition without initial items

### ISSUE THREAD

**Issue by SamirKharchi** [HandyOrg/HandyControl#905]
**Describe the bug**
The carousel control crashes when it has no items initially and one adds items afterwards.

**To Reproduce**
1. Add a carousel without any initial items
2. Add an item (e.g. via code) once the view has been initialised.
3. Crashes with an Out-of-bounds exception

**Expected behavior**
No crash.

**Additional context**
Debugging shows that `Carousel.UpdateItemsPosition()` is crashing once it tries to use the `PageIndex`, which is **-1** at that point and therefore of course out-of-bounds.

Possible fix is to update the `PageIndex` to an in-bounds range value when an item is added.
```
private void UpdateItemsPosition()
{
    if (!CheckNull() || !_appliedTemplate || Items.Count == 0)
        return;

    if (PageIndex == -1) // Fixes the crash
    {
         PageIndex = 0;
    }
```

**Comment by NaBian** [comment]
can you provide a demo, i can not reproduce this issue

**Comment by SamirKharchi** [comment]
Hi,

I am on holidays. I will provide a demo once I am back on my machine.

**Comment by NaBian** [comment]
> Hi,
> 
> I am on holidays. I will provide a demo once I am back on my machine.

hello?

**Comment by ghost1372** [comment]
@SamirKharchi  Are you back?😅

**Comment by SamirKharchi** [comment]
Hi guys!

sorry for the delay (had tons of work crashing on me after holidays, then it slipped my mind). 
I had the time yesterday to strip down our crashing code base and once I have stripped it down, the crash is not reproducable anymore I'm afraid.
However, in our full blown code it still does crash. It might be a threading issue on our side or something to do with Prism (which we are using) I guess, because I cannot reproduce it on a clean project or the demo project of HandyControl either.

I keep it in our version of HandyControl but it probably is not a necessary fix. So rry for keeping this pending for so long.

**Comment by 810906591** [comment]
ItemsSource 发生变化后
 private void UpdateItemsPosition()
 {
     if (!CheckNull() || !_appliedTemplate || Items.Count == 0)
         return;
     if (PageIndex == -1) // Fixes the crash
     {
         PageIndex = 0;
     }
     if (!IsCenter)
     {
         ItemsHost.BeginAnimation(MarginProperty,
             AnimationHelper.CreateAnimation(new Thickness(-_widthList[PageIndex], 0, 0, 0)));
     }
     else
     {
         var ctl = (FrameworkElement) ItemsHost.Children[PageIndex];
         var ctlWidth = ctl.DesiredSize.Width;
         ItemsHost.BeginAnimation(MarginProperty,
             AnimationHelper.CreateAnimation(
                 new Thickness(-_widthList[PageIndex] + (ActualWidth - ctlWidth) / 2, 0, 0, 0)));
     }
 }
这时，  var ctl = (FrameworkElement) ItemsHost.Children[PageIndex];会报越界。
原先ItemsSource 集合有多条数据，PageIndex=1（非0）；这时ItemsSource 集合只剩下1条数据，这个时候就报索引越界了
