### ISSUE TITLE
What is the default height of a button in HandyControl?

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#908]
Can somebody tell me what the default height of HandyControl button is? I want to match the height of my custom control to the buttons height.

**Comment by ghost1372** [comment]
look at in source code
https://github.com/HandyOrg/HandyControl/blob/17a54ef7ea9ee440a545bb930393974cb7f74c8a/src/Shared/HandyControl_Shared/Themes/Styles/Base/ButtonBaseBaseStyle.xaml#L5

https://github.com/HandyOrg/HandyControl/blob/17a54ef7ea9ee440a545bb930393974cb7f74c8a/src/Shared/HandyControl_Shared/Themes/Basic/Sizes.xaml#L5

**Comment by ms-somanna** [comment]
So it is 30.

**Comment by ghost1372** [comment]
Yeap
