### ISSUE TITLE
DateTimePicker dispaly error

### ISSUE THREAD

**Issue by hupo376787** [HandyOrg/HandyControl#913]
**Describe the bug**
Set `DateTimePicker`'s `SelectedDateTime`, and open the select dialog, the dialog display error datetime.

**To Reproduce**
1. Create a xaml `<hc:DateTimePicker x:Name="dt"/>`
2. Add code behind `dt.SelectedDateTime = new DateTime(2021, 3, 20, 14, 35, 59);`

**Expected behavior**
Show the datetime given in code behind.

**Screenshots**
![image](https://user-images.githubusercontent.com/14960168/126437927-fba184d8-f92b-4aab-9adc-3af9cacfc7a6.png)

**Environment (please complete the following information):**
 - .net: core 3.1
 - IDE vs 2019 latest
 - HC Version 3.2.0

**Additional context**

**Comment by NaBian** [comment]
after 8813fddf you can use DisplayDateTime
