### ISSUE TITLE
[Feature request]Show slider value on top while sliding

### ISSUE THREAD

**Issue by hupo376787** [HandyOrg/HandyControl#914]
**Is your feature request related to a problem? Please describe.**
When sliding, user is not aware of the exact value.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/14960168/126587143-38810a12-4a7a-4750-89ba-50e9b16767f3.png)

**Comment by NaBian** [comment]
You certainly didn't take the time to open the demo

**Comment by hupo376787** [comment]
@NaBian I found the bug, the tip is shown, but not on the most top.

If set the height higher, the value can be seen.

![image](https://user-images.githubusercontent.com/14960168/127610886-7f23ce4e-303f-435d-9812-065398591a04.png)

**Comment by NaBian** [comment]
this can be opened as a separate issue, more issues are welcome!
