### ISSUE TITLE
OutOfMemoryError?

### ISSUE THREAD

**Issue by chancezheng** [HandyOrg/HandyControl#921]
DispatcherTimer timer = new ();
time.Interval = TimeSpan.FromSeconds(5);
timer.tick += (s,e)=>
{
   Notification.Show(new NotificationTip($"您有{count}份心电报告需要处理,请及时处理"), ShowAnimation.HorizontalMove, flase);
};
NotificationTip is belong to Page Class,
If my code as this,it will occur OutOfMemoryError???

**Comment by NaBian** [comment]
提供的信息太少，加之也无法复现，大概率不是 hc 的问题。

**Comment by chancezheng** [comment]
```
Notification.Show(new NotificationTip($"您有{count}份心电报告需要处理,请及时处理"), ShowAnimation.HorizontalMove, flase);
```
上诉代码挂机一晚上内存会从70M涨到260多M，如下图：
![image](https://user-images.githubusercontent.com/31839078/127945294-247d0f42-b0c3-48f1-b0ed-0aa1d8ea3158.png)
经我测试把这个方法的false置为true，然后手动关闭返回函数返回的windows实例，就不会有内存的问题，正常测试代码如下
```
var noti = Notification.Show(new NotificationTip($"您有{count}份心电报告需要处理,请及时处理"), ShowAnimation.HorizontalMove, true);
noti.Close();
```
