### ISSUE TITLE
Bug in ComboBox: "Value was either too large or too small for a double" 

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#928]
**Describe the bug**
When you set the ComboBox as follows   
```
<hc:ComboBox hc:InfoElement.PlaceHolder="Test 1">
<ComboBoxItem Content="Test 1"/>
<ComboBoxItem Content="Test 2"/>
</hc:ComboBox>
```
You get an error stating "Value was either too large or too small for a double". When you make any changes to the above code the error disappears but appears again after a few seconds.  
But the compilation is successful.

**Screenshots**
![Capture.PNG](https://user-images.githubusercontent.com/32904377/127036013-39990547-9517-4b84-b484-c98c7b4ddd29.PNG)

**Environment:**
 - .net 4.7.2
 - IDE vs2019
 - IDE Version: 16.9.3
- HandyControl version: 3.2.0
- HandyControls version: 3.3.7

**Comment by ghost1372** [comment]
you are using **hc:ComboBox** so you should add **hc:ComboBoxItem** not **ComboBoxItem**
