### ISSUE TITLE
InfoElement.RegexPattern not working for me.

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#933]
As mentioned in the [docs](https://hosseini.ninja/handycontrol/extend_controls/textBox/) I tried 
```
<hc:TextBox hc:InfoElement.RegexPattern="^[0-9]*(?:\.[0-9]+)?$"/>
```
The regex pattern mentioned above alllows for integers and floating point numbers only. But when I enter an alphabet in the textbox, the text is displayed in the textbox and no error is shown. Later I tried setting a custom error string using `ErrorStr="Numbers Only"` still no error is shown. Is this a bug or am I doing something wrong?

**Comment by ghost1372** [comment]
set TextType to anything except Common

`<hc:TextBox TextType="Mail" hc:InfoElement.RegexPattern="^[0-9]*(?:\.[0-9]+)?$"/>
`

**Comment by sami-soft** [comment]
> 

TextType property not found Error !
  
`<Window`
`        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"`
`        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"`
`        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"`
`        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"`
`        xmlns:local="clr-namespace:Myproject.Payments"`
`         xmlns:hc="https://handyorg.github.io/handycontrol"    `
`        xmlns:System="clr-namespace:System;assembly=System.Runtime" `
`        x:Class="Myproject.Payments.Form_1"`
`        mc:Ignorable="d"    `
`        Title="Form_1" Height="450" Width="800" Loaded="Window_Loaded">`
`    <Grid>`
`		<hc:TextBox  x:Name="txt_1" `
`		TextType="Mail"`
`		HorizontalAlignment="Left" Height="19" Margin="244,54,0,0" VerticalAlignment="Top" Width="219"/> `        
`    </Grid>`
`</Window>`

**Comment by CodingOctocat** [comment]
> set TextType to anything except Common
> 
> `<hc:TextBox TextType="Mail" hc:InfoElement.RegexPattern="^[0-9]*(?:\.[0-9]+)?$"/> `

`HandyControls` cannot find the `TextType`, while the `TextType` property of `HandyControl` is read-only.
