### ISSUE TITLE
v3.1升到v3.2  导致RelativePanel 内容不自适应

### ISSUE THREAD

**Issue by windsOne** [HandyOrg/HandyControl#934]
代码
![1627702082(1)](https://user-images.githubusercontent.com/14890297/127727417-14a7bcda-bf35-4a1f-b7f2-ba5e8c4e36dd.jpg)
V3.1 效果
![1627702104(1)](https://user-images.githubusercontent.com/14890297/127727425-6d506525-c288-4818-8f75-24219f1a93d4.jpg)
 V3.2 效果
![1627702015(1)](https://user-images.githubusercontent.com/14890297/127727428-5702b423-adef-4cd4-9192-ae7d9f5cd507.jpg)
请问如果在V3.2 让 Border  自适应windows 大小。谢谢

**Comment by windsOne** [comment]
测试代码
`<Window x:Class="RelativePanel.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:hc="https://handyorg.github.io/handycontrol"
        xmlns:local="clr-namespace:RelativePanel"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <hc:RelativePanel>
        <Border Background="Red"></Border>
    </hc:RelativePanel>
</Window>
`
V3.1 效果
![image](https://user-images.githubusercontent.com/14890297/127727628-386e5d7e-9501-436b-98f8-bdee0d673508.png)
 V3.2 效果
![image](https://user-images.githubusercontent.com/14890297/127727640-9c85af18-9b3e-4d1a-8bb9-bee04ca6d53d.png)

**Comment by NaBian** [comment]
3.2 行为和 uwp 中一致，3.1 反而是 bug

**Comment by windsOne** [comment]
@NaBian
那么如果我想在3.2 达到 3.1的效果，请问该怎么办。可能问题简单，但是真心求问
