### ISSUE TITLE
v3.1升到v3.2  导致RelativePanel 内容不自适应

### ISSUE THREAD

**Issue by windsOne** [HandyOrg/HandyControl#937]
测试代码
`<Window x:Class="RelativePanel.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:hc="https://handyorg.github.io/handycontrol"
        xmlns:local="clr-namespace:RelativePanel"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <hc:RelativePanel>
        <Border Background="Red"></Border>
    </hc:RelativePanel>
</Window>
`
V3.1 效果
![image](https://user-images.githubusercontent.com/14890297/127727628-386e5d7e-9501-436b-98f8-bdee0d673508.png)
 V3.2 效果
![image](https://user-images.githubusercontent.com/14890297/127727640-9c85af18-9b3e-4d1a-8bb9-bee04ca6d53d.png)

再次请问如何在3.2达到3.1 版本的效果，非常感谢

**Comment by NaBian** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.relativepanel?view=winrt-20348

**Comment by windsOne** [comment]
@NaBian 可能是我比较笨，就是偏向请教，请问怎么解决这个问题呢
如果不方便，请关闭问题就好了 。感谢！

**Comment by NaBian** [comment]
``` cs
<Border Background="Red" hc:RelativePanel.AlignLeftWithPanel="True" hc:RelativePanel.AlignTopWithPanel="True" hc:RelativePanel.AlignRightWithPanel="True" hc:RelativePanel.AlignBottomWithPanel="True"/>
```

**Comment by windsOne** [comment]
@NaBian 非常感谢！！！！！！
