### ISSUE TITLE
GlowWindow窗口最大化之后边框的Glow会变成一个白条

### ISSUE THREAD

**Issue by wagayaluda** [HandyOrg/HandyControl#942]
正常情况下，GlowWindow的边框会有一圈Glow
![屏幕截图 2021-08-04 101506](https://user-images.githubusercontent.com/27914613/128111091-8cd4fba7-cb58-4291-8d43-a775b4db734f.png)

但是窗口最大化的时候，这圈Glow会变成白色。把窗口设置为置顶（TopMost = "True"）就能看到这圈白色遮挡了任务栏的一部分。
正常情况
![屏幕截图 2021-08-04 101310](https://user-images.githubusercontent.com/27914613/128111375-25a3ee8d-c90e-4064-8ec4-cf52f88b8870.png)
窗口置顶后
![屏幕截图 2021-08-04 101346](https://user-images.githubusercontent.com/27914613/128111292-896dc3a6-f201-4b6e-bbff-91c6c84ca0d6.png)

多屏幕的时候，一个屏幕上把窗口最大化了也能在另一个屏幕边缘看到白边
![屏幕截图 2021-08-04 102218](https://user-images.githubusercontent.com/27914613/128111752-fb343906-faf7-45a8-af06-3a28e46ed8b4.png)
![屏幕截图 2021-08-04 102253](https://user-images.githubusercontent.com/27914613/128111867-d0be9490-90ca-48f4-bf24-4e1c8e693034.png)

在窗口最大化的时候把这圈Glow设置透明，或者宽度改成0应该就可以解决这个问题了

**Comment by NaBian** [comment]
#252
