### ISSUE TITLE
.NET 4.x框架中窗口最大化时，桌面消息通知获取鼠标焦点后会抛出异常

### ISSUE THREAD

**Issue by wagayaluda** [HandyOrg/HandyControl#943]
如图，当窗口最大化时，鼠标移动到这个通知上面就会引发异常。
仅在.NET Framework 4.x中存在这个问题，.NET Core和.NET 5是正常的。窗口不是最大化的时候也是正常的。
![屏幕截图 2021-08-04 112828](https://user-images.githubusercontent.com/27914613/128118784-75eb94e2-cf6d-4302-802a-90faee0a045c.png)
![屏幕截图 2021-08-04 112851](https://user-images.githubusercontent.com/27914613/128118795-927a0506-92eb-4351-bea7-8b2c151b64c3.png)

**Comment by NaBian** [comment]
#867

**Comment by wagayaluda** [comment]
> #867

已解决，谢谢
