### ISSUE TITLE
Pagination 'PageUpdated' event 

### ISSUE THREAD

**Issue by Ayoub-D1** [HandyOrg/HandyControl#944]
**The Bug**
I am using the Pagination control in my project. Just as suggested, I used the routedevent "PageUpdated". The problem I'm facing is that, if my initial MaxPageCount was 4 and let's say I chose to go to page 3 but then I filter my observableCollection which makes the new MaxPageCount a "2", this creates all sorts of problems, since the Pagination Control will see that my page index is > than my maxPageCount and for some reason, set my PageIndex to that count rather than 1 or NULL. Now, if it were to only change the PageIndex to the MaxPageCount, it would have been fine, but it also raises the PageUpdated event which reruns my logic for when the page is updated causing in my example a sort of concurrency problem.
I suggest in this situation to either reset the PageIndex to 1 (without raising the PageUpdated event) just like on first initialization of the Pagination control. Or to keep it synced to the maxPageCount but again without raising the event to let the user do so in code. 

**To Reproduce**
1. I had an Initial MaxPageCount of 4
2. I Navigated to the 3rd Page, calling the "OnPageUpdated" method. So now, PageIndex equals 3
3. I run some filtering logic on my data in the backend which should filter A.K.A reduce my collection
4. While the filtering data is still running, my code tries to set the new MaxPageCount to the new value of 2
5. The Pagination control sees that my MaxPageCount is less than PageIndex and sets my PageIndex to 2
6. The previous step, fires the 'PageUpdated' event which fires the "OnPageUpdated" method while I'm still filtering my data.
7. Lastly, this causes me a Concurrency problem.

**Expected behavior**
I would have expected the MaxPageCount to change to the new value WITHOUT firing the PageUpdated event and for my PageIndex to either be null (allows me to set it from my backend) or be set to 1 AGAIN WITHOUT firing the 'PageUpdated' event. Since, if I am changin the MaxPageCount then I must be in the process of updating my data.

**Comment by sunnylocus** [comment]
I have encountered the same problem, can I ask when the bug could be fixed?

**Comment by NaBian** [comment]
You should use a variable to determine if you are filtering and ignore PageUpdated event.
