### ISSUE TITLE
TransitioningContentControl does not transition on content change

### ISSUE THREAD

**Issue by DarthMazut** [HandyOrg/HandyControl#947]
Hello, I'd like to propose an important improvement for TransitioningContentControl: 

### Actual:
**TransitioningContentControl** does not transition with cool animation when `Content` dependency property changes.

### Expected:
**TransitioningContentControl** should also transition with cool animation when content changes (specifically when change is invoked by DataBinding mechanism)

### Remarks:
Right now the cool animation of transition is started only when visibility of the `TransitioningContentControl` changes. I think it should also play transitrion animation when content is changed. This is very desirable behavior for extension of `ContentControl`.
Please see https://mahapps.com/docs/controls/transitioningcontentcontrol for example.

Also the fix seems very simple, just invoke `StartTransition()` in `TransitioningContentControl.cs` when content changes.

Thanks

**Comment by jhm-ciberman** [comment]
This would be very useful. In fact, when I started using this control for the first time I thought It wasn't working because this was the behavior I was expecting.

**Comment by jhm-ciberman** [comment]
Thanks @NaBian for the work! Amazing!
