### ISSUE TITLE
引入后Theme.xaml，全部label样式都带边框等样式

### ISSUE THREAD

**Issue by ZevFung** [HandyOrg/HandyControl#956]
引入后Theme.xaml，自己写的label样式都带边框等样式。	

查看源码：
<Style BasedOn="{StaticResource LabelBaseStyle}" TargetType="Label">
		<Setter Property="Foreground" Value="{DynamicResource PrimaryTextBrush}" />
		<Setter Property="BorderThickness" Value="1" />
	</Style>

如何去掉这个影响呢

**Comment by maydark** [comment]
可以自己定义一个默认样式覆盖

**Comment by NaBian** [comment]
style = null
