### ISSUE TITLE
[Feature request] Spanish localization (I can translate all the texts)

### ISSUE THREAD

**Issue by jhm-ciberman** [HandyOrg/HandyControl#959]
Hello. We are developing a desktop app using HandyControl that target spanish speaking users. I would like to request if possible to add Spanish translations

I can translate all the texts to Spanish if you like. I just don't have the time to learn how to build HandyControl and add the language by myself, but I can provide you with the localization files translated to spanish. 

Edit: Here is the fully translated XML File: https://gist.github.com/jhm-ciberman/360da01f5c9af201ca981311eb6ceaf6
The only key I left untranslated was "LangComment" because I don't know where is used. I used the english file as a template (because I don't know chinese). I adapted some words to better reflect the intentions in the UI.

I can make a PR if you point me how to properly add the lang files. But it would be easier for me if you add them yourself. Thanks!

**Comment by ghost1372** [comment]
we already support **ca-es** language. Doesn't it meet your needs?
if no please translate demo language too.
https://github.com/HandyOrg/HandyControl/tree/master/src/Shared/HandyControlDemo_Shared/Properties/Langs

**Comment by jhm-ciberman** [comment]
Hi! `ca-ES` is the language Catalan. Catalan is only speaked in a specific region of Spain (Catalonia) and it's very different from spanish. In the other hand, Spanish language code is `es` and is speaked in a much wider number of countries (Spain, and all Latin America). For example, I'm from Argentina (`es-AR`). 

> if no please translate demo language too.

Sure! I will make the translations as soon as I reach home. Thank you. 

Question: What is the "LangComment" text used for?

**Comment by ghost1372** [comment]
Thank you
LangComment is not used

**Comment by jhm-ciberman** [comment]
Hi again. I've updated the same gist with both files: https://gist.github.com/jhm-ciberman/360da01f5c9af201ca981311eb6ceaf6

 I tried to preserve all the "tecnical" words in english whereas all the human friendly messages that would normally be displayed in a UI for an end user are in spanish. 
 
I haven't checked recompiling the demo. Can you please check for me if I left some non technical word without translation or if I miss translated some class name to spanish? Some words are written in `CammelCase` so are easy to identify, but some others have only one word so it's tricky to know if it's some word that appears on the left panel inside the demo app. 

Thank you!

**Comment by ghost1372** [comment]
Thank you Everythings is OK 😉
I Added a [PR](https://github.com/HandyOrg/HandyControl/pull/962), After review by @NaBian , it can be Merged and will be added in the next update

**Comment by jhm-ciberman** [comment]
Thank you! You're awesome

**Comment by NaBian** [comment]
I've been so busy these days
