### ISSUE TITLE
What is ContextMenuButton used for?

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#960]
I read the [doc](https://hosseini.ninja/handycontrol/extend_controls/contextMenuButton/index.html) on ContextMenuButton and it doesn't seem to be clear.
Is the button used for displaying a context-menu when the button is left clicked or is the button meant to placed in a context-menu as a menu-item?

**Comment by NaBian** [comment]
it‘s simple, left click the button, the contextmenu will show.
