### ISSUE TITLE
Win11 rounded border support is problematic

### ISSUE THREAD

**Issue by superowner** [HandyOrg/HandyControl#968]
![sp210827_091719](https://user-images.githubusercontent.com/15080614/131056985-2e596ebc-da20-4796-a99b-75adf4b21a0e.png)

**Environment **
 - Edition	Windows 11 Pro 21H2 OS build 22000.160
 - .net 5/.net4.8
 - vs2019

**Comment by ghost1372** [comment]
Thank you @superowner 
This issue is related to GlowWindows

**Comment by ghost1372** [comment]
I close this issue and we follow it in a new [issue](https://github.com/HandyOrg/HandyControl/issues/1033)
