### ISSUE TITLE
HandyControl Windows Issues in Windows 11

### ISSUE THREAD

**Issue by ghost1372** [HandyOrg/HandyControl#969]
These are the problems that exist right now
- Border Rounded Corner Issue for GlowWindows (Reported [Here](https://github.com/HandyOrg/HandyControl/issues/968) and i think this issue can be fixed easily)
- AcrylicBlur is disabled in Windows 11
- None of the windows, Do not display accent colors (windows 11 GlowWindows features)
- Snap Layout Cant be Displayed

## AcrylicBlur is disabled in Windows 11
This does not matter because it is disabled in Windows itself. and **ACCENT_ENABLE_ACRYLICBLURBEHIND**  automatically change to **ACCENT_ENABLE_BLURBEHIND**

![Untitled4](https://user-images.githubusercontent.com/9213496/131079849-974be00a-3116-4dcb-8b40-2466aa0cf8d1.png)

## None of the windows, Do not display accent colors (windows 11 GlowWindows features)
In Windows 11, by activating **enable accent color on title bars and windows borders**,  All windows use the GlowWindows like feature. (red border around window)
![Untitled](https://user-images.githubusercontent.com/9213496/131079085-cd476b54-42af-4605-8838-6281dbf7b45f.png)

and this is handycontrol window/Blurwindow/GlowWindow Which does not support Windows 11 border accent color
![Untitled3](https://user-images.githubusercontent.com/9213496/131079836-4349fd69-6376-4b5d-99c5-48024fcbfe75.png)

This is what I think for GlowWindow:
The GlowWindows should work as before, except that it automatically detects the version of the operating system and if it was running on Windows 11. We need to check if **enable accent color on title bars and windows borders** is enabled, disable HandyControl GlowWindows and we should use windows 11 GlowWindows. 
There should also be a boolean property called (ForceHcGlowWindowsInWin11) so that if the user needs to continue to use handyControl GlowWindows in windows 11

**Comment by ghost1372** [comment]
## Snap Layout Cant be Displayed

I found another problem
In Windows 11, if we put the mouse on the maximize button, the Snap layout window will open.
![1](https://user-images.githubusercontent.com/9213496/131092669-64eaed29-d81c-4a69-93d0-f4b2502742b0.png)

But none of handyControl Windows (Blurwindow/GlowWindow/Window) does not supports this feature

**Comment by ghost1372** [comment]
@NaBian It has been more than 2 months since the release of the latest version. Since the release of the next version is imminent, it is best to resolve these issues before releasing

**Comment by ghost1372** [comment]
> ## Snap Layout Cant be Displayed
> I found another problem In Windows 11, if we put the mouse on the maximize button, the Snap layout window will open. ![1](https://user-images.githubusercontent.com/9213496/131092669-64eaed29-d81c-4a69-93d0-f4b2502742b0.png)
> 
> But none of handyControl Windows (Blurwindow/GlowWindow/Window) does not supports this feature

https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu
https://github.com/dotnet/wpf/issues/4825

**Comment by ghost1372** [comment]
@NaBian  any idea?

**Comment by NaBian** [comment]
I don't have Window 11, i have no idea 😭 .

**Comment by ghost1372** [comment]
> I don't have Window 11, i have no idea 😭 .

😅 Be up to date

**Comment by ghost1372** [comment]
I close this issue and we follow it in a new [issue](https://github.com/HandyOrg/HandyControl/issues/1033)
