### ISSUE TITLE
Not change FontSize of Button if set FontSize for  window 

### ISSUE THREAD

**Issue by Mohadin** [HandyOrg/HandyControl#970]
When I set FontSize property in window change all element font size in window but button not change .

Environment:
 - .net: [4.6.2]
 - IDE [e.g. vs2019]
 - Version [3.2.0.0]

**Comment by konglhui** [comment]
use Style="{StaticResource ButtonCustom}" is work

**Comment by konglhui** [comment]
or Height="Auto"
