### ISSUE TITLE
使用Growl通知报调用目标发生了异常

### ISSUE THREAD

**Issue by LiuFu2014** [HandyOrg/HandyControl#972]
**Describe the bug**
使用Growl通知报调用目标发生了异常。
代码：
                    Growl.SuccessGlobal(new GrowlInfo()
                    {
                        Message =“test”,
                        ShowDateTime = true,
                        ShowCloseButton = true,
                        WaitTime = 5
                    });

**To Reproduce**
1. 调用代码，桌面右上角弹出通知
2. 等待几秒钟后，捕获到异常

**Expected behavior**
推测在等待5秒后，自行关闭时发生了异常

**Environment (please complete the following information):**
 - .net: 4.8
 - IDE  VS2019
 - Version :3.2

**Additional context**
e.tostring()如下：
System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.ComponentModel.Win32Exception: 0x80070578
   在 Standard.HRESULT.ThrowIfFailed(String message)
   在 Standard.HRESULT.ThrowLastError()
   在 Standard.NativeMethods.GetWindowRect(IntPtr hwnd)
   在 System.Windows.Shell.WindowChromeWorker.GetEffectiveClientArea(RECT& rcClient)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   在 System.Windows.Interop.HwndMouseInputProvider.HasCustomChrome(HwndSource hwndSource, RECT& rcClient)
   在 System.Windows.Interop.HwndMouseInputProvider.GetEffectiveClientRect(IntPtr hwnd)
   在 System.Windows.Interop.HwndMouseInputProvider.PossiblyDeactivate(IntPtr hwndCapture, Boolean stillActiveIfOverSelf)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
e.Exception.InnerException.ToString()如下：
System.ComponentModel.Win32Exception (0x80004005): 0x80070578
   在 Standard.HRESULT.ThrowIfFailed(String message)
   在 Standard.HRESULT.ThrowLastError()
   在 Standard.NativeMethods.GetWindowRect(IntPtr hwnd)
   在 System.Windows.Shell.WindowChromeWorker.GetEffectiveClientArea(RECT& rcClient)

**Comment by NaBian** [comment]
Duplicate #867
