### ISSUE TITLE
Button Icon not visible in light theme when ButtonIcon style is used for the button.

### ISSUE THREAD

**Issue by ms-somanna** [HandyOrg/HandyControl#974]
HandyControls version: 3.3.7

**Comment by ghost1372** [comment]
You are definitely using it incorrectly
        
`<Button Style="{StaticResource ButtonIcon}" Foreground="{DynamicResource PrimaryTextBrush}" hc:IconElement.Geometry="{StaticResource UpDownGeometry}"/>
`
![Animation](https://user-images.githubusercontent.com/9213496/131701388-8501d25a-b48a-4a75-9aa5-9d8fea6a550a.gif)

**Comment by ms-somanna** [comment]
> You are definitely using it incorrectly
>         
> `<Button Style="{StaticResource ButtonIcon}" Foreground="{DynamicResource PrimaryTextBrush}" hc:IconElement.Geometry="{StaticResource UpDownGeometry}"/>
> `
> ![Animation](https://user-images.githubusercontent.com/9213496/131701388-8501d25a-b48a-4a75-9aa5-9d8fea6a550a.gif)
> 

Hmm, I hadn't set the foreground property and thats why the geometry wasn't visible.
But can you tell me as to why the foreground property is not defined in the style definition of ButtonIcon?

**Comment by ghost1372** [comment]
Recently nabian added foreground property so in the next version everythings is ok and you dont need to add this property anymore
