### ISSUE TITLE
Growl.SuccessGlobal 方法导致崩溃

### ISSUE THREAD

**Issue by CCbugCC** [HandyOrg/HandyControl#978]
你好，反馈个bug, 版本3.2中 （之前版本也是） 调用Growl.SuccessGlobal(message)，不设置token，显示通知，如果当前窗口最大化，或者有窗口处于通知的底部，鼠标指针从窗口滑动到通知那里会报错崩溃。

**Comment by CCbugCC** [comment]
![GIF 2021-9-2 10-02-05](https://user-images.githubusercontent.com/37820738/131769566-365cefa9-1a1e-4614-b0e3-b11c0c677731.gif)
这个是重现效果

**Comment by NaBian** [comment]
请在提 issue 前先搜索是否有相关类似的 issue，确认没有时再开辟一个新的 issue
