### ISSUE TITLE
[Feature request] Add x:Key to Datagrid, ListView style

### ISSUE THREAD

**Issue by Yopler** [HandyOrg/HandyControl#980]
**Is your feature request related to a problem? Please describe.**
I really like the default style of the Datagrid but I can't make my own default Datagrid Style base on the Handy Control one. I have see that the same problem is present for the ListView style, and maybe some others.

**Describe the solution you'd like**
It's possible to add a `x:Key = DataGridBaseStyle`  (using the default naming of the other BaseStyle) to the DataGrid Style and then make it default `<Style TargetType="DataGrid" BaseOn="{StaticRessource DataGridBaseStyle}"/>`

**Describe alternatives you've considered**
A first alternative is to make all the changes on the `<DataGrid/>`  Tag.
But Currently I have litterally copy/paste the default style and made the Changes I wanted.

PS : Sorry for this approximative English ! ^^

**Comment by ghost1372** [comment]
you can use like this

`<Style TargetType="DataGrid" BasedOn="{StaticResource {x:Type DataGrid}}"/>
`

**Comment by Yopler** [comment]
Doesn't seem to work for me.

Here an example of the kind of changes I want to make : 
```xaml
<Style x:Key="CustomDataGridRowStyle" TargetType="DataGridRow" BasedOn="{StaticResource DataGridRowStyle}">
        <Setter Property="Background" Value="{StaticResource LayerBackground}"/>
</Style>

<Style TargetType="DataGrid" BasedOn="{StaticResource {x:Type DataGrid}}">
        <Setter Property="AutoGenerateColumns" Value="False"/>
        <Setter Property="Background" Value="Transparent"/>
        <Setter Property="RowStyle" Value="{StaticResource CustomDataGridRowStyle}"/>
</Style>
```

And I get the following result : 
![image](https://user-images.githubusercontent.com/45144437/131971946-8dcce078-ad4a-47fc-bf0d-42591e817849.png)


I feel like it takes the default style of WPF and not the one of HandyControl.

**Comment by ghost1372** [comment]
> ```
> BasedOn="{StaticResource {x:Type DataGrid}}"
> ```

Change `BasedOn="{StaticResource DataGridRowStyle}"` to `BasedOn="{StaticResource {x:Type DataGridRowStyle}}"`

**Comment by Yopler** [comment]
Same problem !

But I just found a solution ! 
In the previous comment, the style Tag was on the App.xaml file.
The `<Style TargetType="DataGrid" BasedOn="{StaticResource {x:Type DataGrid}}"/>` solution works if it is in another file ressources. I suggest in the MainWindow.xaml file to make it use in the all application.

However, I think it can be an improvement to create an `x:Key = DataGridBaseStyle` ^^

**Comment by ghost1372** [comment]
@NaBian  do you have any idea? can we make **x:Key = DataGridBaseStyle**?

**Comment by NaBian** [comment]
if you want to custom datagrid style, you can refer to datagrid.small style, it's easy.

**Comment by Yopler** [comment]
Close` x:key="Datagrid.Small"` with commits 
- 3e85278214f1cdc55ce50d4f4bcf40a8855ffac0
- e31c31b0db7b9819bc7c30f35146b517638d82e4

**Comment by Yopler** [comment]
My bad, `ListView `doesn't have a `x:Key` yet 😅😅
