### ISSUE TITLE
当Datagrid设置为单选模式的时候依然可以点击全选，并且点击后会报错

### ISSUE THREAD

**Issue by my522cn** [HandyOrg/HandyControl#987]
**Describe the bug**
 当Datagrid设置为SelectionMode="Single"时，全选按钮依然生效，并且点击后会报错：

`System.NotSupportedException:“CanSelectMultipleItems 为 true 时只能调用 SelectAll。”`

**Comment by NaBian** [comment]
无法复现

**Comment by my522cn** [comment]
![demo](https://user-images.githubusercontent.com/11346219/133542296-94315807-b7b7-4fd2-a350-7018bcb91bd9.gif)

**Comment by NaBian** [comment]
想必这个 issue 和 #1075 一样，用的是非官方库，一并关闭了，如果不是，还请麻烦再开启 issue 哈。

**Comment by my522cn** [comment]
确实是的，非常感谢

**Comment by ghost1372** [comment]
Thank you @my522cn 
Issue Fixed

**Comment by my522cn** [comment]
@ghost1372 it's a good news, thank you.
