### ISSUE TITLE
[Bug] hc:SideMenu Not supporting `ItemsSource`? 

### ISSUE THREAD

**Issue by jhm-ciberman** [HandyOrg/HandyControl#988]
**Describe the bug**
The `ItemsSource` attribute don't seems to be supported by the SideMenu component

**To Reproduce**

Create a simple ViewModel
```csharp
public List<string> HeadersList {get;} = new List<string> { "Foo", "Bar", "Boo", "Zig" };
```

Create a new View with that uses that ViewModel as DataContext and then create a SideMenu:
```xaml
<hc:SideMenu Width="200" ItemsSource="{Binding HeadersList}">
    <hc:SideMenu.ItemTemplate>
        <DataTemplate>
            <hc:SideMenuItem Header="{Binding}"/>
        </DataTemplate>
    </hc:SideMenu.ItemTemplate>
</hc:SideMenu>
```
The binding is done correctly but nothing shows on the screen. 

**Expected behavior**
The ItemsSource should be supported, in this way the menu can be customized using the MVVM pattern. 

**Screenshots**
Nothing shows on the screen. 

**Environment (please complete the following information):**
 - .net: NET 5.0
 - IDE VS2019
 - Version HandyControls 3.3.7 (I'm using the forked version, but I think this should be reported here in the main repo)

**Comment by NaBian** [comment]
duplicate #335

**Comment by jhm-ciberman** [comment]
Thank you. I ended up using a ListBox with a bunch of custom styling so it looks cool. But is not as great as the SideMenu component.
