### ISSUE TITLE
Cannot manually set the `Height` of the hc:ComboBox

### ISSUE THREAD

**Issue by jhm-ciberman** [HandyOrg/HandyControl#989]
**Describe the bug**
The height property will only affect to the global area filled by the ComboBox and not the height of the selection area. 

**To Reproduce**

Create a `ComboBox` from XAML:

```xaml

<hc:ComboBox
    Margin="20"
    MaxWidth="200"
    Height="60"
    hc:InfoElement.Title="Select a value" 
    hc:TitleElement.TitlePlacement="Top"
    hc:InfoElement.Placeholder="Please select"
    hc:InfoElement.Necessary="True"/>
```

The height property will only affect to the global area filled by the ComboBox and not the height of the selection area. 

**Expected behavior**
The height property should affect the global area filled by the ComboBox and not the height of the selection area. 

**Screenshots**
I have a combo box with an `ItemTemplate`, so I can show a content with an icon and a rich format. 
When the screens opens the combo box should be shown without any selection. 
The problem is that the height of the `ItemTemplate` is greater than the combo box initial height. I want the height of the combo box to be the same height of the `ItemTemplate`. Manually setting the `Height` property of the `hc:ComboBox` component seems to have no effect. 

![image](https://user-images.githubusercontent.com/7988351/132892496-cf3f5f18-105f-4024-8c8e-79818fccff2a.png)

In this picture, both combo boxes are equal. The combo box of the left has an item selected, the combo box of the right has no item selected. Both `ComboBox` have their `Height` property set to the same value, but the height is ignored.

**Environment (please complete the following information):**
 - .net: NET 5.0
 - IDE VS2019
 - Version HandyControls 3.3.7 (I'm using the forked version, but I think this should be reported here in the main repo)

**Comment by NaBian** [comment]
hc:InfoElement.ContentHeight

**Comment by jhm-ciberman** [comment]
Wow. Amazing! Thank you!
